import type { CurriculumLesson, UnitReviewQuestion } from "@/content/part1-curriculum";
import type { LocalizedText } from "@/lib/types";

const L = (en: string, ar: string): LocalizedText => ({ en, ar });

const choice = (id: string, prompt: LocalizedText, answer: string, options: Array<[string, LocalizedText]>, explanation: LocalizedText): UnitReviewQuestion => ({
  id,
  kind: "choice",
  prompt,
  answer,
  choices: options.map(([optionId, text]) => ({ id: optionId, text })),
  explanation,
});

const reviewQuestions: UnitReviewQuestion[] = [
  choice("unit1-review-1", L("Which sequence best describes the broad development of information technology?", "أي تسلسل يصف التطور العام لتكنولوجيا المعلومات؟"), "a", [["a", L("Early specialist computers → personal computers → Web → mobile → cloud", "الحواسيب المتخصصة المبكرة ← الحواسيب الشخصية ← الويب ← المحمول ← السحابة")], ["b", L("Cloud → early computers → mobile → Web → personal computers", "السحابة ← الحواسيب المبكرة ← المحمول ← الويب ← الحواسيب الشخصية")], ["c", L("Mobile → Web → early computers → cloud → personal computers", "المحمول ← الويب ← الحواسيب المبكرة ← السحابة ← الحواسيب الشخصية")]], L("Each era widened access and changed how people use information.", "وسّعت كل مرحلة الوصول وغيّرت طريقة استخدام الناس للمعلومات.")),
  choice("unit1-review-2", L("Why can an autonomous vehicle need edge computing for some decisions?", "لماذا قد تحتاج المركبة ذاتية القيادة إلى الحوسبة الطرفية لبعض القرارات؟"), "b", [["a", L("It removes every need for a network", "تلغي كل حاجة إلى الشبكة")], ["b", L("A local decision can avoid unsafe delay", "يمكن للقرار المحلي تجنب التأخير غير الآمن")], ["c", L("It makes all data public", "تجعل كل البيانات عامة")]], L("Edge processing keeps time-critical decisions near the data source.", "تبقي المعالجة الطرفية القرارات الحساسة للوقت قريبة من مصدر البيانات.")),
  choice("unit1-review-3", L("Which statement correctly relates AI, machine learning, deep learning, and generative AI?", "أي عبارة تربط الذكاء الاصطناعي وتعلم الآلة والتعلم العميق والذكاء التوليدي بصورة صحيحة؟"), "a", [["a", L("Machine learning is part of AI; deep learning is part of machine learning; generative AI can use deep learning", "تعلم الآلة جزء من الذكاء الاصطناعي؛ والتعلم العميق جزء من تعلم الآلة؛ ويمكن للذكاء التوليدي استخدام التعلم العميق")], ["b", L("They are four unrelated names for the same method", "هي أربعة أسماء غير مترابطة للطريقة نفسها")], ["c", L("Generative AI is outside AI", "الذكاء التوليدي خارج الذكاء الاصطناعي")]], L("The terms describe nested or related approaches, not separate labels.", "تصف المصطلحات أساليب متداخلة أو مترابطة وليست تسميات منفصلة.")),
  choice("unit1-review-4", L("A model gives a confident answer with no reliable evidence. What is the best next action?", "يقدم نموذج إجابة واثقة بلا دليل موثوق. ما أفضل إجراء تالٍ؟"), "c", [["a", L("Treat confidence as proof", "اعتبر الثقة دليلاً")], ["b", L("Share the answer without checking", "انشر الإجابة دون تحقق")], ["c", L("Check important claims against trusted sources", "تحقق من الادعاءات المهمة بمصادر موثوقة")]], L("Convincing output can still be inaccurate, so important claims need verification.", "قد تكون المخرجات المقنعة غير دقيقة، لذلك تحتاج الادعاءات المهمة إلى تحقق.")),
  choice("unit1-review-5", L("A music service uses listening history to suggest songs. This is mainly an example of:", "تستخدم خدمة موسيقى سجل الاستماع لاقتراح أغانٍ. هذا مثال أساسي على:"), "a", [["a", L("a recommendation system using behaviour patterns", "نظام توصية يستخدم أنماط السلوك")], ["b", L("a guarantee that the learner will like every song", "ضمان أن المتعلم سيحب كل أغنية")], ["c", L("a decision that needs no data", "قرار لا يحتاج بيانات")]], L("Recommendations infer likely preferences from available patterns.", "تستنتج التوصيات تفضيلات محتملة من الأنماط المتاحة.")),
  choice("unit1-review-6", L("Which use should retain the strongest human oversight?", "أي استخدام ينبغي أن يحتفظ بأقوى رقابة بشرية؟"), "b", [["a", L("Sorting similar product images", "فرز صور منتجات متشابهة")], ["b", L("Deciding a patient’s treatment priority", "تحديد أولوية علاج مريض")], ["c", L("Suggesting a delivery route to check", "اقتراح مسار توصيل للتحقق منه")]], L("High-impact decisions affecting people need accountable human judgment.", "القرارات عالية الأثر التي تؤثر في الناس تحتاج إلى حكم بشري مسؤول.")),
  choice("unit1-review-7", L("A hiring tool was trained mostly on past applicants from one group. What risk should the team investigate?", "دُرّبت أداة توظيف أساسًا على متقدمين سابقين من مجموعة واحدة. أي خطر ينبغي للفريق فحصه؟"), "a", [["a", L("Algorithmic bias caused by unrepresentative data", "تحيز خوارزمي ناتج عن بيانات غير ممثلة")], ["b", L("A faster internet connection", "اتصال إنترنت أسرع")], ["c", L("A brighter screen", "شاشة أكثر سطوعًا")]], L("A limited historical dataset can teach an unfair pattern.", "يمكن لمجموعة بيانات تاريخية محدودة أن تعلّم نمطًا غير عادل.")),
  choice("unit1-review-8", L("What does transparency add to an AI-supported decision?", "ماذا تضيف الشفافية إلى قرار مدعوم بالذكاء الاصطناعي؟"), "c", [["a", L("It promises that no errors are possible", "تعد بأن الأخطاء مستحيلة")], ["b", L("It removes responsibility from people", "تلغي مسؤولية الناس")], ["c", L("It makes relevant reasons easier to understand and question", "تجعل الأسباب المهمة أسهل للفهم والمساءلة")]], L("Transparency supports informed checking and meaningful challenge.", "تدعم الشفافية التحقق الواعي والاعتراض الهادف.")),
  { id: "unit1-review-9", kind: "matching", prompt: L("Match each technology concept to its most appropriate description.", "صل كل مفهوم تقني بوصفه الأنسب."), pairs: [{ id: "cloud", left: L("Cloud computing", "الحوسبة السحابية"), right: L("Networked computing resources delivered as services", "موارد حوسبة شبكية تقدم كخدمات") }, { id: "edge", left: L("Edge computing", "الحوسبة الطرفية"), right: L("Processing close to where data is created", "معالجة قريبة من مكان إنشاء البيانات") }, { id: "ar", left: L("Augmented reality", "الواقع المعزز"), right: L("Digital information added to the real world", "معلومات رقمية تضاف إلى العالم الحقيقي") }, { id: "vr", left: L("Virtual reality", "الواقع الافتراضي"), right: L("Immersive computer-generated environment", "بيئة رقمية غامرة مولدة بالحاسوب") }], explanation: L("The concepts have different jobs: services at a distance, local speed, added information, and immersion.", "للمفاهيم وظائف مختلفة: خدمات عن بعد وسرعة محلية ومعلومات مضافة وانغماس." ) },
  { id: "unit1-review-10", kind: "matching", prompt: L("Classify each concern under the principle that responds most directly to it.", "صنّف كل قلق تحت المبدأ الذي يستجيب له مباشرة."), pairs: [{ id: "fairness", left: L("Check different groups for unjust disadvantage", "تحقق من المجموعات المختلفة لمنع الضرر غير العادل"), right: L("Fairness", "الإنصاف") }, { id: "privacy", left: L("Collect only justified personal data and protect it", "اجمع البيانات الشخصية المبررة فقط واحمها"), right: L("Privacy protection", "حماية الخصوصية") }, { id: "transparent", left: L("Give relevant reasons for an important outcome", "قدم أسبابًا مهمة لنتيجة مؤثرة"), right: L("Transparency", "الشفافية") }, { id: "accountable", left: L("Name who monitors harm and responds", "حدد من يراقب الضرر ويستجيب له"), right: L("Accountability", "المساءلة") }], explanation: L("Responsible AI uses all four principles together.", "يستخدم الذكاء الاصطناعي المسؤول المبادئ الأربعة معًا." ) },
  { id: "unit1-review-11", kind: "ordering", prompt: L("Put this responsible school-AI design process in order.", "رتب عملية تصميم ذكاء اصطناعي مدرسي مسؤول."), order: [{ id: "need", text: L("Define the learning or communication need", "حدد حاجة التعلم أو التواصل") }, { id: "data", text: L("Choose necessary, protected data", "اختر البيانات الضرورية والمحميّة") }, { id: "check", text: L("Test for usefulness, bias, and privacy risks", "اختبر الفائدة والتحيز ومخاطر الخصوصية") }, { id: "human", text: L("Keep a person responsible for important decisions", "أبقِ شخصًا مسؤولًا عن القرارات المهمة") }, { id: "improve", text: L("Monitor feedback and improve safeguards", "راقب التغذية الراجعة وحسّن الضمانات") }], explanation: L("A responsible service starts with a need, handles data carefully, checks harms, and continues to improve.", "تبدأ الخدمة المسؤولة بحاجة، وتعالج البيانات بعناية، وتفحص الأضرار، وتستمر في التحسين." ) },
  { id: "unit1-review-12", kind: "ordering", prompt: L("Order the path from data to a carefully checked AI-supported action.", "رتب المسار من البيانات إلى إجراء مدعوم بالذكاء الاصطناعي تم التحقق منه بعناية."), order: [{ id: "examples", text: L("Collect relevant examples", "اجمع أمثلة ذات صلة") }, { id: "pattern", text: L("Find or learn a pattern", "اعثر على نمط أو تعلمه") }, { id: "output", text: L("Produce a prediction or suggestion", "أنتج تنبؤًا أو اقتراحًا") }, { id: "verify", text: L("Check the result and its limits", "تحقق من النتيجة وحدودها") }, { id: "decide", text: L("Make an accountable decision", "اتخذ قرارًا خاضعًا للمساءلة") }], explanation: L("Pattern-based output is an input to judgment, not the final authority.", "المخرجات القائمة على الأنماط مدخل للحكم وليست السلطة النهائية." ) },
  choice("unit1-review-13", L("A school app wants to recommend revision resources. Which data choice is most privacy-aware?", "يريد تطبيق مدرسي اقتراح موارد للمراجعة. أي اختيار للبيانات أكثر مراعاة للخصوصية؟"), "b", [["a", L("Collect every message and contact list by default", "اجمع كل رسالة وقائمة جهات اتصال تلقائيًا")], ["b", L("Use only the learning topics and completed tasks needed for the feature", "استخدم موضوعات التعلم والمهام المكتملة اللازمة للميزة فقط")], ["c", L("Publish individual activity histories", "انشر سجلات النشاط الفردية")]], L("Data minimisation limits collection to what the stated purpose genuinely needs.", "يحد تقليل البيانات من الجمع إلى ما يحتاجه الغرض المعلن فعلًا.")),
  choice("unit1-review-14", L("A face-recognition attendance tool often fails for some learners. What is the most responsible immediate response?", "تفشل أداة حضور بالتعرف على الوجه كثيرًا مع بعض المتعلمين. ما الاستجابة الفورية الأكثر مسؤولية؟"), "a", [["a", L("Pause harmful use, investigate fairness, and offer a non-biometric alternative", "أوقف الاستخدام الضار وافحص الإنصاف وقدّم بديلًا غير حيوي")], ["b", L("Ignore the failures because the system is automated", "تجاهل الإخفاقات لأن النظام آلي")], ["c", L("Require learners to retry until it works", "اطلب من المتعلمين المحاولة حتى تعمل")]], L("A responsible organisation notices harm, protects people, investigates, and provides a fair alternative.", "تلاحظ المؤسسة المسؤولة الضرر وتحمي الناس وتحقق وتوفر بديلًا عادلًا.")),
  choice("unit1-review-15", L("Which statement best joins the four Unit 1 lessons?", "أي عبارة تجمع دروس الوحدة الأولى الأربعة بأفضل صورة؟"), "c", [["a", L("Technology and AI always make decisions more objective", "التقنية والذكاء الاصطناعي يجعلان القرارات أكثر موضوعية دائمًا")], ["b", L("More data removes the need to think about people", "المزيد من البيانات يلغي الحاجة إلى التفكير في الناس")], ["c", L("Useful technology combines technical capability with careful data, human judgment, and ethical safeguards", "تجمع التقنية المفيدة بين القدرة التقنية والبيانات الدقيقة والحكم البشري والضمانات الأخلاقية")]], L("The unit connects how technology develops, how AI uses patterns, where it helps, and how people remain protected.", "تربط الوحدة تطور التقنية وكيف يستخدم الذكاء الاصطناعي الأنماط وأين يساعد وكيف تبقى حماية الناس.")),
  choice("unit1-review-16", L("Which improvement best shows accountability after a school AI service makes an unfair recommendation?", "أي تحسين يوضح المساءلة بعد أن تقدم خدمة ذكاء اصطناعي مدرسية توصية غير عادلة؟"), "b", [["a", L("Hide the outcome so nobody asks about it", "أخفِ النتيجة حتى لا يسأل عنها أحد")], ["b", L("Correct the outcome, review data and rules, tell affected users how to appeal, and monitor the fix", "صحح النتيجة وراجع البيانات والقواعد وأخبر المتأثرين بكيفية الاعتراض وراقب الإصلاح")], ["c", L("Say the model—not people—is responsible", "قل إن النموذج لا الناس هو المسؤول")]], L("Accountability means a person or organisation owns the response and improvement.", "تعني المساءلة أن شخصًا أو مؤسسة يتولى الاستجابة والتحسين.")),
];

export const unit1LessonOverrides: Record<string, Pick<CurriculumLesson, "challenge" | "reflection" | "unitReview" | "extraTaskCount">> = {
  "it-and-society": {
    challenge: {
      id: "community-center-transform",
      title: L("Think as an Engineer: a community centre for every resident", "فكر كمهندس: مركز مجتمعي يخدم كل السكان"),
      prompt: L("A local community centre posts information only on paper, answers questions in person, and records event registrations by hand. Design a realistic first digital change while keeping the centre usable for older residents and people without reliable Internet access.", "ينشر مركز مجتمعي محلي معلوماته على الورق فقط، ويجيب عن الأسئلة حضوريًا، ويسجل الفعاليات يدويًا. صمم أول تغيير رقمي واقعي مع إبقاء المركز قابلًا للاستخدام لكبار السن ولمن لا يملكون اتصالًا موثوقًا بالإنترنت."),
      successCriteria: [L("Choose one concrete service problem to solve first.", "اختر مشكلة خدمة محددة لحلها أولًا."), L("Connect an appropriate technology to a named group of residents and a clear benefit.", "اربط تقنية مناسبة بمجموعة محددة من السكان وفائدة واضحة."), L("Keep a realistic non-digital support or access alternative.", "أبقِ دعمًا غير رقمي أو بديل وصول واقعيًا."), L("State how the centre could recognise that the change is helping.", "اذكر كيف يمكن للمركز معرفة أن التغيير مفيد.")],
    },
    reflection: {
      transfer: L("Transfer: a school library wants fewer missed events without excluding families who prefer paper notices. Which first change would you recommend?", "نقل: تريد مكتبة مدرسية تقليل تفويت الفعاليات دون استبعاد الأسر التي تفضل الإشعارات الورقية. ما أول تغيير توصي به؟"),
      pairDiscussion: L("Discuss one digital benefit and one access risk with a partner in class. Then record your own conclusion.", "ناقش فائدة رقمية واحدة وخطر وصول واحد مع زميل داخل الفصل، ثم سجل خلاصتك الخاصة."),
      individualPrompt: L("Which non-digital support would you keep, and why?", "أي دعم غير رقمي ستبقيه، ولماذا؟"),
    },
    extraTaskCount: 1,
  },
  "how-ai-works": {
    challenge: {
      id: "revision-recommendations",
      title: L("Think as an Engineer: revision recommendations with a human check", "فكر كمهندس: توصيات مراجعة مع فحص بشري"),
      prompt: L("A school wants to suggest revision topics to learners. Plan the input data, the pattern the system could look for, the recommendation it should produce, and the human check that keeps the suggestion from becoming an unchecked final decision.", "تريد مدرسة اقتراح موضوعات مراجعة للمتعلمين. خطط لبيانات الإدخال والنمط الذي قد يبحث عنه النظام والتوصية التي ينبغي أن ينتجها والفحص البشري الذي يمنع الاقتراح من أن يصبح قرارًا نهائيًا بلا تحقق."),
      successCriteria: [L("Use learning evidence that is relevant to the recommendation.", "استخدم دليل تعلم ذي صلة بالتوصية."), L("Describe a pattern and an output rather than treating AI as magic.", "صف نمطًا ومخرجًا بدل التعامل مع الذكاء الاصطناعي كسحر."), L("Name one way incomplete data could mislead the recommendation.", "اذكر طريقة واحدة قد تضلل بها البيانات الناقصة التوصية."), L("Keep a teacher or learner able to check and question the result.", "أبقِ المعلم أو المتعلم قادرًا على فحص النتيجة والاعتراض عليها.")],
    },
    reflection: {
      transfer: L("Transfer: a music app suggests songs from listening history. What pattern could it use, and what can it not know for certain?", "نقل: يقترح تطبيق موسيقى أغانٍ من سجل الاستماع. ما النمط الذي يمكن أن يستخدمه، وما الذي لا يستطيع معرفته بيقين؟"),
      pairDiscussion: L("Compare one useful data choice and one misleading data gap with a partner, then write your own conclusion.", "قارن اختيار بيانات مفيدًا وفجوة بيانات مضللة مع زميل، ثم اكتب خلاصتك الخاصة."),
      individualPrompt: L("What should a learner be told before relying on an AI recommendation?", "ما الذي ينبغي إخبار المتعلم به قبل الاعتماد على توصية من الذكاء الاصطناعي؟"),
    },
    extraTaskCount: 1,
  },
  "ai-in-life": {
    challenge: {
      id: "city-ai-service",
      title: L("Think as an Engineer: an AI-assisted city service", "فكر كمهندس: خدمة مدينة مدعومة بالذكاء الاصطناعي"),
      prompt: L("A city wants to improve one public service with AI: transport, waste collection, healthcare appointments, agriculture support, customer support, or traffic management. Choose a service and balance its benefit with the data, risks, and human checking it needs.", "تريد مدينة تحسين خدمة عامة واحدة بالذكاء الاصطناعي: النقل أو جمع النفايات أو مواعيد الرعاية الصحية أو دعم الزراعة أو دعم العملاء أو إدارة المرور. اختر خدمة ووازن بين فائدتها والبيانات والمخاطر والفحص البشري الذي تحتاجه."),
      successCriteria: [L("Name a useful AI capability for one public service.", "سم قدرة مفيدة للذكاء الاصطناعي لخدمة عامة واحدة."), L("Choose relevant input data and an expected benefit for users.", "اختر بيانات إدخال ذات صلة وفائدة متوقعة للمستخدمين."), L("Identify one realistic risk or limitation.", "حدد خطرًا أو قيدًا واقعيًا واحدًا."), L("Keep a person responsible for checking an important outcome.", "أبقِ شخصًا مسؤولًا عن فحص نتيجة مهمة.")],
    },
    reflection: {
      transfer: L("Transfer: a clinic wants to reduce missed appointments. What could AI suggest, and what should staff still decide?", "نقل: تريد عيادة تقليل المواعيد الفائتة. ماذا يمكن أن يقترح الذكاء الاصطناعي، وما الذي ينبغي أن يظل الموظفون مسؤولين عن تقريره؟"),
      pairDiscussion: L("Compare a public-service benefit and a risk with a partner. Each learner then records an individual conclusion.", "قارن فائدة لخدمة عامة وخطرًا مع زميل. ثم يسجل كل متعلم خلاصة فردية."),
      individualPrompt: L("Which human check matters most for your chosen service, and why?", "أي فحص بشري هو الأهم لخدمتك المختارة، ولماذا؟"),
    },
    extraTaskCount: 1,
  },
  "ai-ethics": {
    challenge: {
      id: "school-program-ethics",
      title: L("Think as an Engineer: a fair academic-program decision", "فكر كمهندس: قرار عادل لبرنامج أكاديمي"),
      prompt: L("A school is considering AI to help select learners for a special academic program using grades, attendance, activities, and past performance. Decide what role AI may have, what data should be limited or excluded, and which safeguards keep the process fair, understandable, and accountable.", "تدرس مدرسة استخدام الذكاء الاصطناعي للمساعدة في اختيار المتعلمين لبرنامج أكاديمي خاص باستخدام الدرجات والحضور والأنشطة والأداء السابق. قرر ما الدور الذي قد يؤديه الذكاء الاصطناعي، وما البيانات التي ينبغي تقييدها أو استبعادها، وأي ضمانات تجعل العملية عادلة ومفهومة وخاضعة للمساءلة."),
      successCriteria: [L("Keep final selection accountable to people, not the model alone.", "أبقِ الاختيار النهائي خاضعًا لمسؤولية البشر لا النموذج وحده."), L("Identify a fairness or data-quality risk in historical records.", "حدد خطر إنصاف أو جودة بيانات في السجلات التاريخية."), L("Protect unnecessary personal data and explain the outcome clearly.", "احمِ البيانات الشخصية غير اللازمة واشرح النتيجة بوضوح."), L("Provide teacher review, an appeal path, and a way to monitor unfair outcomes.", "وفر مراجعة من المعلم ومسار اعتراض وطريقة لمراقبة النتائج غير العادلة.")],
    },
    reflection: {
      transfer: L("Transfer: a library wants to recommend books and send reminders. Which decision should remain human, what data is justified, and how would a learner challenge an unfair result?", "نقل: تريد مكتبة اقتراح كتب وإرسال تذكيرات. أي قرار ينبغي أن يبقى بشريًا، وما البيانات المبررة، وكيف يستطيع المتعلم الاعتراض على نتيجة غير عادلة؟"),
      pairDiscussion: L("Discuss one fairness safeguard and one explanation a learner would need. Then each learner records an individual conclusion.", "ناقش ضمان إنصاف واحدًا وشرحًا واحدًا يحتاجه المتعلم. ثم يسجل كل متعلم خلاصة فردية."),
      individualPrompt: L("Which safeguard would you protect most strongly, and why?", "أي ضمان ستحميه بأكبر قدر، ولماذا؟"),
    },
    unitReview: {
      title: L("Unit 1 review: information technology and AI", "مراجعة الوحدة الأولى: تكنولوجيا المعلومات والذكاء الاصطناعي"),
      introduction: L("Reconnect the four lessons: how technology changed access, how AI learns patterns, where it supports people, and how ethical safeguards keep people protected. Answer the retrieval, matching, ordering, classification, and scenario items using the reasoning you practised in the unit.", "أعد ربط الدروس الأربعة: كيف غيرت التقنية الوصول، وكيف يتعلم الذكاء الاصطناعي الأنماط، وأين يدعم الناس، وكيف تحمي الضمانات الأخلاقية الناس. أجب عن عناصر الاسترجاع والمطابقة والترتيب والتصنيف والسيناريو باستخدام التفكير الذي تدربت عليه في الوحدة."),
      questions: reviewQuestions,
    },
    extraTaskCount: 2,
  },
};
