import type { CurriculumLesson, CurriculumQuestion, UnitReviewQuestion } from "@/content/part1-curriculum";
import type { LocalizedText } from "@/lib/types";

const L = (en: string, ar: string): LocalizedText => ({ en, ar });
const opt = (en: string, ar: string): LocalizedText => L(en, ar);

type Fact = { term: LocalizedText; definition: LocalizedText; distractor: LocalizedText };
type Override = Pick<CurriculumLesson, "objectives" | "explanation" | "keyTerms" | "takeaway" | "summaryPoints" | "practice" | "quiz" | "activities" | "challenge" | "reflection" | "unitReview" | "extraTaskCount" | "sourcePages">;

function choice(id: string, prompt: LocalizedText, correct: LocalizedText, alternatives: LocalizedText[], explanation: LocalizedText): CurriculumQuestion {
  const choices = [correct, ...alternatives].map((text, index) => ({ id: String.fromCharCode(97 + index), text }));
  return { id, type: "mcq", prompt, choices, answer: "a", explanation };
}

function trueFalse(id: string, prompt: LocalizedText, truth: boolean, explanation: LocalizedText): CurriculumQuestion {
  return { id, type: "true-false", prompt, choices: [{ id: "true", text: L("True", "صحيح") }, { id: "false", text: L("False", "خطأ") }], answer: truth ? "true" : "false", explanation };
}

function cloze(id: string, prompt: LocalizedText, answer: string, explanation: LocalizedText): CurriculumQuestion {
  return { id, type: "cloze", prompt, answer, explanation };
}

function assessment(prefix: "practice" | "quiz", facts: Fact[]): CurriculumQuestion[] {
  const question = (index: number, fact: Fact) => choice(
    `${prefix}-${index + 1}`,
    prefix === "practice"
      ? L(`Which statement best describes ${fact.term.en}?`, `ما العبارة التي تصف ${fact.term.ar} بدقة؟`)
      : L(`A team is planning a website. Which statement about ${fact.term.en} is most accurate?`, `يخطط فريق لموقع ويب. ما العبارة الأدق عن ${fact.term.ar}؟`),
    fact.definition,
    [fact.distractor, L("It is only decoration and does not affect a user's decision.", "هو مجرد زينة ولا يؤثر في قرار المستخدم."), L("It removes the need to consider users or evidence.", "يلغي الحاجة إلى مراعاة المستخدمين أو الأدلة.")],
    L(`${fact.term.en}: ${fact.definition.en}`, `${fact.term.ar}: ${fact.definition.ar}`),
  );
  const items = Array.from({ length: prefix === "practice" ? 8 : 10 }, (_, index) => question(index, facts[index % facts.length]));
  items[prefix === "practice" ? 5 : 7] = trueFalse(
    `${prefix}-${prefix === "practice" ? 6 : 8}`,
    L(`A useful decision about ${facts[1].term.en} considers the purpose and the people who will use it.`, `القرار المفيد بشأن ${facts[1].term.ar} يراعي الغرض والأشخاص الذين سيستخدمونه.`),
    true,
    L("Good decisions are made in context, not by applying one rule everywhere.", "تُتخذ القرارات الجيدة في سياقها، لا بتطبيق قاعدة واحدة في كل مكان."),
  );
  items[prefix === "practice" ? 6 : 8] = trueFalse(
    `${prefix}-${prefix === "practice" ? 7 : 9}`,
    L(`One correct idea means a team never needs to test or improve its work.`, `وجود فكرة صحيحة يعني أن الفريق لا يحتاج أبدًا إلى اختبار عمله أو تحسينه.`),
    false,
    L("Users and evidence can reveal a need to improve a design.", "يمكن للمستخدمين والأدلة أن تكشف حاجة إلى تحسين التصميم."),
  );
  items[prefix === "practice" ? 7 : 9] = cloze(
    `${prefix}-${prefix === "practice" ? 8 : 10}`,
    L(`Complete the idea with the keyword “purpose”: choose a solution for the user and the _____.`, `أكمل الفكرة بكتابة الكلمة الإنجليزية “purpose”: اختر حلًا للمستخدم ولـ_____.`),
    "purpose",
    L("Purpose gives a design decision a clear reason.", "يمنح الغرض قرار التصميم سببًا واضحًا."),
  );
  return items;
}

const mediaFacts: Fact[] = [
  { term: opt("one-way communication", "الاتصال أحادي الاتجاه"), definition: opt("mainly sends information from a sender to receivers, as with television, radio, or a newspaper.", "ينقل المعلومات أساسًا من مرسل إلى متلقين، كما في التلفاز أو الإذاعة أو الصحيفة."), distractor: opt("requires every receiver to reply before it works.", "يتطلب أن يرد كل متلقٍ قبل أن يعمل.") },
  { term: opt("two-way communication", "الاتصال ثنائي الاتجاه"), definition: opt("lets people respond, post, share, or otherwise interact with information.", "يتيح للناس الرد أو النشر أو المشاركة أو التفاعل مع المعلومات."), distractor: opt("can only use sound and never text or images.", "لا يمكنه إلا استخدام الصوت ولا يستخدم النص أو الصور.") },
  { term: opt("website", "الموقع الإلكتروني"), definition: opt("can hold detailed, updateable information and can support interaction through features such as forms.", "يمكن أن يحتوي معلومات مفصلة قابلة للتحديث، ويدعم التفاعل عبر خصائص مثل النماذج."), distractor: opt("is always available without a device or connection.", "يتاح دائمًا دون جهاز أو اتصال.") },
  { term: opt("target audience", "الجمهور المستهدف"), definition: opt("is the group a message is intended to reach, whose access and needs affect the media choice.", "هو المجموعة المقصود وصول الرسالة إليها، ويؤثر وصولها واحتياجاتها في اختيار الوسيط."), distractor: opt("is the number of colours on a page.", "هو عدد الألوان في الصفحة.") },
  { term: opt("purpose", "الغرض"), definition: opt("is what communication is meant to achieve, such as reaching people, giving detail, or sending a reminder.", "هو ما يراد من الاتصال تحقيقه، مثل الوصول إلى الناس أو تقديم تفاصيل أو إرسال تذكير."), distractor: opt("means using the newest medium regardless of the message.", "يعني استخدام أحدث وسيط بصرف النظر عن الرسالة.") },
  { term: opt("media mix", "مزيج الوسائط"), definition: opt("uses more than one medium so that each can contribute a useful role.", "يستخدم أكثر من وسيط كي يسهم كل واحد بدور مفيد."), distractor: opt("repeats exactly the same message in every place without a reason.", "يكرر الرسالة نفسها في كل مكان بلا سبب.") },
];

const designFacts: Fact[] = [
  { term: opt("persona", "شخصية المستخدم"), definition: opt("is a concrete description of a typical user, including goals, context, and difficulties.", "هي وصف ملموس لمستخدم نموذجي، يشمل أهدافه وسياقه وصعوباته."), distractor: opt("is a final decorative image placed on a page.", "هي صورة زخرفية نهائية توضع في صفحة.") },
  { term: opt("wireframe", "المخطط الهيكلي"), definition: opt("is a rough page blueprint that shows information, position, and priority before final visual styling.", "هو مخطط أولي للصفحة يوضح المعلومات والموقع والأولوية قبل التنسيق البصري النهائي."), distractor: opt("is a list of the final colours and fonts only.", "هو قائمة بالألوان والخطوط النهائية فقط.") },
  { term: opt("contrast", "التباين"), definition: opt("makes an important item stand out so users can notice its priority.", "يجعل العنصر المهم بارزًا حتى يلاحظ المستخدم أولويته."), distractor: opt("makes every item look equally important.", "يجعل كل العناصر تبدو متساوية الأهمية.") },
  { term: opt("repetition", "التكرار"), definition: opt("reuses clear visual rules so users do not have to relearn each page.", "يعيد استخدام قواعد بصرية واضحة حتى لا يضطر المستخدم لتعلم كل صفحة من جديد."), distractor: opt("requires every heading to have a different style.", "يتطلب أن يكون لكل عنوان أسلوب مختلف.") },
  { term: opt("alignment", "المحاذاة"), definition: opt("lines up related text and elements to create visual order.", "يصطف النص والعناصر المرتبطة ليصنع نظامًا بصريًا."), distractor: opt("means placing items at random so the page feels busy.", "يعني وضع العناصر عشوائيًا كي تبدو الصفحة مزدحمة.") },
  { term: opt("proximity", "التقارب"), definition: opt("places related information close together and separates unrelated information.", "يضع المعلومات المرتبطة متقاربة ويفصل المعلومات غير المرتبطة."), distractor: opt("places a price far from the product it describes.", "يضع السعر بعيدًا عن المنتج الذي يصفه.") },
  { term: opt("user-centered design", "التصميم المتمحور حول المستخدم"), definition: opt("starts with what users need, their context, usability, and access rather than the creator's convenience.", "يبدأ بما يحتاجه المستخدمون وسياقهم وسهولة الاستخدام والوصول بدلًا من راحة المنشئ."), distractor: opt("starts by choosing decoration before learning who will use the page.", "يبدأ باختيار الزينة قبل معرفة من سيستخدم الصفحة.") },
];

const evaluationFacts: Fact[] = [
  { term: opt("qualitative evaluation", "التقييم النوعي"), definition: opt("explores why people struggle or make choices through observation, feedback, interviews, or expert review.", "يستكشف سبب صعوبة استخدام الناس أو اختياراتهم عبر الملاحظة والتغذية الراجعة والمقابلات أو مراجعة الخبراء."), distractor: opt("only counts visits and contains no observations.", "لا يعد إلا الزيارات ولا يحتوي ملاحظات.") },
  { term: opt("quantitative evaluation", "التقييم الكمي"), definition: opt("uses numbers to show how much is happening, such as views, exits, or completed actions.", "يستخدم الأرقام ليوضح مقدار ما يحدث، مثل المشاهدات أو الخروج أو الإجراءات المكتملة."), distractor: opt("automatically tells a team why every user acted that way.", "يخبر الفريق تلقائيًا بسبب تصرف كل مستخدم هكذا.") },
  { term: opt("page view (PV)", "مشاهدة الصفحة"), definition: opt("counts how many times a page was viewed.", "يعد عدد مرات مشاهدة الصفحة."), distractor: opt("counts only completed registrations.", "يعد التسجيلات المكتملة فقط.") },
  { term: opt("bounce rate", "معدل الارتداد"), definition: opt("is the proportion of visits that end after viewing only the first page.", "هو نسبة الزيارات التي تنتهي بعد مشاهدة الصفحة الأولى فقط."), distractor: opt("is the percentage of visitors who complete a target action.", "هو نسبة الزوار الذين يكملون إجراءً مستهدفًا.") },
  { term: opt("conversion rate (CVR)", "معدل التحويل"), definition: opt("is the proportion of visits that complete the target action, such as signing up or buying.", "هو نسبة الزيارات التي تكمل الإجراء المستهدف، مثل التسجيل أو الشراء."), distractor: opt("is the number of headings on a page.", "هو عدد العناوين في الصفحة.") },
  { term: opt("heuristic evaluation", "التقييم الاستدلالي"), definition: opt("is an expert review using practical usability rules such as consistency, error prevention, and clear system status.", "هو مراجعة خبير باستخدام قواعد عملية لسهولة الاستخدام مثل الاتساق ومنع الأخطاء ووضوح حالة النظام."), distractor: opt("asks a random visitor to write code for the site.", "يطلب من زائر عشوائي كتابة برنامج للموقع.") },
];

const improvementFacts: Fact[] = [
  { term: opt("PDCA", "دورة PDCA"), definition: opt("is a repeated improvement cycle: Plan, Do, Check, then Act.", "هي دورة تحسين متكررة: خطط ثم نفذ ثم تحقق ثم تصرف."), distractor: opt("means publish, decorate, copy, and abandon.", "تعني النشر ثم الزخرفة ثم النسخ ثم الترك.") },
  { term: opt("Plan", "خطط"), definition: opt("sets a goal and chooses one change to investigate or make.", "يحدد هدفًا ويختار تغييرًا واحدًا لفحصه أو تنفيذه."), distractor: opt("means deciding success before collecting any evidence.", "يعني تقرير النجاح قبل جمع أي دليل.") },
  { term: opt("Check", "تحقق"), definition: opt("compares the result with the goal using evidence; it is not merely checking code spelling.", "يقارن النتيجة بالهدف باستخدام الأدلة؛ وليس مجرد فحص كتابة الكود."), distractor: opt("means adding several unrelated changes at once.", "يعني إضافة عدة تغييرات غير مرتبطة دفعة واحدة.") },
  { term: opt("Design Thinking", "التفكير التصميمي"), definition: opt("uses Empathize, Define, Ideate, Prototype, and Test to address a user problem.", "يستخدم فهم المستخدم وتحديد المشكلة وتوليد الأفكار والنموذج الأولي والاختبار لمعالجة مشكلة مستخدم."), distractor: opt("chooses the first visual idea without listening to users.", "يختار أول فكرة بصرية دون الاستماع للمستخدمين.") },
  { term: opt("prototype", "نموذج أولي"), definition: opt("is a quick, testable version used to learn before a full final product is made.", "هو نسخة سريعة قابلة للاختبار تُستخدم للتعلم قبل صنع منتج نهائي كامل."), distractor: opt("must be identical to the finished site in every detail.", "يجب أن يطابق الموقع النهائي في كل التفاصيل.") },
  { term: opt("A/B testing", "اختبار A/B"), definition: opt("compares two versions while changing one element, then uses enough data to guide a decision.", "يقارن بين نسختين مع تغيير عنصر واحد، ثم يستخدم بيانات كافية لتوجيه القرار."), distractor: opt("changes every feature at once so results arrive faster.", "يغير كل الخصائص دفعة واحدة كي تظهر النتائج أسرع.") },
];

const finalReview: UnitReviewQuestion[] = [
  { id: "review-1", kind: "choice", prompt: L("A science fair needs complete details available at any time. Which medium best supports that role?", "يحتاج معرض العلوم إلى تفاصيل كاملة متاحة في أي وقت. أي وسيط يدعم هذا الدور؟"), choices: [opt("Website", "موقع إلكتروني"), opt("Radio only", "إذاعة فقط"), opt("Newspaper only", "صحيفة فقط"), opt("A single poster", "ملصق واحد")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("A website can keep detailed, updateable information available for people who visit it.", "يمكن للموقع الإلكتروني حفظ معلومات مفصلة قابلة للتحديث للناس الذين يزورونه.") },
  { id: "review-2", kind: "choice", prompt: L("Which medium is especially useful when people can share and respond quickly?", "أي وسيط مفيد خصوصًا عندما يستطيع الناس المشاركة والرد بسرعة؟"), choices: [opt("SNS", "شبكات التواصل الاجتماعي"), opt("Newspaper", "صحيفة"), opt("Radio announcement", "إعلان إذاعي"), opt("Television broadcast", "بث تلفزيوني")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("SNS supports rapid sharing and interaction.", "تدعم شبكات التواصل الاجتماعي الانتشار السريع والتفاعل.") },
  { id: "review-3", kind: "choice", prompt: L("A plan must include people with limited Internet access. What is a sensible extra choice?", "يجب أن تشمل الخطة أشخاصًا لديهم وصول محدود إلى الإنترنت. ما الاختيار الإضافي المناسب؟"), choices: [opt("Radio or a printed newspaper notice", "إذاعة أو إعلان صحفي مطبوع"), opt("A second website", "موقع إلكتروني ثانٍ"), opt("Only an online form", "نموذج إلكتروني فقط"), opt("Only a social-media post", "منشور تواصل اجتماعي فقط")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("A media mix can include an option that does not depend on Internet access.", "يمكن لمزيج الوسائط أن يضم خيارًا لا يعتمد على الاتصال بالإنترنت.") },
  { id: "review-4", kind: "choice", prompt: L("What is a persona mainly for?", "ما الغرض الأساسي من شخصية المستخدم؟"), choices: [opt("Clarifying a typical user's goals, context, and difficulties", "توضيح أهداف المستخدم النموذجي وسياقه وصعوباته"), opt("Choosing final page colours", "اختيار ألوان الصفحة النهائية"), opt("Counting page views", "عد مشاهدات الصفحة"), opt("Writing a news article", "كتابة مقال إخباري")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("A persona keeps the design focused on real user needs.", "تحافظ شخصية المستخدم على تركيز التصميم في احتياجات المستخدم الحقيقية.") },
  { id: "review-5", kind: "choice", prompt: L("Which description fits a wireframe?", "أي وصف يناسب المخطط الهيكلي؟"), choices: [opt("A rough layout blueprint that shows information priority", "مخطط أولي للتخطيط يوضح أولوية المعلومات"), opt("A finished visual design", "تصميم بصري نهائي"), opt("A list of web metrics", "قائمة بمقاييس الويب"), opt("A test of two button labels", "اختبار لعبارتي زر")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("Wireframes decide what appears where before final decoration.", "تحدد المخططات الهيكلية ما يظهر وأين قبل الزينة النهائية.") },
  { id: "review-6", kind: "choice", prompt: L("A primary action button is hard to notice. Which CRAP principle needs attention?", "زر الإجراء الرئيسي صعب الملاحظة. أي مبدأ من مبادئ CRAP يحتاج اهتمامًا؟"), choices: [opt("Contrast", "التباين"), opt("Repetition", "التكرار"), opt("Alignment", "المحاذاة"), opt("Proximity", "التقارب")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("Contrast makes a priority action stand out.", "يجعل التباين الإجراء ذي الأولوية بارزًا.") },
  { id: "review-7", kind: "choice", prompt: L("Keeping a product name, price, and buy button close together uses which principle?", "إبقاء اسم المنتج وسعره وزر الشراء متقاربة يستخدم أي مبدأ؟"), choices: [opt("Proximity", "التقارب"), opt("Contrast", "التباين"), opt("PV", "مشاهدة الصفحة"), opt("A/B testing", "اختبار A/B")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("Proximity groups related information.", "يجمع التقارب المعلومات المرتبطة.") },
  { id: "review-8", kind: "choice", prompt: L("What does quantitative evaluation primarily answer?", "ما الذي يجيب عنه التقييم الكمي أساسًا؟"), choices: [opt("How much is happening numerically", "كم يحدث بالأرقام"), opt("Why one individual feels frustrated", "لماذا يشعر فرد بالإحباط"), opt("Which font is most beautiful", "أي خط أجمل"), opt("Who designed the logo", "من صمم الشعار")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("Quantitative evidence shows numerical patterns.", "تظهر الأدلة الكمية أنماطًا رقمية.") },
  { id: "review-9", kind: "choice", prompt: L("A page receives 100 visits; 40 end after the first page. What is its bounce rate?", "تتلقى الصفحة 100 زيارة؛ وتنتهي 40 منها بعد الصفحة الأولى. ما معدل الارتداد؟"), choices: [opt("40%", "40٪"), opt("4%", "4٪"), opt("60%", "60٪"), opt("100%", "100٪")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("40 of 100 first-page exits is 40%.", "40 خروجًا من أصل 100 بعد الصفحة الأولى يساوي 40٪.") },
  { id: "review-10", kind: "choice", prompt: L("A sign-up page has 200 visits and 10 completed registrations. What is its CVR?", "لدى صفحة التسجيل 200 زيارة و10 تسجيلات مكتملة. ما معدل التحويل؟"), choices: [opt("5%", "5٪"), opt("10%", "10٪"), opt("20%", "20٪"), opt("50%", "50٪")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("10 completed actions out of 200 visits is 5%.", "10 إجراءات مكتملة من أصل 200 زيارة تساوي 5٪.") },
  { id: "review-11", kind: "choice", prompt: L("Many visitors arrive but few register. What can analytics show, and what can it not show alone?", "يصل زوار كثيرون لكن قليلًا منهم يسجلون. ماذا تظهر التحليلات وما الذي لا تشرحه وحدها؟"), choices: [opt("It can show low conversion but needs qualitative evidence to explain why", "يمكنها إظهار انخفاض التحويل لكنها تحتاج دليلًا نوعيًا لشرح السبب"), opt("It proves the button colour is wrong", "تثبت أن لون الزر خاطئ"), opt("It proves every visitor disliked the page", "تثبت أن كل زائر لم يعجبه الموقع"), opt("It removes the need to test with users", "تلغي الحاجة إلى اختبار المستخدمين")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("Numbers identify a pattern; observation or interviews can investigate the reason.", "تحدد الأرقام نمطًا؛ ويمكن للملاحظة أو المقابلات فحص السبب.") },
  { id: "review-12", kind: "choice", prompt: L("An expert notices that the same action has different labels on two pages. Which heuristic is weak?", "لاحظ خبير أن الإجراء نفسه له تسميتان مختلفتان في صفحتين. أي قاعدة إرشادية ضعيفة؟"), choices: [opt("Consistency", "الاتساق"), opt("Page views", "مشاهدات الصفحة"), opt("Proximity", "التقارب"), opt("Prototype", "النموذج الأولي")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("Consistent labels and behaviour reduce relearning.", "تقلل التسميات والسلوكيات المتسقة من إعادة التعلم.") },
  { id: "review-13", kind: "choice", prompt: L("What is the correct PDCA sequence?", "ما تسلسل PDCA الصحيح؟"), choices: [opt("Plan → Do → Check → Act", "خطط ← نفذ ← تحقق ← تصرف"), opt("Do → Plan → Act → Check", "نفذ ← خطط ← تصرف ← تحقق"), opt("Check → Act → Plan → Do", "تحقق ← تصرف ← خطط ← نفذ"), opt("Plan → Check → Do → Act", "خطط ← تحقق ← نفذ ← تصرف")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("PDCA uses evidence after a planned action, then decides the next move.", "تستخدم PDCA الأدلة بعد فعل مخطط ثم تقرر الخطوة التالية.") },
  { id: "review-14", kind: "choice", prompt: L("Which Design Thinking stage turns a user observation into a clear problem statement?", "أي مرحلة من التفكير التصميمي تحول ملاحظة المستخدم إلى تعريف واضح للمشكلة؟"), choices: [opt("Define", "تحديد المشكلة"), opt("Ideate", "توليد الأفكار"), opt("Prototype", "النموذج الأولي"), opt("Test", "اختبار")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("Define clarifies the user problem before solutions are chosen.", "توضح مرحلة تحديد المشكلة مشكلة المستخدم قبل اختيار الحلول.") },
  { id: "review-15", kind: "choice", prompt: L("Why should an A/B test change only one element at a time?", "لماذا ينبغي لاختبار A/B أن يغير عنصرًا واحدًا فقط في كل مرة؟"), choices: [opt("So the team can link a difference to that change", "ليتمكن الفريق من ربط الاختلاف بذلك التغيير"), opt("So both versions look unrelated", "كي تبدو النسختان غير مرتبطتين"), opt("So no users are needed", "كي لا نحتاج مستخدمين"), opt("So data never needs reviewing", "كي لا تحتاج البيانات إلى مراجعة")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("Several simultaneous changes hide which one affected the result.", "تخفي التغييرات المتعددة المتزامنة أيها أثّر في النتيجة.") },
  { id: "review-16", kind: "choice", prompt: L("Which action best models continuous improvement?", "أي إجراء يجسد التحسين المستمر أفضل؟"), choices: [opt("Measure a change, learn from it, and begin another focused cycle", "قياس تغيير والتعلم منه وبدء دورة مركزة أخرى"), opt("Launch once and never collect feedback", "النشر مرة واحدة وعدم جمع تغذية راجعة"), opt("Redesign everything whenever one visitor leaves", "إعادة تصميم كل شيء كلما غادر زائر واحد"), opt("Choose changes without a goal", "اختيار تغييرات بلا هدف")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("Iteration makes focused changes and learns from evidence.", "يجري التحسين التكراري تغييرات مركزة ويتعلم من الأدلة.") },
  { id: "review-17", kind: "matching", prompt: L("Match each communication purpose to its most suitable role.", "طابق كل غرض اتصالي مع دوره الأنسب."), pairs: [{ id: "detail", left: opt("Keep full event details available", "إبقاء تفاصيل الفعالية الكاملة متاحة"), right: opt("Website", "موقع إلكتروني") }, { id: "spread", left: opt("Encourage quick voluntary sharing", "تشجيع المشاركة السريعة الطوعية"), right: opt("SNS", "شبكات التواصل الاجتماعي") }, { id: "direct", left: opt("Send a reminder to selected families", "إرسال تذكير إلى أسر محددة"), right: opt("Email", "البريد الإلكتروني") }], explanation: L("A media plan gives each channel a purpose rather than treating channels as identical.", "تعطي خطة الوسائط كل قناة غرضًا بدل معاملتها كأنها متطابقة.") },
  { id: "review-18", kind: "matching", prompt: L("Match the evidence or issue to its idea.", "طابق الدليل أو المشكلة مع فكرته."), pairs: [{ id: "number", left: opt("42 of 100 visits leave after the first page", "42 زيارة من أصل 100 تنتهي بعد الصفحة الأولى"), right: opt("Bounce rate", "معدل الارتداد") }, { id: "feedback", left: opt("Three learners say they cannot find the register button", "يقول ثلاثة طلاب إنهم لا يجدون زر التسجيل"), right: opt("Qualitative evidence", "دليل نوعي") }, { id: "status", left: opt("A form gives no message after submission", "لا يقدم النموذج رسالة بعد الإرسال"), right: opt("Visibility of system status", "وضوح حالة النظام") }], explanation: L("Numbers, user feedback, and heuristic issues answer different questions.", "تجيب الأرقام وتغذية المستخدمين ومشكلات القواعد الإرشادية عن أسئلة مختلفة.") },
  { id: "review-19", kind: "ordering", prompt: L("Put the user-focused page-planning path in order.", "رتب مسار تخطيط الصفحة المتمحور حول المستخدم."), order: [{ id: "persona", text: opt("Understand the user with a persona", "افهم المستخدم بشخصية مستخدم") }, { id: "wireframe", text: opt("Plan information priority with a wireframe", "خطط أولوية المعلومات بمخطط هيكلي") }, { id: "clear", text: opt("Make relationships clear with CRAP", "اجعل العلاقات واضحة بمبادئ CRAP") }, { id: "use", text: opt("Let people use the page", "دع الناس يستخدمون الصفحة") }], explanation: L("Learn who the page serves before deciding layout and clarity.", "تعرف أولًا من تخدمه الصفحة قبل تقرير التخطيط والوضوح.") },
  { id: "review-20", kind: "ordering", prompt: L("Order the Design Thinking stages.", "رتب مراحل التفكير التصميمي."), order: [{ id: "empathize", text: opt("Empathize", "فهم المستخدم") }, { id: "define", text: opt("Define", "تحديد المشكلة") }, { id: "ideate", text: opt("Ideate", "توليد الأفكار") }, { id: "prototype", text: opt("Prototype", "نموذج أولي") }, { id: "test", text: opt("Test", "اختبار") }], explanation: L("The stages help a team learn from users, make a testable idea, and learn again.", "تساعد المراحل الفريق على التعلم من المستخدمين وصنع فكرة قابلة للاختبار ثم التعلم مجددًا.") },
  { id: "review-21", kind: "choice", prompt: L("Which statement distinguishes usability from accessibility?", "أي عبارة تميز بين سهولة الاستخدام وإمكانية الوصول؟"), choices: [opt("Usability concerns ease and efficiency; accessibility considers whether a wide range of people can use the site", "تتعلق سهولة الاستخدام بالسهولة والكفاءة؛ وتنظر إمكانية الوصول إلى قدرة نطاق واسع من الناس على استخدام الموقع"), opt("They both mean choosing colours", "كلاهما يعني اختيار الألوان"), opt("Accessibility is only for desktop users", "إمكانية الوصول للحواسيب فقط"), opt("Usability means adding more content", "تعني سهولة الاستخدام إضافة محتوى أكثر")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("A user-centered page considers both efficient use and access for different people.", "تراعي الصفحة المتمحورة حول المستخدم الاستخدام الكفء والوصول لأشخاص مختلفين.") },
  { id: "review-22", kind: "choice", prompt: L("Version A gets 32 registrations from 100 visitors and Version B gets 47 from 100, with only button text changed. What is the sound next decision?", "تحصل النسخة A على 32 تسجيلًا من 100 زائر والنسخة B على 47 من 100 زائر، ولم يتغير سوى نص الزر. ما القرار التالي السليم؟"), choices: [opt("Use the stronger B result as evidence, then continue checking with sufficient data", "استخدم نتيجة B الأقوى كدليل، ثم واصل التحقق ببيانات كافية"), opt("Assume every future change will succeed", "افترض أن كل تغيير مستقبلي سينجح"), opt("Change the whole page before looking again", "غير الصفحة كلها قبل النظر مرة أخرى"), opt("Ignore the results because text does not matter", "تجاهل النتائج لأن النص لا يهم")].map((text, i) => ({ id: "abcd"[i], text })), answer: "a", explanation: L("The controlled comparison gives evidence about the one changed element; improvement continues.", "تقدم المقارنة المضبوطة دليلًا عن العنصر الوحيد المتغير؛ ويستمر التحسين.") },
];

export const unit4LessonOverrides: Record<string, Override> = {
  "media-types-and-characteristics": {
    sourcePages: "75–80",
    objectives: [L("Compare media by communication direction, purpose, and audience.", "قارن الوسائط بحسب اتجاه الاتصال والغرض والجمهور."), L("Choose and justify a useful mix of media for a real situation.", "اختر وبرر مزيجًا مفيدًا من الوسائط لموقف واقعي.")],
    explanation: [
      { title: L("Start with the decision, not the channel", "ابدأ بالقرار لا بالقناة"), body: L("A school science fair needs attention, accurate details, and reminders. Television, radio, newspapers, websites, social-networking services (SNS), and email do not serve those jobs in the same way. Instead of asking which medium is best in general, ask what the message must do and who needs to receive it.\n\nA useful choice considers purpose, audience access, the type of information, reach, and whether people need to respond. This makes media choice a reasoned design decision rather than a habit.", "يحتاج معرض العلوم في المدرسة إلى جذب الانتباه وتفاصيل دقيقة وتذكيرات. لا يؤدي التلفاز والإذاعة والصحف والمواقع وخدمات الشبكات الاجتماعية والبريد الإلكتروني هذه الوظائف بالطريقة نفسها. بدل أن نسأل أي وسيط هو الأفضل عمومًا، نسأل: ماذا يجب أن تفعل الرسالة؟ ومن الذي يحتاج إلى تلقيها؟\n\nيراعي الاختيار المفيد الغرض ووصول الجمهور ونوع المعلومات والانتشار والحاجة إلى رد الناس. وهكذا يصبح اختيار الوسيط قرارًا تصميميًا مبررًا لا مجرد عادة."), visual: "media-map" },
      { title: L("Direction changes the conversation", "اتجاه الاتصال يغير المحادثة"), body: L("Television, radio, and newspapers mainly move information from a sender to receivers: they are one-way media. An SNS lets people reply, post, and share, so it supports two-way communication. A website commonly presents information, but a form, comment area, or booking request can also let a visitor respond.\n\nThe labels describe the main communication pattern, not a rule that one tool can never be used differently. The important question is whether the planned audience needs a path back to the sender.", "ينقل التلفاز والإذاعة والصحف المعلومات أساسًا من مرسل إلى متلقين، لذلك هي وسائط أحادية الاتجاه. تتيح خدمات الشبكات الاجتماعية للناس الرد والنشر والمشاركة، لذا تدعم اتصالًا ثنائي الاتجاه. ويعرض الموقع الإلكتروني المعلومات غالبًا، لكن نموذجًا أو منطقة تعليق أو طلب حجز قد يتيح للزائر الرد أيضًا.\n\nتصف التسميات نمط الاتصال الأساسي، وليست قاعدة تمنع استخدام الأداة بشكل مختلف. والسؤال المهم هو: هل يحتاج الجمهور المخطط له إلى طريق للرد على المرسل؟"), visual: "media-compare" },
      { title: L("Why a website is useful—and limited", "لماذا يفيد الموقع الإلكتروني وما حدوده"), body: L("A website can combine text, images, sound, and video in one place. It can be updated, can hold detail, and can be reached from many locations through a browser. These strengths make it a useful home for information that should remain available.\n\nIt also has constraints. A visitor normally needs a device and an Internet connection, must actively come to the site, and may have a slow connection or a small screen. A fair media plan does not assume every audience member has the same access.", "يمكن للموقع الإلكتروني جمع النصوص والصور والصوت والفيديو في مكان واحد. ويمكن تحديثه وحفظ التفاصيل والوصول إليه من أماكن كثيرة عبر المتصفح. وتجعل هذه النقاط منه موطنًا مفيدًا للمعلومات التي ينبغي أن تبقى متاحة.\n\nوله قيود أيضًا. يحتاج الزائر عادة إلى جهاز واتصال بالإنترنت، ويجب أن يقصد الموقع بنفسه، وقد يملك اتصالًا بطيئًا أو شاشة صغيرة. لا تفترض خطة وسائط عادلة أن كل فرد من الجمهور يملك الوصول نفسه."), visual: "website-balance" },
      { title: L("One message can have several roles", "يمكن للرسالة أن تؤدي أدوارًا متعددة"), body: L("Communication often works best as a media mix. An SNS post can attract attention and encourage sharing; a website can provide complete dates, directions, and answers; an email can send a direct reminder to a selected group. Each channel has a reason in the plan.\n\nCombining media is not about copying everything everywhere. It is about matching a channel to a purpose while checking which groups might still be missed.", "غالبًا ما يعمل الاتصال أفضل بوصفه مزيجًا من الوسائط. يمكن لمنشور على شبكة اجتماعية جذب الانتباه وتشجيع المشاركة؛ ويقدم الموقع التواريخ والاتجاهات والإجابات الكاملة؛ ويرسل البريد الإلكتروني تذكيرًا مباشرًا إلى مجموعة محددة. لكل قناة سبب في الخطة.\n\nلا يعني الجمع بين الوسائط نسخ كل شيء في كل مكان، بل يعني مطابقة القناة بالغرض مع التحقق من المجموعات التي قد لا تزال غير مشمولة."), visual: "media-plan" },
    ],
    keyTerms: mediaFacts.map((fact) => ({ term: fact.term, definition: fact.definition })),
    takeaway: L("Choose media from purpose + audience, then combine roles when that improves reach, detail, or interaction.", "اختر الوسيط من الغرض + الجمهور، ثم اجمع الأدوار عندما يحسن ذلك الوصول أو التفاصيل أو التفاعل."),
    summaryPoints: [L("TV, radio, and newspapers are mainly one-way; SNS supports two-way communication.", "التلفاز والإذاعة والصحف أحادية الاتجاه أساسًا؛ وتدعم الشبكات الاجتماعية الاتصال الثنائي."), L("A website is strong for detailed, updateable information but depends on access and a visitor choosing to open it.", "الموقع قوي للمعلومات المفصلة القابلة للتحديث لكنه يعتمد على الوصول واختيار الزائر فتحه."), L("Audience access matters as much as reach.", "وصول الجمهور مهم بقدر أهمية الانتشار."), L("Purpose gives each medium a job in the plan.", "يعطي الغرض كل وسيط وظيفة في الخطة."), L("A media mix can connect attention, detail, and direct reminders.", "يمكن لمزيج الوسائط وصل الانتباه بالتفاصيل والتذكيرات المباشرة.")],
    practice: assessment("practice", mediaFacts), quiz: assessment("quiz", mediaFacts),
    activities: [
      { id: "media-direction-sort", title: L("Sort the communication pattern", "صنف نمط الاتصال"), instruction: L("Classify each medium as mainly one-way, two-way, or able to support both. Use the selectable list; no dragging is required.", "صنف كل وسيط على أنه أحادي الاتجاه أساسًا أو ثنائي الاتجاه أو قادر على دعم الاثنين. استخدم القائمة القابلة للاختيار؛ لا يلزم السحب.") },
      { id: "website-balance", title: L("Balance a website", "وازن مزايا الموقع وقيوده"), instruction: L("Decide whether each statement is a website strength or constraint, then check the balance.", "حدد هل كل عبارة ميزة للموقع أم قيد، ثم تحقق من التوازن.") },
      { id: "media-purpose-match", title: L("Match purpose to role", "طابق الغرض بالدور"), instruction: L("Give each communication goal the medium role that fits it best in this scenario.", "أعط كل هدف اتصالي دور الوسيط الأنسب له في هذا الموقف.") },
      { id: "media-plan-builder", title: L("Build a media plan", "ابنِ خطة وسائط"), instruction: L("Choose a channel for attention, complete details, and a direct reminder.", "اختر قناة لجذب الانتباه وللتفاصيل الكاملة ولتذكير مباشر.") },
    ],
    challenge: { id: "community-media-plan", title: L("Free evening classes: reach the whole community", "الدروس المسائية المجانية: الوصول إلى المجتمع كله"), prompt: L("A community centre offers free evening classes. Its audience includes students, parents, older residents, and people with limited Internet access. Build a plan using at least two media and explain one group that could still be missed.", "يقدم مركز مجتمعي دروسًا مسائية مجانية. يشمل جمهوره الطلاب وأولياء الأمور وكبار السن وأشخاصًا لديهم وصول محدود إلى الإنترنت. ابنِ خطة تستخدم وسيطين على الأقل واشرح مجموعة قد تظل غير مشمولة."), successCriteria: [L("Choose at least two media with distinct purposes.", "اختر وسيطين على الأقل لهما غرضان مختلفان."), L("Connect a medium to a named audience.", "اربط وسيطًا بجمهور مسمى."), L("Identify a remaining access gap honestly.", "حدد فجوة وصول متبقية بصدق.") ] },
    reflection: { transfer: L("A local library wants more families at a reading event. Which media roles would you combine, and why?", "تريد مكتبة محلية حضور أسر أكثر لفعالية قراءة. ما أدوار الوسائط التي ستجمعها ولماذا؟"), pairDiscussion: L("Compare two plans: which audience is well served, and who is still at risk of being missed?", "قارن خطتين: أي جمهور مخدوم جيدًا، ومن لا يزال معرضًا لعدم الوصول؟"), individualPrompt: L("Record one evidence-based media choice you would make.", "سجل اختيارًا واحدًا لوسيط مبنيًا على دليل.") },
    extraTaskCount: 5,
  },
  "information-design-and-ux": {
    sourcePages: "81–87",
    objectives: [L("Use personas and wireframes to plan information around user needs.", "استخدم شخصيات المستخدم والمخططات الهيكلية لتخطيط المعلومات حول احتياجات المستخدم."), L("Apply CRAP and user-centered design to improve usability and access.", "طبق مبادئ CRAP والتصميم المتمحور حول المستخدم لتحسين سهولة الاستخدام والوصول.")],
    explanation: [
      { title: L("Meet the person before designing the page", "تعرف إلى الشخص قبل تصميم الصفحة"), body: L("A persona is a concrete representation of a typical target user. It gives a name or description, goals, situation, device, and challenges. For example, a parent checking a clinic website on a phone during a short break may need opening hours immediately and may not have time to search through a long page.\n\nA persona is not decoration or a guess about popularity. It helps a team ask who is using the page, what they need, and what could make the task difficult.", "شخصية المستخدم تمثيل ملموس لمستخدم نموذجي مستهدف. تصف الاسم أو الفئة والأهداف والموقف والجهاز والتحديات. فمثلًا قد يحتاج ولي أمر يفحص موقع عيادة من هاتفه خلال استراحة قصيرة إلى ساعات العمل فورًا، وقد لا يملك وقتًا للبحث في صفحة طويلة.\n\nليست شخصية المستخدم زينة أو تخمينًا للشعبية. إنها تساعد الفريق على سؤال: من يستخدم الصفحة؟ وماذا يحتاج؟ وما الذي قد يصعب المهمة؟"), visual: "persona" },
      { title: L("Plan before decoration", "خطط قبل الزينة"), body: L("A wireframe is a rough blueprint for a page. It decides which information appears, where it appears, and what should be noticed first. Like a floor plan before furniture and paint, it is about structure and priority rather than final colours, logos, or decorative fonts.\n\nA clinic homepage might place an emergency contact and appointment action where a hurried visitor can find them, then group opening hours, services, and directions clearly. Placement follows user needs, not the designer's taste.", "المخطط الهيكلي مخطط أولي للصفحة. يقرر ما المعلومات التي تظهر وأين تظهر وما الذي يجب ملاحظته أولًا. ومثل مخطط الأرضية قبل الأثاث والطلاء، فهو يتعلق بالبنية والأولوية لا بالألوان النهائية أو الشعارات أو الخطوط الزخرفية.\n\nقد تضع الصفحة الرئيسية لعيادة اتصال الطوارئ وإجراء الحجز في مكان يسهل أن يجده الزائر المستعجل، ثم تجمع ساعات العمل والخدمات والاتجاهات بوضوح. ويتبع الموضع احتياجات المستخدم لا ذوق المصمم."), visual: "wireframe" },
      { title: L("Four ways to make a page clearer", "أربع طرق لجعل الصفحة أوضح"), body: L("CRAP is a memory aid for four information-design principles. Contrast makes a priority action or heading noticeable. Repetition uses the same visual rule for similar actions. Alignment lets text and controls follow a clear edge or line. Proximity keeps related information together and leaves space between unrelated groups.\n\nThese principles do not demand one fixed style. They help a visitor see what belongs together, what matters first, and where to look next.", "CRAP وسيلة تذكر لأربعة مبادئ في تصميم المعلومات. يجعل التباين الإجراء أو العنوان ذي الأولوية ملحوظًا. ويستخدم التكرار القاعدة البصرية نفسها للإجراءات المتشابهة. وتجعل المحاذاة النصوص وعناصر التحكم تتبع حافة أو خطًا واضحًا. ويبقي التقارب المعلومات المرتبطة معًا ويترك مساحة بين المجموعات غير المرتبطة.\n\nلا تفرض هذه المبادئ أسلوبًا ثابتًا واحدًا، بل تساعد الزائر على رؤية ما ينتمي معًا وما المهم أولًا وأين ينظر بعد ذلك."), visual: "crap" },
      { title: L("Design from the user's perspective", "صمم من منظور المستخدم"), body: L("User-Centered Design (UCD) means making decisions from the user's perspective instead of the creator's convenience. It connects a persona to practical choices about information priority, labels, actions, usability, and accessibility.\n\nUsability asks whether a task is easy and efficient. Accessibility asks whether a wide range of people, including people with impairments, can use the site. A good design considers both: clear text, understandable navigation, visible actions, and a layout that works in the context where people use it.", "يعني التصميم المتمحور حول المستخدم اتخاذ القرارات من منظور المستخدم بدلًا من راحة المنشئ. وهو يربط شخصية المستخدم بخيارات عملية حول أولوية المعلومات والتسميات والإجراءات وسهولة الاستخدام وإمكانية الوصول.\n\nتسأل سهولة الاستخدام هل المهمة سهلة وفعالة. وتسأل إمكانية الوصول هل يستطيع نطاق واسع من الناس، ومنهم أشخاص لديهم إعاقات، استخدام الموقع. ويراعي التصميم الجيد الاثنين: نصًا واضحًا وتنقلًا مفهومًا وإجراءات مرئية وتخطيطًا يعمل في السياق الذي يستخدم فيه الناس الموقع."), visual: "user-flow" },
    ],
    keyTerms: designFacts.map((fact) => ({ term: fact.term, definition: fact.definition })),
    takeaway: L("Good page design begins with user needs: persona → wireframe → clear relationships through CRAP → usable, accessible experience.", "يبدأ تصميم الصفحة الجيد باحتياجات المستخدم: شخصية مستخدم ← مخطط هيكلي ← علاقات واضحة عبر CRAP ← تجربة سهلة ومتاحة."),
    summaryPoints: [L("A persona makes the target user's goal, context, and difficulty concrete.", "تجعل شخصية المستخدم هدف المستخدم المستهدف وسياقه وصعوبته ملموسة."), L("A wireframe plans hierarchy before final visual decoration.", "يخطط المخطط الهيكلي للتسلسل قبل الزينة البصرية النهائية."), L("Contrast, repetition, alignment, and proximity improve clarity.", "يحسن التباين والتكرار والمحاذاة والتقارب الوضوح."), L("UCD asks what users need before choosing the solution.", "يسأل التصميم المتمحور حول المستخدم عما يحتاجه المستخدمون قبل اختيار الحل."), L("Usability and accessibility are related but not identical.", "ترتبط سهولة الاستخدام وإمكانية الوصول لكنهما ليسا الشيء نفسه.")],
    practice: assessment("practice", designFacts), quiz: assessment("quiz", designFacts),
    activities: [
      { id: "persona-builder", title: L("Build a persona", "ابنِ شخصية مستخدم"), instruction: L("Choose a user's group, goal, device, and challenge. See how priorities change.", "اختر فئة المستخدم وهدفه وجهازه وتحديه. شاهد كيف تتغير الأولويات.") },
      { id: "wireframe-priority", title: L("Prioritize a clinic homepage", "رتب أولوية صفحة عيادة"), instruction: L("Use the Move up and Move down controls to order key clinic blocks for a hurried mobile visitor.", "استخدم زري التحريك للأعلى والأسفل لترتيب عناصر العيادة لزائر مستعجل على الهاتف.") },
      { id: "crap-fixer", title: L("Fix the messy page", "أصلح الصفحة المربكة"), instruction: L("Identify the CRAP principle that fixes each visible problem.", "حدد مبدأ CRAP الذي يصلح كل مشكلة ظاهرة.") },
    ],
    challenge: { id: "results-page-design", title: L("A results page that works for families", "صفحة نتائج تعمل للأسر"), prompt: L("A school is redesigning its student-results page for students, parents, older parents, and mobile users. Choose a persona, set the first information priority, make a small wireframe decision, and explain how one CRAP choice improves usability or accessibility.", "تعيد مدرسة تصميم صفحة نتائج الطلاب للطلاب وأولياء الأمور الأكبر سنًا ومستخدمي الهاتف. اختر شخصية مستخدم وحدد أولوية المعلومات الأولى واتخذ قرارًا صغيرًا للمخطط الهيكلي واشرح كيف يحسن اختيار واحد من CRAP سهولة الاستخدام أو الوصول."), successCriteria: [L("Name a user and need.", "سم مستخدمًا واحتياجًا."), L("Give the most important information a high priority.", "أعط المعلومات الأهم أولوية عالية."), L("Connect a CRAP decision to clearer use or access.", "اربط قرارًا من CRAP باستخدام أو وصول أوضح.") ] },
    reflection: { transfer: L("Think of a school page you have used. What would a persona reveal before anyone redesigned it?", "فكر في صفحة مدرسية استخدمتها. ماذا ستكشف شخصية المستخدم قبل أن يعيد أحد تصميمها؟"), pairDiscussion: L("Compare priorities for a hurried phone user and a user who needs larger, clearer text.", "قارن الأولويات لمستخدم مستعجل على الهاتف ولمستخدم يحتاج نصًا أكبر وأوضح."), individualPrompt: L("Write one design choice and the user need behind it.", "اكتب قرارًا تصميميًا واحدًا واحتياج المستخدم وراءه.") },
    extraTaskCount: 4,
  },
  "website-evaluation": {
    sourcePages: "88–94",
    objectives: [L("Distinguish qualitative and quantitative evidence for website evaluation.", "ميز بين الأدلة النوعية والكمية لتقييم المواقع."), L("Use simple metrics and heuristic checks to identify a focused improvement need.", "استخدم مقاييس بسيطة وفحوصًا إرشادية لتحديد حاجة مركزة للتحسين.")],
    explanation: [
      { title: L("Numbers show patterns; people help explain them", "تظهر الأرقام الأنماط ويساعد الناس في تفسيرها"), body: L("Quantitative evaluation uses numbers to ask how much is happening: how often a page is viewed, how many visits end quickly, or how many people complete a target action. Qualitative evaluation asks why: it observes users, gathers feedback in interviews, or uses expert review to identify difficulty.\n\nNeither kind of evidence replaces the other. A low registration rate is a useful signal, but it does not by itself prove why people stopped. A short usability observation can make the next investigation much more focused.", "يستخدم التقييم الكمي الأرقام ليسأل عن مقدار ما يحدث: كم مرة تُشاهد صفحة، أو كم زيارة تنتهي سريعًا، أو كم شخصًا يكمل إجراءً مستهدفًا. ويسأل التقييم النوعي لماذا: يلاحظ المستخدمين ويجمع التغذية الراجعة في المقابلات أو يستخدم مراجعة الخبراء لتحديد الصعوبة.\n\nلا يحل نوع من الأدلة محل الآخر. يمثل معدل التسجيل المنخفض إشارة مفيدة، لكنه لا يثبت وحده سبب توقف الناس. وقد تجعل ملاحظة قصيرة لاختبار سهولة الاستخدام التحقيق التالي أكثر تركيزًا."), visual: "evidence-split" },
      { title: L("Read three simple website measures", "اقرأ ثلاثة مقاييس ويب بسيطة"), body: L("A page view (PV) counts a page being viewed. Bounce rate is the proportion of visits that end after the first page: if 40 of 100 visits leave immediately, the bounce rate is 40%. Conversion rate (CVR) is the proportion that completes a target action: if 50 of 1,000 visits register, the CVR is 5%.\n\nThese measures should be read in context. High PV with low CVR can mean many people arrive but few complete the goal. The numbers identify the pattern; they do not automatically explain the reason.", "تعد مشاهدة الصفحة عدد مرات مشاهدة الصفحة. ومعدل الارتداد هو نسبة الزيارات التي تنتهي بعد الصفحة الأولى: فإذا غادرت 40 زيارة من أصل 100 فورًا، كان معدل الارتداد 40٪. ومعدل التحويل هو نسبة من يكمل الإجراء المستهدف: فإذا سجل 50 من أصل 1000 زيارة، كان معدل التحويل 5٪.\n\nينبغي قراءة هذه المقاييس في سياقها. فقد تعني مشاهدات كثيرة مع تحويل منخفض أن كثيرًا من الناس يصلون لكن القليل يكمل الهدف. تحدد الأرقام النمط ولا تشرح السبب تلقائيًا."), visual: "metrics" },
      { title: L("Check the interface with practical rules", "افحص الواجهة بقواعد عملية"), body: L("Heuristic evaluation is an expert review of an interface using practical usability rules. Consistency asks whether labels and behavior stay familiar across pages. Error prevention asks whether the design reduces likely mistakes before they happen. Visibility of system status asks whether the site tells people what is happening through a loading sign, confirmation, or useful error message.\n\nA heuristic review is not a personal opinion about decoration. It is a structured way to look for avoidable user problems.", "التقييم الاستدلالي مراجعة خبير للواجهة باستخدام قواعد عملية لسهولة الاستخدام. يسأل الاتساق هل تبقى التسميات والسلوك مألوفة عبر الصفحات. ويسأل منع الأخطاء هل يقلل التصميم الأخطاء المحتملة قبل وقوعها. ويسأل وضوح حالة النظام هل يخبر الموقع الناس بما يحدث عبر علامة تحميل أو تأكيد أو رسالة خطأ مفيدة.\n\nليست المراجعة الاستدلالية رأيًا شخصيًا في الزينة، بل طريقة منظمة للبحث عن مشكلات مستخدم يمكن تجنبها."), visual: "heuristics" },
      { title: L("Use evidence to choose the next question", "استخدم الأدلة لاختيار السؤال التالي"), body: L("A responsible team combines evidence. Analytics might show a high first-page exit rate. A usability test may then show that visitors cannot find the action they came for. An expert review may reveal inconsistent labels or a missing confirmation message. Together, these sources help the team choose one useful next improvement.\n\nEvaluation is not a one-time score for a site. It is a way to learn what to improve and then check whether the change helped.", "يجمع الفريق المسؤول بين الأدلة. قد تظهر التحليلات معدل خروج مرتفعًا من الصفحة الأولى. وقد يبين اختبار سهولة الاستخدام بعد ذلك أن الزوار لا يجدون الإجراء الذي أتوا من أجله. وقد تكشف مراجعة خبير تسميات غير متسقة أو رسالة تأكيد مفقودة. معًا تساعد هذه المصادر الفريق على اختيار تحسين مفيد واحد تالٍ.\n\nالتقييم ليس درجة لمرة واحدة للموقع، بل طريقة لتعلم ما ينبغي تحسينه ثم التحقق من أن التغيير أفاد."), visual: "evidence-loop" },
    ],
    keyTerms: evaluationFacts.map((fact) => ({ term: fact.term, definition: fact.definition })),
    takeaway: L("Use numbers to see what is happening, qualitative evidence to investigate why, and heuristics to spot avoidable interface problems.", "استخدم الأرقام لرؤية ما يحدث، والأدلة النوعية لفحص السبب، والقواعد الإرشادية لاكتشاف مشكلات واجهة يمكن تجنبها."),
    summaryPoints: [L("Quantitative evidence answers how much; qualitative evidence investigates why.", "تجيب الأدلة الكمية عن كم؛ وتفحص الأدلة النوعية لماذا."), L("PV counts views, bounce rate counts first-page exits, and CVR counts target actions.", "تعد PV المشاهدات، ويعد معدل الارتداد الخروج من الصفحة الأولى، ويعد CVR الإجراءات المستهدفة."), L("A high-PV, low-CVR pattern needs investigation rather than assumptions.", "يحتاج نمط مشاهدات عالية وتحويل منخفض إلى فحص لا إلى افتراضات."), L("Heuristic evaluation checks consistency, error prevention, and system status.", "يفحص التقييم الاستدلالي الاتساق ومنع الأخطاء وحالة النظام."), L("Combining evidence produces a stronger next decision.", "يؤدي جمع الأدلة إلى قرار تالٍ أقوى.")],
    practice: assessment("practice", evaluationFacts), quiz: assessment("quiz", evaluationFacts),
    activities: [
      { id: "evaluation-sort", title: L("Sort the evidence", "صنف الأدلة"), instruction: L("Classify each finding as qualitative or quantitative evidence.", "صنف كل نتيجة على أنها دليل نوعي أو كمي.") },
      { id: "metric-lab", title: L("Read the metric lab", "اقرأ مختبر المقاييس"), instruction: L("Calculate simple bounce rate and CVR cases, then decide what the numbers can and cannot tell you.", "احسب حالات بسيطة لمعدل الارتداد والتحويل، ثم حدد ما الذي تستطيع الأرقام إظهاره وما لا تستطيع." ) },
      { id: "heuristic-map", title: L("Map the interface issue", "اربط مشكلة الواجهة"), instruction: L("Match each broken-interface example to consistency, error prevention, or system status.", "طابق كل مثال لواجهة معطلة بالاتساق أو منع الأخطاء أو حالة النظام.") },
    ],
    challenge: { id: "bookstore-evaluation", title: L("A bookstore has visitors, but few buyers", "متجر كتب لديه زوار لكن مشترين قليلين"), prompt: L("An online bookstore has high page views, a low purchase CVR, and many first-page exits. Identify the metrics, choose a qualitative method, write one question for users, and propose a focused next evaluation—not a full redesign.", "لدى متجر كتب إلكتروني مشاهدات صفحات عالية ومعدل تحويل شراء منخفض وخروج كثير من الصفحة الأولى. حدد المقاييس واختر طريقة نوعية واكتب سؤالًا واحدًا للمستخدمين واقترح تقييمًا تاليًا مركزًا لا إعادة تصميم كاملة."), successCriteria: [L("Read the numerical pattern accurately.", "اقرأ النمط الرقمي بدقة."), L("Choose a method that can investigate why.", "اختر طريقة يمكنها فحص السبب."), L("State one focused question or next check.", "اذكر سؤالًا واحدًا مركزًا أو فحصًا تاليًا.") ] },
    reflection: { transfer: L("What could your school learn from page-view data, and what would still require talking to students?", "ماذا قد تتعلم مدرستك من بيانات مشاهدات الصفحات، وماذا سيظل بحاجة إلى الحديث مع الطلاب؟"), pairDiscussion: L("One learner argues for analytics first; another argues for observing users first. When would each be useful?", "يرى طالب أن تبدأ بالتحليلات، ويرى آخر أن تبدأ بملاحظة المستخدمين. متى يفيد كل منهما؟"), individualPrompt: L("Write one number you would measure and one user question you would ask.", "اكتب رقمًا واحدًا ستقيسه وسؤال مستخدم واحدًا ستطرحه.") },
    extraTaskCount: 4,
  },
  "iterative-website-improvement": {
    sourcePages: "95–101",
    objectives: [L("Explain PDCA, Design Thinking, and A/B testing as complementary improvement tools.", "اشرح PDCA والتفكير التصميمي واختبار A/B بوصفها أدوات تحسين متكاملة."), L("Plan one measurable, user-focused website improvement instead of redesigning everything.", "خطط لتحسين واحد قابل للقياس ومتمحور حول المستخدم بدل إعادة تصميم كل شيء.")],
    explanation: [
      { title: L("Launch is the beginning of learning", "النشر هو بداية التعلم"), body: L("When a website is launched, real users reveal misunderstandings, obstacles, and opportunities that a team did not predict. Iteration means improving repeatedly: make a focused change, learn from its result, then decide what to do next.\n\nThis does not mean changing everything whenever a number moves. It means choosing a goal, collecting evidence, and making a measured next step. A site can become more useful through many small, thoughtful cycles.", "عند نشر موقع يكشف المستخدمون الحقيقيون سوء الفهم والعقبات والفرص التي لم يتوقعها الفريق. يعني التحسين التكراري أن نتحسن مرارًا: نجري تغييرًا مركزًا ونتعلم من نتيجته ثم نقرر ما نفعله بعد ذلك.\n\nلا يعني هذا تغيير كل شيء كلما تحرك رقم، بل يعني اختيار هدف وجمع أدلة واتخاذ خطوة تالية مقيسة. يمكن أن يصبح الموقع أكثر فائدة عبر دورات صغيرة ومدروسة كثيرة."), visual: "pdca" },
      { title: L("Use PDCA to manage a learning loop", "استخدم PDCA لإدارة حلقة تعلم"), body: L("PDCA stands for Plan, Do, Check, Act. In Plan, set a goal and choose a change. In Do, implement it. In Check, compare the result with the goal using evidence. In Act, keep, refine, or replace the change—and begin the next plan.\n\nFor example, a team wants fewer first-page exits. It plans clearer navigation, makes the change, checks bounce rate and user feedback, then decides whether to keep refining the navigation or investigate another obstacle. Check is about the result, not simply whether code has been typed correctly.", "ترمز PDCA إلى خطط ونفذ وتحقق وتصرف. في مرحلة التخطيط تحدد هدفًا وتختار تغييرًا. وفي التنفيذ تطبقه. وفي التحقق تقارن النتيجة بالهدف باستخدام الأدلة. وفي التصرف تبقي التغيير أو تحسنه أو تستبدله، ثم تبدأ خطة جديدة.\n\nفمثلًا يريد فريق تقليل الخروج من الصفحة الأولى. يخطط لتنقل أوضح وينفذ التغيير ويتحقق من معدل الارتداد وتغذية المستخدمين ثم يقرر هل يستمر في تحسين التنقل أو يفحص عائقًا آخر. التحقق يتعلق بالنتيجة، لا بمجرد كتابة الكود بشكل صحيح."), visual: "pdca" },
      { title: L("Understand people before solving the problem", "افهم الناس قبل حل المشكلة"), body: L("Design Thinking provides another user-focused path: Empathize, Define, Ideate, Prototype, Test. First understand users and their situation. Then define the actual problem, generate several ideas, create a quick testable version, and let people try it. Testing can send a team back to an earlier stage.\n\nThe difference matters. “Our button colour is boring” is not yet a user problem. “Mobile users cannot find the registration action” is a defined problem that can lead to practical ideas and a small prototype.", "يقدم التفكير التصميمي مسارًا آخر متمحورًا حول المستخدم: افهم المستخدم وحدد المشكلة وولد الأفكار وأنشئ نموذجًا أوليًا واختبر. افهم أولًا المستخدمين وموقفهم، ثم حدد المشكلة الفعلية وولد عدة أفكار وأنشئ نسخة سريعة قابلة للاختبار ودع الناس يجربونها. وقد يعيد الاختبار الفريق إلى مرحلة سابقة.\n\nوالفرق مهم. فعبارة «لون زرنا ممل» ليست مشكلة مستخدم بعد. أما «لا يستطيع مستخدمو الهاتف العثور على إجراء التسجيل» فهي مشكلة محددة تقود إلى أفكار عملية ونموذج أولي صغير."), visual: "design-thinking" },
      { title: L("Compare one clear alternative at a time", "قارن بديلًا واضحًا واحدًا في كل مرة"), body: L("An A/B test compares two versions with real users and a chosen measure. If Version A says “Register” and Version B says “Join Event,” while everything else stays the same, the team can compare results. In a simulated result, 32 of 100 people choose A and 47 of 100 choose B; B performs better in that sample.\n\nOnly one element should change at a time. If text, colour, position, and page layout all change together, the result cannot identify the cause. The team should also collect enough data before making a confident decision. PDCA manages the overall loop; Design Thinking understands the problem; A/B testing compares one focused option.", "يقارن اختبار A/B نسختين مع مستخدمين حقيقيين ومقياس مختار. فإذا كتبت النسخة A «سجل» وكتبت النسخة B «انضم إلى الفعالية» وبقي كل شيء آخر كما هو، يستطيع الفريق مقارنة النتائج. في نتيجة محاكاة يختار 32 من 100 النسخة A ويختار 47 من 100 النسخة B؛ فتؤدي B أفضل في هذه العينة.\n\nينبغي تغيير عنصر واحد فقط في كل مرة. فإذا تغير النص واللون والموضع وتخطيط الصفحة معًا، فلن تحدد النتيجة السبب. وينبغي للفريق أيضًا جمع بيانات كافية قبل قرار واثق. تدير PDCA الحلقة العامة؛ ويفهم التفكير التصميمي المشكلة؛ ويقارن اختبار A/B خيارًا واحدًا مركزًا."), visual: "ab-test" },
      { title: L("A connected process for better websites", "عملية مترابطة لمواقع أفضل"), body: L("A strong web-improvement process begins with a purpose and audience, chooses media, understands the user, plans the page, and makes information clear. After people use the page, evidence identifies a problem. PDCA, Design Thinking, and A/B testing then support a careful improvement and another round of learning.\n\nThe point is not a perfect first version. It is a respectful, evidence-based cycle that keeps the user visible in each decision.", "تبدأ عملية قوية لتحسين المواقع بالغرض والجمهور واختيار الوسائط وفهم المستخدم وتخطيط الصفحة وجعل المعلومات واضحة. وبعد أن يستخدم الناس الصفحة، تحدد الأدلة مشكلة. ثم تدعم PDCA والتفكير التصميمي واختبار A/B تحسينًا دقيقًا وجولة تعلم جديدة.\n\nالمقصود ليس نسخة أولى كاملة، بل دورة محترمة مبنية على الأدلة تُبقي المستخدم حاضرًا في كل قرار."), visual: "unit4-master" },
    ],
    keyTerms: improvementFacts.map((fact) => ({ term: fact.term, definition: fact.definition })),
    takeaway: L("Improve deliberately: understand the user, change one focused thing, measure it, decide what to do, and repeat.", "حسّن بتعمد: افهم المستخدم، وغيّر شيئًا واحدًا مركزًا، وقسه، وقرر ما ستفعله، ثم كرر."),
    summaryPoints: [L("Iteration learns from real use after launch.", "يتعلم التحسين التكراري من الاستخدام الحقيقي بعد النشر."), L("PDCA is Plan → Do → Check → Act → repeat.", "PDCA هي خطط ← نفذ ← تحقق ← تصرف ← كرر."), L("Design Thinking begins with users and uses a testable prototype.", "يبدأ التفكير التصميمي بالمستخدمين ويستخدم نموذجًا أوليًا قابلًا للاختبار."), L("A/B testing compares two alternatives with one changed element.", "يقارن اختبار A/B بديلين مع تغيير عنصر واحد."), L("Enough evidence guides the next focused decision.", "توجه الأدلة الكافية القرار التالي المركز.")],
    practice: assessment("practice", improvementFacts), quiz: assessment("quiz", improvementFacts),
    activities: [
      { id: "pdca-order", title: L("Complete the PDCA loop", "أكمل حلقة PDCA"), instruction: L("Use Move up and Move down to put the four steps in order, then see why the loop returns to Plan.", "استخدم التحريك للأعلى والأسفل لوضع الخطوات الأربع بالترتيب، ثم شاهد لماذا تعود الحلقة إلى التخطيط.") },
      { id: "design-thinking-order", title: L("Follow a user problem", "اتبع مشكلة مستخدم"), instruction: L("Order the Design Thinking actions for students who cannot find a registration button.", "رتب إجراءات التفكير التصميمي لطلاب لا يجدون زر التسجيل.") },
      { id: "ab-test-simulator", title: L("Compare one button change", "قارن تغيير زر واحد"), instruction: L("Read the A/B result, choose the stronger label, and explain why the rest of the page stays the same.", "اقرأ نتيجة A/B واختر التسمية الأقوى واشرح لماذا تبقى بقية الصفحة كما هي.") },
    ],
    challenge: { id: "event-improvement-loop", title: L("Turn visits into informed event registrations", "حوّل الزيارات إلى تسجيلات مدروسة للفعالية"), prompt: L("A school event page receives many visitors but few registrations. Choose one metric, describe one user problem, plan one change, select an A/B option, and state the next action after measurement. Do not redesign everything.", "تتلقى صفحة فعالية مدرسية زوارًا كثيرين لكن تسجيلات قليلة. اختر مقياسًا واحدًا ووصف مشكلة مستخدم واحدة وخطط لتغيير واحد واختر خيار A/B واذكر الإجراء التالي بعد القياس. لا تعِد تصميم كل شيء."), successCriteria: [L("Name a metric connected to the goal.", "سم مقياسًا مرتبطًا بالهدف."), L("Focus on one user problem and one change.", "ركز على مشكلة مستخدم واحدة وتغيير واحد."), L("Use the result to justify a next action.", "استخدم النتيجة لتبرير إجراء تالٍ.") ] },
    reflection: { transfer: L("If a club sign-up page had many visits and few sign-ups, what small change would you investigate first?", "إذا كان لصفحة تسجيل نادٍ زيارات كثيرة وتسجيلات قليلة، فما التغيير الصغير الذي ستفحصه أولًا؟"), pairDiscussion: L("Compare a quick A/B test with a usability observation. What can each one teach a team?", "قارن اختبار A/B سريعًا بملاحظة سهولة الاستخدام. ماذا يمكن أن يعلم كل منهما فريقًا؟"), individualPrompt: L("Write one goal, one change, and one measure for your own improvement loop.", "اكتب هدفًا واحدًا وتغييرًا واحدًا ومقياسًا واحدًا لحلقة تحسينك.") },
    unitReview: { title: L("Unit 4 review: design, evidence, improvement", "مراجعة الوحدة ٤: تصميم وأدلة وتحسين"), introduction: L("Connect the four lessons: choose media for people and purpose, design for users, evaluate with evidence, then improve deliberately.", "اربط الدروس الأربعة: اختر الوسائط للناس والغرض، وصمم للمستخدمين، وقيّم بالأدلة، ثم حسّن بتعمد."), questions: finalReview },
    extraTaskCount: 4,
  },
};
