"use client";

import { Check, Clipboard, Copy, LoaderCircle, Plus, RefreshCw, Trash2, UserRound, XCircle } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { AppLocale } from "@/lib/i18n";

type ClassOption = { id: string; title: string; code?: string };
type ManagedCode = { id: string; code?: string; type: "general" | "class"; classId: string | null; classTitle?: string | null; createdAt: string; expiresAt: string | null; maxUses: number | null; currentUses: number; active: boolean; redemptions: { studentName?: string; studentEmail?: string; student_id?: string; redeemedAt?: string; redeemed_at?: string }[] };

const copy = {
  en: { title: "Access codes", body: "Create private curriculum access codes. A class code also connects the student to its teacher and class.", general: "General access", class: "Class access", classLabel: "Class", expires: "Expires", uses: "Maximum uses", generate: "Generate code", empty: "No access codes yet.", code: "Code", type: "Type", created: "Created", use: "Uses", status: "Status", actions: "Actions", active: "Active", disabled: "Disabled", unlimited: "Unlimited", hide: "Hide", copy: "Copy", copied: "Copied", regenerate: "Regenerate", disable: "Disable", enable: "Enable", revoke: "Revoke", redemptions: "Students who used this code", noClass: "Choose a class", never: "Never", error: "We could not update this access code. Try again.", notShown: "Hidden after creation", classHelp: "A class code grants access and adds the student to the selected class." },
  ar: { title: "أكواد الدخول", body: "أنشئ أكواد وصول خاصة إلى المنهج. يربط كود الفصل الطالب بالمعلم والفصل أيضًا.", general: "وصول عام", class: "وصول فصل", classLabel: "الفصل", expires: "تاريخ الانتهاء", uses: "الحد الأقصى للاستخدام", generate: "إنشاء كود", empty: "لا توجد أكواد دخول بعد.", code: "الكود", type: "النوع", created: "الإنشاء", use: "الاستخدام", status: "الحالة", actions: "إجراءات", active: "نشط", disabled: "معطّل", unlimited: "بلا حد", hide: "إخفاء", copy: "نسخ", copied: "تم النسخ", regenerate: "تجديد", disable: "تعطيل", enable: "تفعيل", revoke: "إلغاء", redemptions: "الطلاب الذين استخدموا الكود", noClass: "اختر فصلًا", never: "دون انتهاء", error: "تعذر تحديث كود الدخول. حاول مجددًا.", notShown: "مخفي بعد الإنشاء", classHelp: "يمنح كود الفصل الوصول ويضيف الطالب إلى الفصل المحدد." },
} as const;

export function AccessCodeManager({ locale }: { locale: AppLocale }) {
  const t = copy[locale]; const [codes, setCodes] = useState<ManagedCode[]>([]); const [classes, setClasses] = useState<ClassOption[]>([]); const [type, setType] = useState<"general" | "class">("general"); const [classId, setClassId] = useState(""); const [expiresAt, setExpiresAt] = useState(""); const [maxUses, setMaxUses] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [revealed, setRevealed] = useState<Record<string, string>>({}); const [copied, setCopied] = useState("");
  const classTitle = useMemo(() => classes.find((item) => item.id === classId)?.title, [classes, classId]);
  const refresh = async () => { const [codesResponse, classesResponse] = await Promise.all([fetch("/api/v1/access-codes", { cache: "no-store" }), fetch("/api/v1/classes", { cache: "no-store" })]); if (codesResponse.ok) setCodes((await codesResponse.json()).codes); if (classesResponse.ok) setClasses((await classesResponse.json()).classes); };
  useEffect(() => { void refresh(); }, []);
  async function generate() { setPending(true); setError(""); try { const response = await fetch("/api/v1/access-codes", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type, classId: type === "class" ? classId : null, classTitle: type === "class" ? classTitle : null, expiresAt: expiresAt ? new Date(expiresAt).toISOString() : null, maxUses: maxUses ? Number(maxUses) : null }) }); if (!response.ok) throw new Error(); const { code } = await response.json() as { code: ManagedCode }; if (code.code) setRevealed((items) => ({ ...items, [code.id]: code.code! })); setCodes((items) => [code, ...items]); setExpiresAt(""); setMaxUses(""); } catch { setError(t.error); } finally { setPending(false); } }
  async function mutate(id: string, action: "toggle" | "delete" | "regenerate", active?: boolean) { setError(""); try { const response = await fetch(action === "regenerate" ? `/api/v1/access-codes/${id}/regenerate` : `/api/v1/access-codes/${id}`, action === "delete" ? { method: "DELETE" } : action === "toggle" ? { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ active }) } : { method: "POST" }); if (!response.ok) throw new Error(); if (action === "delete") setCodes((items) => items.filter((item) => item.id !== id)); else { const { code } = await response.json() as { code: ManagedCode }; if (code.code) setRevealed((items) => ({ ...items, [id]: code.code! })); setCodes((items) => items.map((item) => item.id === id ? { ...item, ...code } : item)); } } catch { setError(t.error); } }
  async function copyCode(id: string, code: string | undefined) { if (!code) return; await navigator.clipboard?.writeText(code); setCopied(id); window.setTimeout(() => setCopied(""), 1300); }
  return <article className="panel dashboard-card full access-code-manager"><div className="status-head"><div><span className="eyebrow">{locale === "ar" ? "إدارة الوصول" : "Access management"}</span><h2>{t.title}</h2><p>{t.body}</p></div></div><div className={`access-code-create access-code-create--${type}`}><div className="segmented" role="group" aria-label={t.type}><button type="button" data-active={type === "general"} onClick={() => setType("general")}>{t.general}</button><button type="button" data-active={type === "class"} onClick={() => setType("class")}>{t.class}</button></div>{type === "class" && <label className="field"><span>{t.classLabel}</span><select className="select-input" value={classId} onChange={(event) => setClassId(event.target.value)}><option value="">{t.noClass}</option>{classes.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select><small>{t.classHelp}</small></label>}<label className="field"><span>{t.expires}</span><input className="text-input" type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} /></label><label className="field"><span>{t.uses}</span><input className="text-input" type="number" min="1" max="10000" value={maxUses} onChange={(event) => setMaxUses(event.target.value)} placeholder={t.unlimited} /></label><button className="button" type="button" disabled={pending || (type === "class" && !classId)} onClick={() => void generate()}>{pending ? <LoaderCircle className="spin" /> : <Plus />}{t.generate}</button></div>{error && <p className="feedback error" role="alert">{error}</p>}
    {codes.length ? <div className="table-wrap"><table><thead><tr><th>{t.code}</th><th>{t.type}</th><th>{t.created}</th><th>{t.expires}</th><th>{t.use}</th><th>{t.status}</th><th>{t.actions}</th></tr></thead><tbody>{codes.map((item) => { const shownCode = revealed[item.id] ?? item.code; return <tr key={item.id}><td><div className="code-cell"><code>{shownCode ?? t.notShown}</code>{shownCode && <button className="icon-button" type="button" onClick={() => void copyCode(item.id, shownCode)} aria-label={t.copy}>{copied === item.id ? <Check size={16} /> : <Copy size={16} />}</button>}</div></td><td>{item.type === "class" ? `${t.class}${item.classTitle ? ` · ${item.classTitle}` : ""}` : t.general}</td><td>{new Intl.DateTimeFormat(locale === "ar" ? "ar-EG" : "en-GB", { dateStyle: "medium" }).format(new Date(item.createdAt))}</td><td>{item.expiresAt ? new Intl.DateTimeFormat(locale === "ar" ? "ar-EG" : "en-GB", { dateStyle: "medium" }).format(new Date(item.expiresAt)) : t.never}</td><td>{item.currentUses}/{item.maxUses ?? "∞"}</td><td><span className={`badge ${item.active ? "" : "draft"}`}>{item.active ? t.active : t.disabled}</span></td><td><div className="table-actions"><button className="button ghost small" type="button" onClick={() => void mutate(item.id, "regenerate")}><RefreshCw size={15} />{t.regenerate}</button><button className="button ghost small" type="button" onClick={() => void mutate(item.id, "toggle", !item.active)}>{item.active ? <XCircle size={15} /> : <Check size={15} />}{item.active ? t.disable : t.enable}</button><button className="button ghost small danger" type="button" onClick={() => void mutate(item.id, "delete")}><Trash2 size={15} />{t.revoke}</button></div>{item.redemptions.length > 0 && <details className="redemption-list"><summary><UserRound size={14} /> {t.redemptions} ({item.redemptions.length})</summary><ul>{item.redemptions.map((redemption, index) => <li key={index}>{redemption.studentName ?? redemption.student_id ?? "Student"} · {new Intl.DateTimeFormat(locale === "ar" ? "ar-EG" : "en-GB", { dateStyle: "short", timeStyle: "short" }).format(new Date(redemption.redeemedAt ?? redemption.redeemed_at ?? Date.now()))}</li>)}</ul></details>}</td></tr>; })}</tbody></table></div> : <div className="empty-state"><Clipboard /><p>{t.empty}</p></div>}
  </article>;
}
