"use client";

import { Atom, BarChart3, Bot, BrainCircuit, Car, CheckCircle2, ChevronLeft, ChevronRight, CircleAlert, ClipboardCheck, Cloud, Code2, Cpu, Database, Download, Factory, FileText, Fingerprint, Glasses, Laptop, Lightbulb, ListChecks, LockKeyhole, Map, Network, Palette, ReceiptText, Repeat2, RotateCcw, Router, ScanFace, Send, Server, ShieldCheck, ShoppingCart, Smartphone, Sparkles, Sprout, Telescope, UserRoundCheck, Users, Volume2, Wifi } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState, type CSSProperties } from "react";
import type { CurriculumLesson, CurriculumQuestion } from "@/content/part1-curriculum";
import { Unit2ActivityRenderer, Unit2Challenge, Unit2FinalReview, type SavedUnit2Mistake } from "@/components/unit2-interactives";
import { Unit3ActivityRenderer, Unit3Challenge } from "@/components/unit3-interactives";
import { Unit4ActivityRenderer, Unit4Challenge } from "@/components/unit4-interactives";
import { Unit1Challenge } from "@/components/unit1-interactives";
import { touchLessonProgress, writeLessonProgress, type LocalLessonMistake } from "@/lib/demo-progress";
import { cacheLessonUrls } from "@/lib/offline";
import type { Locale } from "@/lib/types";

type Step = "explanation" | "summary" | "practice" | "solutions" | "quiz" | "challenge" | "unit-review";
type Stored = { step: Step; answers: Record<string, string>; solutions: boolean; quizSubmitted: boolean; completedActivities: string[]; challengeCompleted: boolean; reflection: string; reviewSubmitted: boolean; reviewScore?: number; reviewMistakes: LocalLessonMistake[]; reviewAnswers: Record<string, string>; reviewOrders: Record<string, string[]> };
const pick = (locale: Locale, value: { en: string; ar: string }) => value[locale];
const tr = (locale: Locale, en: string, ar: string) => locale === "ar" ? ar : en;
const baseSteps: { id: Step; en: string; ar: string }[] = [
  { id: "explanation", en: "Explanation", ar: "الشرح" }, { id: "summary", en: "Summary", ar: "الملخص" },
  { id: "practice", en: "Practice Questions", ar: "أسئلة التدريب" }, { id: "solutions", en: "Solutions", ar: "الحلول" }, { id: "quiz", en: "Quiz", ar: "الاختبار" },
];
const initialStored = (): Stored => ({ step: "explanation", answers: {}, solutions: false, quizSubmitted: false, completedActivities: [], challengeCompleted: false, reflection: "", reviewSubmitted: false, reviewMistakes: [], reviewAnswers: {}, reviewOrders: {} });
function stepsForLesson(lesson: CurriculumLesson) {
  const steps = [...baseSteps];
  if (lesson.challenge) steps.push({ id: "challenge", en: "Engineer Challenge", ar: "تحدي المهندس" });
  if (lesson.unitReview) steps.push({ id: "unit-review", en: `Unit ${lesson.unit} Review`, ar: `مراجعة الوحدة ${lesson.unit === 1 ? "١" : lesson.unit === 2 ? "٢" : lesson.unit === 3 ? "٣" : lesson.unit}` });
  return steps;
}

function Question({ question, locale, value, onChange, reveal, locked }: { question: CurriculumQuestion; locale: Locale; value?: string; onChange: (value: string) => void; reveal?: boolean; locked?: boolean }) {
  const correct = question.type === "short" ? Boolean(value?.trim()) : question.type === "cloze" ? value?.trim().toLocaleLowerCase() === question.answer.toLocaleLowerCase() : value === question.answer;
  return <article className={`panel curriculum-question ${reveal ? (correct ? "is-correct" : "is-incorrect") : ""}`}>
    <p className="question-number">{question.id.replace(/^(practice|quiz)-/, "").replace("-", " ")}</p>
    <h3>{pick(locale, question.prompt)}</h3>
    {question.choices ? <div className="question-options" role="radiogroup" aria-label={pick(locale, question.prompt)}>
      {question.choices.map((choice) => <label className="choice-row" key={choice.id}>
        <input type="radio" name={question.id} value={choice.id} checked={value === choice.id} disabled={locked} onChange={() => onChange(choice.id)} />
        <span>{pick(locale, choice.text)}</span>
      </label>)}
    </div> : <input className="short-answer" value={value ?? ""} disabled={locked} onChange={(event) => onChange(event.target.value)} placeholder={tr(locale, "Write your answer", "اكتب إجابتك")} />}
    {reveal && <div className="answer-feedback" role="status"><strong>{correct ? tr(locale, "Correct", "إجابة صحيحة") : tr(locale, "Review this", "راجع هذه النقطة")}</strong><p>{pick(locale, question.explanation)}</p></div>}
  </article>;
}

function DiagramLabel({ locale, en, ar }: { locale: Locale; en: string; ar: string }) { return <>{tr(locale, en, ar)}</>; }

function Unit1Diagram({ visual, locale }: { visual: CurriculumLesson["explanation"][number]["visual"]; locale: Locale }) {
  if (visual === "timeline") {
    const stages = [
      ["1940s–60s", "1940–1960", Cpu, "Early computers", "الحواسيب المبكرة"], ["1970s–80s", "1970–1980", FileText, "Personal computers", "الحواسيب الشخصية"], ["1990s", "التسعينيات", Network, "Internet & Web", "الإنترنت والويب"], ["2000s", "الألفية الجديدة", Smartphone, "Mobile Internet", "الإنترنت المحمول"], ["2010s+", "2010 وما بعده", Cloud, "Cloud services", "الخدمات السحابية"],
    ] as const;
    return <figure className="edu-diagram edu-timeline"><figcaption><Cpu /><DiagramLabel locale={locale} en="Information technology timeline" ar="الخط الزمني لتكنولوجيا المعلومات" /></figcaption><ol>{stages.map(([enDate, arDate, Icon, enTitle, arTitle], index) => <li key={enDate}><div className="timeline-node"><Icon aria-hidden="true" /><span className="timeline-date"><DiagramLabel locale={locale} en={enDate} ar={arDate} /></span></div><strong><DiagramLabel locale={locale} en={enTitle} ar={arTitle} /></strong>{index < stages.length - 1 && <i className="timeline-link" aria-hidden="true" />}</li>)}</ol><p><DiagramLabel locale={locale} en="Specialist machines → personal access → global connection → computing everywhere → IT as a service" ar="آلات المتخصصين ← وصول شخصي ← اتصال عالمي ← حوسبة في كل مكان ← تكنولوجيا كمعلومات كخدمة" /></p></figure>;
  }
  if (visual === "moore") return <figure className="edu-diagram edu-moore"><figcaption><Cpu /><DiagramLabel locale={locale} en="Moore's Law: capability grew as transistor density increased" ar="قانون مور: ازدادت القدرة مع زيادة كثافة الترانزستورات" /></figcaption><div className="moore-progression"><div><span className="chip chip-low">{Array.from({ length: 6 }, (_, i) => <i key={i} />)}</span><small><DiagramLabel locale={locale} en="Fewer transistors" ar="ترانزستورات أقل" /></small></div><span className="process-arrow" aria-hidden="true" /><div><span className="chip chip-medium">{Array.from({ length: 16 }, (_, i) => <i key={i} />)}</span><small><DiagramLabel locale={locale} en="More density" ar="كثافة أعلى" /></small></div><span className="process-arrow" aria-hidden="true" /><div><span className="chip chip-high">{Array.from({ length: 30 }, (_, i) => <i key={i} />)}</span><small><DiagramLabel locale={locale} en="Greater capability" ar="قدرة أكبر" /></small></div></div><div className="limit-callout"><Atom aria-hidden="true" /><div><strong><DiagramLabel locale={locale} en="Physical limits" ar="حدود فيزيائية" /></strong><span><DiagramLabel locale={locale} en="Quantum tunnelling and leakage current make endless miniaturisation difficult." ar="يجعل النفق الكمي وتسرب التيار تصغير المكونات إلى ما لا نهاية أمرًا صعبًا." /></span></div></div></figure>;
  if (visual === "edge") return <figure className="edu-diagram edu-compute"><figcaption><Network /><DiagramLabel locale={locale} en="Cloud computing and edge computing" ar="الحوسبة السحابية والحوسبة الطرفية" /></figcaption><div className="compute-columns"><section className="cloud-route"><h3><Cloud /> <DiagramLabel locale={locale} en="Cloud route" ar="مسار السحابة" /></h3><div className="route-flow"><span><Car /><DiagramLabel locale={locale} en="Vehicle & sensors" ar="المركبة والمستشعرات" /></span><i /><span><Wifi /><DiagramLabel locale={locale} en="Internet" ar="الإنترنت" /></span><i /><span><Server /><DiagramLabel locale={locale} en="Cloud server" ar="خادم سحابي" /></span><i /><span><Cpu /><DiagramLabel locale={locale} en="Processing" ar="معالجة" /></span><i /><span><Car /><DiagramLabel locale={locale} en="Response" ar="استجابة" /></span></div><p className="latency-note"><span className="latency-bars"><i /><i /><i /></span><DiagramLabel locale={locale} en="Network trip can add delay" ar="قد تضيف الرحلة عبر الشبكة تأخرًا" /></p></section><section className="edge-route"><h3><Cpu /> <DiagramLabel locale={locale} en="Edge route" ar="مسار الطرف" /></h3><div className="route-flow"><span><Car /><DiagramLabel locale={locale} en="Vehicle & sensors" ar="المركبة والمستشعرات" /></span><i /><span><Cpu /><DiagramLabel locale={locale} en="Local edge processing" ar="معالجة طرفية محلية" /></span><i /><span><ShieldCheck /><DiagramLabel locale={locale} en="Immediate decision" ar="قرار فوري" /></span></div><p className="latency-note fast"><CheckCircle2 /><DiagramLabel locale={locale} en="Low latency for time-critical decisions" ar="زمن تأخر منخفض للقرارات الحساسة للوقت" /></p></section></div></figure>;
  if (visual === "arvr") return <figure className="edu-diagram edu-arvr"><figcaption><Glasses /><DiagramLabel locale={locale} en="AR, VR, and a first look at quantum computing" ar="الواقع المعزز والافتراضي ولمحة أولى عن الحوسبة الكمية" /></figcaption><div className="arvr-grid"><section className="ar-card"><div className="scene"><Map /><i className="overlay-card">+</i></div><h3>AR</h3><p><DiagramLabel locale={locale} en="Real world + digital information" ar="العالم الحقيقي + معلومات رقمية" /></p></section><section className="vr-card"><div className="scene"><Glasses /><i className="virtual-orbit" /></div><h3>VR</h3><p><DiagramLabel locale={locale} en="Immersive computer-generated environment" ar="بيئة رقمية مولدة وغامرة" /></p></section></div><div className="quantum-strip"><section><Cpu /><div><strong><DiagramLabel locale={locale} en="Classical computer" ar="حاسوب تقليدي" /></strong><span><DiagramLabel locale={locale} en="Bit: 0 or 1" ar="بت: 0 أو 1" /></span></div></section><i /><section><Atom /><div><strong><DiagramLabel locale={locale} en="Quantum computer" ar="حاسوب كمي" /></strong><span><DiagramLabel locale={locale} en="Qubit: superposition concept" ar="كيوبت: مفهوم التراكب" /></span></div></section></div></figure>;
  if (visual === "hierarchy") return <figure className="edu-diagram edu-ai-hierarchy"><figcaption><BrainCircuit /><DiagramLabel locale={locale} en="AI technologies are nested" ar="تقنيات الذكاء الاصطناعي متداخلة" /></figcaption><div className="nest ai"><strong>Artificial Intelligence <small>AI</small></strong><div className="nest ml"><strong>Machine Learning <small>ML</small></strong><div className="nest dl"><strong>Deep Learning <small>DL</small></strong><div className="nest gen"><strong>Generative AI</strong><span><DiagramLabel locale={locale} en="creates new output" ar="ينشئ مخرجات جديدة" /></span></div></div></div></div><p><DiagramLabel locale={locale} en="Each inner area is a more specialised part of the area around it." ar="كل مساحة داخلية جزء أكثر تخصصًا من المساحة التي تحيط بها." /></p></figure>;
  if (visual === "rules") return <figure className="edu-diagram edu-rules"><figcaption><Bot /><DiagramLabel locale={locale} en="Two ways a system can make a decision" ar="طريقتان يمكن للنظام أن يتخذ بهما قرارًا" /></figcaption><div className="rules-grid"><section><FileText /><h3><DiagramLabel locale={locale} en="Rule-based program" ar="برنامج قائم على القواعد" /></h3><div className="mini-flow"><span><DiagramLabel locale={locale} en="Written rule" ar="قاعدة مكتوبة" /></span><i /><span><DiagramLabel locale={locale} en="Decision" ar="قرار" /></span></div><p><DiagramLabel locale={locale} en="People specify instructions for cases." ar="يحدد البشر التعليمات للحالات." /></p></section><section><Database /><h3><DiagramLabel locale={locale} en="Machine Learning" ar="تعلم الآلة" /></h3><div className="mini-flow"><span><DiagramLabel locale={locale} en="Data" ar="بيانات" /></span><i /><span><DiagramLabel locale={locale} en="Pattern" ar="نمط" /></span><i /><span><DiagramLabel locale={locale} en="Prediction" ar="تنبؤ" /></span></div><p><DiagramLabel locale={locale} en="The system learns patterns from examples." ar="يتعلم النظام الأنماط من الأمثلة." /></p></section></div></figure>;
  if (visual === "neural") return <figure className="edu-diagram edu-neural"><figcaption><BrainCircuit /><DiagramLabel locale={locale} en="A conceptual neural network" ar="شبكة عصبية مفاهيمية" /></figcaption><svg viewBox="0 0 420 170" role="img" aria-label={tr(locale, "Connected layers learn patterns from data", "طبقات مترابطة تتعلم الأنماط من البيانات")}><g className="neural-links">{[42,85,128].flatMap((a) => [58,100,142].map((b) => <line key={`${a}-${b}`} x1="65" y1={a} x2="180" y2={b} />)).concat([58,100,142].flatMap((a) => [75,120].map((b) => <line key={`${a}-${b}`} x1="205" y1={a} x2="310" y2={b} />))).concat([75,120].map((a) => <line key={a} x1="335" y1={a} x2="390" y2="98" />))}</g><g className="neural-nodes">{[42,85,128].map((y) => <circle key={`a${y}`} cx="52" cy={y} r="13" />)}{[58,100,142].map((y) => <circle key={`b${y}`} cx="193" cy={y} r="13" />)}{[75,120].map((y) => <circle key={`c${y}`} cx="323" cy={y} r="13" />)}<circle cx="400" cy="98" r="15" /></g><text x="20" y="162">{tr(locale, "Input", "إدخال")}</text><text x="158" y="162">{tr(locale, "Hidden layers", "طبقات خفية")}</text><text x="372" y="162">{tr(locale, "Output", "مخرج")}</text></svg></figure>;
  if (visual === "generative") return <figure className="edu-diagram edu-generative"><figcaption><Sparkles /><DiagramLabel locale={locale} en="Generative AI creates new output" ar="الذكاء الاصطناعي التوليدي ينشئ مخرجات جديدة" /></figcaption><div><section><FileText /><span><DiagramLabel locale={locale} en="Text" ar="نص" /></span></section><section><Glasses /><span><DiagramLabel locale={locale} en="Images" ar="صور" /></span></section><section><Volume2 /><span><DiagramLabel locale={locale} en="Audio" ar="صوت" /></span></section><section><Cpu /><span><DiagramLabel locale={locale} en="Programs" ar="برامج" /></span></section></div></figure>;
  if (visual === "everyday") return <figure className="edu-diagram edu-use-cards"><figcaption><Smartphone /><DiagramLabel locale={locale} en="AI in daily life" ar="الذكاء الاصطناعي في الحياة اليومية" /></figcaption><div><section><ShoppingCart /><strong><DiagramLabel locale={locale} en="Recommendations" ar="التوصيات" /></strong></section><section><Volume2 /><strong><DiagramLabel locale={locale} en="Voice assistants" ar="المساعدات الصوتية" /></strong></section><section><FileText /><strong><DiagramLabel locale={locale} en="Translation" ar="الترجمة" /></strong></section><section><ScanFace /><strong><DiagramLabel locale={locale} en="Face recognition" ar="التعرف على الوجه" /></strong></section></div></figure>;
  if (visual === "industry") return <figure className="edu-diagram edu-use-cards industry"><figcaption><Factory /><DiagramLabel locale={locale} en="AI across industries" ar="الذكاء الاصطناعي عبر الصناعات" /></figcaption><div><section><UserRoundCheck /><strong><DiagramLabel locale={locale} en="Healthcare" ar="الرعاية الصحية" /></strong></section><section><Sprout /><strong><DiagramLabel locale={locale} en="Agriculture" ar="الزراعة" /></strong></section><section><Factory /><strong><DiagramLabel locale={locale} en="Manufacturing" ar="التصنيع" /></strong></section><section><Map /><strong><DiagramLabel locale={locale} en="Logistics" ar="اللوجستيات" /></strong></section></div></figure>;
  if (visual === "caution" || visual === "compare") return <figure className="edu-diagram edu-good-caution"><figcaption><BrainCircuit /><DiagramLabel locale={locale} en="Use AI with informed human judgment" ar="استخدم الذكاء الاصطناعي بحكم بشري واعٍ" /></figcaption><div><section className="good"><CheckCircle2 /><h3><DiagramLabel locale={locale} en="AI is good at" ar="يجيد الذكاء الاصطناعي" /></h3><ul><li><DiagramLabel locale={locale} en="Finding patterns" ar="اكتشاف الأنماط" /></li><li><DiagramLabel locale={locale} en="Classification and recognition" ar="التصنيف والتعرف" /></li><li><DiagramLabel locale={locale} en="Probabilistic prediction" ar="التنبؤ الاحتمالي" /></li></ul></section><section className="caution"><ShieldCheck /><h3><DiagramLabel locale={locale} en="People must consider" ar="يجب أن يراعي البشر" /></h3><ul><li><DiagramLabel locale={locale} en="Fairness and privacy" ar="الإنصاف والخصوصية" /></li><li><DiagramLabel locale={locale} en="Bias and hallucination" ar="التحيز والهلوسة" /></li><li><DiagramLabel locale={locale} en="Responsibility" ar="المسؤولية" /></li></ul></section></div></figure>;
  if (visual === "bias") return <figure className="edu-diagram edu-bias"><figcaption><ShieldCheck /><DiagramLabel locale={locale} en="How algorithmic bias can lead to harm" ar="كيف قد يقود التحيز الخوارزمي إلى ضرر" /></figcaption><div className="bias-flow"><section><Database /><strong><DiagramLabel locale={locale} en="Biased, incomplete data or design" ar="بيانات أو تصميم متحيز أو غير مكتمل" /></strong></section><i /><section><BrainCircuit /><strong><DiagramLabel locale={locale} en="AI learns a pattern" ar="يتعلم الذكاء الاصطناعي نمطًا" /></strong></section><i /><section><ReceiptText /><strong><DiagramLabel locale={locale} en="Biased judgement" ar="حكم متحيز" /></strong></section><i /><section className="harm"><UserRoundCheck /><strong><DiagramLabel locale={locale} en="Possible harm to people" ar="ضرر محتمل للناس" /></strong></section></div></figure>;
  if (visual === "xai") return <figure className="edu-diagram edu-xai"><figcaption><Telescope /><DiagramLabel locale={locale} en="Black box versus Explainable AI" ar="الصندوق الأسود مقابل الذكاء الاصطناعي القابل للتفسير" /></figcaption><div><section className="black-box"><LockKeyhole /><h3><DiagramLabel locale={locale} en="Black box" ar="الصندوق الأسود" /></h3><span><DiagramLabel locale={locale} en="Decision appears" ar="يظهر القرار" /></span><i>?</i><small><DiagramLabel locale={locale} en="Reason unclear" ar="السبب غير واضح" /></small></section><section className="explainable"><BrainCircuit /><h3><DiagramLabel locale={locale} en="Explainable AI (XAI)" ar="الذكاء القابل للتفسير (XAI)" /></h3><span><DiagramLabel locale={locale} en="Decision appears" ar="يظهر القرار" /></span><div className="reason-lines"><i /><i /><i /></div><small><DiagramLabel locale={locale} en="Relevant reasons can be checked" ar="يمكن التحقق من الأسباب المهمة" /></small></section></div></figure>;
  if (visual === "ethics") return <figure className="edu-diagram edu-ethics"><figcaption><ShieldCheck /><DiagramLabel locale={locale} en="Four principles for responsible AI" ar="أربعة مبادئ للذكاء الاصطناعي المسؤول" /></figcaption><div><section><ScaleIcon /><strong><DiagramLabel locale={locale} en="Fairness" ar="الإنصاف" /></strong><small><DiagramLabel locale={locale} en="Avoid unjust discrimination" ar="تجنب التمييز غير المبرر" /></small></section><section><Telescope /><strong><DiagramLabel locale={locale} en="Transparency" ar="الشفافية" /></strong><small><DiagramLabel locale={locale} en="Make important decisions understandable" ar="اجعل القرارات المهمة مفهومة" /></small></section><section><LockKeyhole /><strong><DiagramLabel locale={locale} en="Privacy protection" ar="حماية الخصوصية" /></strong><small><DiagramLabel locale={locale} en="Handle personal data appropriately" ar="تعامل مع البيانات الشخصية بشكل مناسب" /></small></section><section><UserRoundCheck /><strong><DiagramLabel locale={locale} en="Accountability" ar="المساءلة" /></strong><small><DiagramLabel locale={locale} en="Someone remains answerable" ar="تبقى جهة ما مسؤولة" /></small></section></div></figure>;
  if (visual === "recommendation-flow") return <figure className="edu-diagram edu-recommendation-flow"><figcaption><ShoppingCart /><DiagramLabel locale={locale} en="A recommendation uses patterns, not certainty" ar="تستخدم التوصية الأنماط لا اليقين" /></figcaption><ol><li><Database /><strong><DiagramLabel locale={locale} en="Relevant activity" ar="نشاط ذو صلة" /></strong></li><li><BrainCircuit /><strong><DiagramLabel locale={locale} en="Pattern" ar="نمط" /></strong></li><li><ShoppingCart /><strong><DiagramLabel locale={locale} en="Suggestion" ar="اقتراح" /></strong></li><li><UserRoundCheck /><strong><DiagramLabel locale={locale} en="Person checks" ar="يتحقق الشخص" /></strong></li></ol><p><DiagramLabel locale={locale} en="The suggestion can be useful, but it should stay open to correction." ar="قد يكون الاقتراح مفيدًا، لكنه يجب أن يظل قابلاً للتصحيح." /></p></figure>;
  if (visual === "operations-flow") return <figure className="edu-diagram edu-operations-flow"><figcaption><Factory /><DiagramLabel locale={locale} en="Industrial AI supports monitored decisions" ar="يدعم الذكاء الاصطناعي الصناعي قرارات خاضعة للمراقبة" /></figcaption><ol><li><Factory /><strong><DiagramLabel locale={locale} en="Machine or route data" ar="بيانات آلة أو مسار" /></strong></li><li><BrainCircuit /><strong><DiagramLabel locale={locale} en="Detect a pattern" ar="اكتشاف نمط" /></strong></li><li><Map /><strong><DiagramLabel locale={locale} en="Recommend an action" ar="اقتراح إجراء" /></strong></li><li><UserRoundCheck /><strong><DiagramLabel locale={locale} en="Monitor exceptions" ar="مراقبة الاستثناءات" /></strong></li></ol></figure>;
  if (visual === "ethics-overview") return <figure className="edu-diagram edu-ethics-overview"><figcaption><ShieldCheck /><DiagramLabel locale={locale} en="Capability alone is not a responsible decision" ar="القدرة وحدها ليست قرارًا مسؤولًا" /></figcaption><ol><li><BrainCircuit /><strong><DiagramLabel locale={locale} en="AI-supported decision" ar="قرار مدعوم بالذكاء الاصطناعي" /></strong></li><li><Users /><strong><DiagramLabel locale={locale} en="Effect on people" ar="أثر في الناس" /></strong></li><li><ScaleIcon /><strong><DiagramLabel locale={locale} en="Ethical checks" ar="فحوص أخلاقية" /></strong></li><li><CheckCircle2 /><strong><DiagramLabel locale={locale} en="Responsible outcome" ar="نتيجة مسؤولة" /></strong></li></ol></figure>;
  if (visual === "bias-intro") return <figure className="edu-diagram edu-bias-intro"><figcaption><ScaleIcon /><DiagramLabel locale={locale} en="Compare outcomes across groups, not only overall accuracy" ar="قارن النتائج بين المجموعات لا الدقة العامة فقط" /></figcaption><div><section><Users /><strong><DiagramLabel locale={locale} en="Group A" ar="المجموعة أ" /></strong><span>92%</span></section><section><Users /><strong><DiagramLabel locale={locale} en="Group B" ar="المجموعة ب" /></strong><span>68%</span></section><aside><CircleAlert /><DiagramLabel locale={locale} en="A large gap is a reason to investigate data and design." ar="الفجوة الكبيرة سبب لفحص البيانات والتصميم." /></aside></div></figure>;
  if (visual === "privacy-path") return <figure className="edu-diagram edu-privacy-path"><figcaption><LockKeyhole /><DiagramLabel locale={locale} en="Personal data needs a justified, protected path" ar="تحتاج البيانات الشخصية إلى مسار مبرر ومحمي" /></figcaption><ol><li><Database /><strong><DiagramLabel locale={locale} en="Collect only what is needed" ar="اجمع ما يلزم فقط" /></strong></li><li><BrainCircuit /><strong><DiagramLabel locale={locale} en="Use for the stated purpose" ar="استخدمه للغرض المعلن" /></strong></li><li><LockKeyhole /><strong><DiagramLabel locale={locale} en="Limit and protect access" ar="قيّد الوصول واحمه" /></strong></li><li><Users /><strong><DiagramLabel locale={locale} en="Explain and allow challenge" ar="اشرح وأتح الاعتراض" /></strong></li></ol></figure>;
  if (visual === "accountability-flow") return <figure className="edu-diagram edu-accountability-flow"><figcaption><UserRoundCheck /><DiagramLabel locale={locale} en="Accountability keeps people responsible after an AI outcome" ar="تحافظ المساءلة على مسؤولية الناس بعد نتيجة للذكاء الاصطناعي" /></figcaption><ol><li><CircleAlert /><strong><DiagramLabel locale={locale} en="Notice and pause harm" ar="اكتشف الضرر وأوقفه" /></strong></li><li><ClipboardCheck /><strong><DiagramLabel locale={locale} en="Review evidence" ar="راجع الأدلة" /></strong></li><li><Users /><strong><DiagramLabel locale={locale} en="Correct outcome and offer appeal" ar="صحح النتيجة وأتح الاعتراض" /></strong></li><li><Repeat2 /><strong><DiagramLabel locale={locale} en="Monitor the improvement" ar="راقب التحسين" /></strong></li></ol></figure>;
  if (visual === "ai-strengths") return <figure className="edu-diagram edu-ai-strengths"><figcaption><BrainCircuit /><DiagramLabel locale={locale} en="AI is useful for pattern-based tasks" ar="يفيد الذكاء الاصطناعي في المهام القائمة على الأنماط" /></figcaption><div><section><Database /><strong><DiagramLabel locale={locale} en="Classify" ar="يصنف" /></strong><small><DiagramLabel locale={locale} en="group similar cases" ar="يجمع الحالات المتشابهة" /></small></section><section><ScanFace /><strong><DiagramLabel locale={locale} en="Recognise" ar="يتعرف" /></strong><small><DiagramLabel locale={locale} en="spot known features" ar="يرصد الخصائص المعروفة" /></small></section><section><Sparkles /><strong><DiagramLabel locale={locale} en="Generate" ar="ينشئ" /></strong><small><DiagramLabel locale={locale} en="produce likely patterns" ar="ينتج أنماطًا محتملة" /></small></section><section><BarChart3 /><strong><DiagramLabel locale={locale} en="Predict" ar="يتنبأ" /></strong><small><DiagramLabel locale={locale} en="estimate, not certainty" ar="تقدير لا يقين" /></small></section></div></figure>;
  return null;
}

function Unit2Diagram({ visual, locale }: { visual: CurriculumLesson["explanation"][number]["visual"]; locale: Locale }) {
  const label = (en: string, ar: string) => <DiagramLabel locale={locale} en={en} ar={ar} />;
  if (visual === "https") return <figure className="edu-diagram unit2-diagram edu-https"><figcaption><LockKeyhole />{label("HTTPS: establish trust, then protect traffic", "HTTPS: أنشئ الثقة ثم احمِ حركة البيانات")}</figcaption><div className="https-flow"><section><Server /><strong>{label("Service", "الخدمة")}</strong><small>{label("certificate + public key", "شهادة + مفتاح عام")}</small></section><i /><section><Network /><strong>{label("Browser checks", "يتحقق المتصفح")}</strong><small>{label("identity evidence", "دليل الهوية")}</small></section><i /><section><KeyRoundIcon /><strong>{label("Session key", "مفتاح الجلسة")}</strong><small>{label("safe setup", "إعداد آمن")}</small></section><i /><section className="protected"><LockKeyhole /><strong>{label("Encrypted traffic", "حركة مشفرة")}</strong><small>{label("efficient shared key", "مفتاح مشترك فعال")}</small></section></div></figure>;
  if (visual === "key-pair") return <figure className="edu-diagram unit2-diagram edu-key-pair"><figcaption><KeyRoundIcon />{label("Two jobs in a secure connection", "وظيفتان في اتصال آمن")}</figcaption><div><section><div className="key-pair-icon"><i>Public</i><i>Private</i></div><strong>{label("Public-key cryptography", "التشفير بالمفتاح العام")}</strong><p>{label("Helps establish a shared secret safely", "يساعد على إنشاء سر مشترك بأمان")}</p></section><i className="diagram-connector" /><section><div className="shared-key-icon"><KeyRoundIcon /></div><strong>{label("Symmetric cryptography", "التشفير المتماثل")}</strong><p>{label("Efficiently protects the continuing messages", "يحمي الرسائل المستمرة بكفاءة")}</p></section></div></figure>;
  if (visual === "mfa") return <figure className="edu-diagram unit2-diagram edu-mfa"><figcaption><ShieldCheck />{label("Multi-factor authentication uses different proof types", "تستخدم المصادقة متعددة العوامل أنواعاً مختلفة من الإثبات")}</figcaption><div>{[[LockKeyhole, "Knowledge", "المعرفة", "Password", "كلمة المرور"], [Smartphone, "Possession", "الحيازة", "Approved device", "جهاز معتمد"], [ScanFace, "Biometric", "حيوي", "Fingerprint", "بصمة الإصبع"]].map(([Icon, en, ar, exampleEn, exampleAr]) => { const IconComponent = Icon as typeof LockKeyhole; return <section key={en as string}><IconComponent /><strong>{label(en as string, ar as string)}</strong><small>{label(exampleEn as string, exampleAr as string)}</small></section>; })}</div><p><CheckCircle2 />{label("MFA = proofs from at least two different categories", "MFA = إثباتات من فئتين مختلفتين على الأقل")}</p></figure>;
  if (visual === "security-map") return <figure className="edu-diagram unit2-diagram edu-security-map"><figcaption><ShieldCheck />{label("Security technologies have different jobs", "للتقنيات الأمنية وظائف مختلفة")}</figcaption><div>{[[LockKeyhole, "Encryption", "التشفير", "Keeps content private", "يحافظ على خصوصية المحتوى"], [FileText, "Digital certificate", "الشهادة الرقمية", "Checks service identity", "تتحقق من هوية الخدمة"], [CheckCircle2, "Digital signature", "التوقيع الرقمي", "Reveals tampering", "يكشف العبث"], [Smartphone, "MFA", "MFA", "Strengthens sign-in", "يقوي تسجيل الدخول"]].map(([Icon, en, ar, roleEn, roleAr]) => { const IconComponent = Icon as typeof LockKeyhole; return <section key={en as string}><IconComponent /><div><strong>{label(en as string, ar as string)}</strong><small>{label(roleEn as string, roleAr as string)}</small></div></section>; })}</div></figure>;
  if (visual === "firewall") return <figure className="edu-diagram unit2-diagram edu-firewall"><figcaption><ShieldCheck />{label("Firewall: rules control network traffic", "جدار الحماية: القواعد تتحكم في حركة الشبكة")}</figcaption><div className="firewall-path"><section><Cloud /><strong>{label("Internet", "الإنترنت")}</strong></section><i /><section className="firewall-gate"><ShieldCheck /><strong>{label("Firewall", "جدار الحماية")}</strong><small>{label("allow / block", "اسمح / امنع")}</small></section><i /><section><Server /><strong>{label("Public web service", "خدمة ويب عامة")}</strong></section></div><div className="firewall-blocked"><Database /><span>{label("Confidential database", "قاعدة بيانات سرية")}</span><b>{label("direct Internet access blocked", "الوصول المباشر من الإنترنت ممنوع")}</b></div></figure>;
  if (visual === "vpn") return <figure className="edu-diagram unit2-diagram edu-vpn"><figcaption><Wifi />{label("VPN: a protected path across the Internet", "VPN: مسار محمي عبر الإنترنت")}</figcaption><div><section><Laptop /><strong>{label("Remote staff", "موظف عن بعد")}</strong></section><i className="vpn-tunnel"><span>{label("encrypted tunnel", "نفق مشفر")}</span></i><section><Router /><strong>{label("Organisation gateway", "بوابة المؤسسة")}</strong></section></div><p>{label("The tunnel protects the path; verify the identity and permission too.", "يحمي النفق المسار؛ وتحقق من الهوية والصلاحية أيضاً.")}</p></figure>;
  if (visual === "dmz") return <figure className="edu-diagram unit2-diagram edu-dmz"><figcaption><Server />{label("DMZ separates public services from internal records", "تفصل DMZ الخدمات العامة عن السجلات الداخلية")}</figcaption><div className="dmz-zones"><section className="outside"><Cloud /><strong>{label("Internet", "الإنترنت")}</strong></section><i /><section className="dmz-zone"><Server /><strong>DMZ</strong><small>{label("public web server", "خادم ويب عام")}</small></section><i /><section className="inside"><Database /><strong>{label("Internal network", "الشبكة الداخلية")}</strong><small>{label("restricted records", "سجلات مقيدة")}</small></section></div></figure>;
  if (visual === "defense") return <figure className="edu-diagram unit2-diagram edu-defense"><figcaption><ShieldCheck />{label("Defense in depth: several layers, different jobs", "الدفاع المتعمق: طبقات متعددة ووظائف مختلفة")}</figcaption><div><section><span>1</span><Router /><strong>{label("Firewall", "جدار الحماية")}</strong></section><section><span>2</span><Wifi /><strong>VPN</strong></section><section><span>3</span><Server /><strong>DMZ</strong></section><section><span>4</span><Laptop /><strong>{label("Endpoints", "نقاط النهاية")}</strong></section><section><span>5</span><ShieldCheck /><strong>{label("Verify", "تحقق")}</strong></section></div><p>{label("If one layer fails, another can still reduce harm.", "إذا فشلت طبقة، تستطيع أخرى الحد من الضرر.")}</p></figure>;
  if (visual === "zero-trust") return <figure className="edu-diagram unit2-diagram edu-zero-trust"><figcaption><Fingerprint />{label("Zero trust: verify each meaningful access request", "الثقة الصفرية: تحقق من كل طلب وصول مهم")}</figcaption><div><section><Laptop /><strong>{label("Person & device", "الشخص والجهاز")}</strong></section><i /><section className="verify"><Fingerprint /><strong>{label("Check identity, device, permission", "افحص الهوية والجهاز والصلاحية")}</strong></section><i /><section><Server /><strong>{label("Only needed resource", "المورد اللازم فقط")}</strong></section></div><p>{label("A network location alone is not proof that access is safe.", "موقع الشبكة وحده ليس دليلاً على أن الوصول آمن.")}</p></figure>;
  if (visual === "incident-flow") return <figure className="edu-diagram unit2-diagram edu-incident-flow"><figcaption><CircleAlert />{label("Incident response follows a deliberate sequence", "تتبع الاستجابة للحادث تسلسلاً مقصوداً")}</figcaption><ol>{[["Prepare", "استعد"], ["Detect", "اكتشف"], ["Contain", "احتوِ"], ["Eradicate", "استأصل"], ["Recover", "استعد"], ["Prevent", "امنع التكرار"]].map(([en, ar], index) => <li key={en}><span>{index + 1}</span><strong>{label(en, ar)}</strong>{index < 5 && <i />}</li>)}</ol><p>{label("Contain before removing the cause; remove the cause before restoring service.", "احتوِ قبل إزالة السبب؛ وأزل السبب قبل استعادة الخدمة.")}</p></figure>;
  if (visual === "risk-matrix") return <figure className="edu-diagram unit2-diagram edu-risk-matrix"><figcaption><CircleAlert />{label("Risk priority = impact × likelihood", "أولوية الخطر = الأثر × الاحتمال")}</figcaption><div className="risk-matrix-layout"><span className="axis-y">{label("Impact", "الأثر")}</span><div className="risk-matrix-cells">{[3, 2, 1].map((impact) => [1, 2, 3].map((likelihood) => <span key={`${impact}-${likelihood}`} data-level={impact * likelihood >= 6 ? "high" : impact * likelihood >= 3 ? "medium" : "low"}>{impact * likelihood}</span>))}</div><span className="axis-x">{label("Likelihood", "الاحتمال")}</span></div><p><strong>{label("High impact + high likelihood = act first", "أثر عالٍ + احتمال عالٍ = تصرف أولاً")}</strong></p></figure>;
  if (visual === "incident-signal") return <figure className="edu-diagram unit2-diagram edu-incident-signal"><figcaption><CircleAlert />{label("An incident needs a calm, evidence-preserving response", "يحتاج الحادث إلى استجابة هادئة تحافظ على الدليل")}</figcaption><ol><li><CircleAlert /><strong>{label("Harm or disruption appears", "يظهر ضرر أو تعطّل")}</strong></li><li><ClipboardCheck /><strong>{label("Record what is known", "سجل ما هو معروف")}</strong></li><li><ShieldCheck /><strong>{label("Protect people and systems", "احمِ الناس والأنظمة")}</strong></li><li><Users /><strong>{label("Begin a deliberate response", "ابدأ استجابة مقصودة")}</strong></li></ol></figure>;
  if (visual === "response-loop") return <figure className="edu-diagram unit2-diagram edu-response-loop"><figcaption><Repeat2 />{label("Response becomes prevention through learning", "تتحول الاستجابة إلى وقاية من خلال التعلم")}</figcaption><ol><li><ShieldCheck /><strong>{label("Contain and recover", "احتوِ واستعد")}</strong></li><li><ClipboardCheck /><strong>{label("Review evidence", "راجع الدليل")}</strong></li><li><Users /><strong>{label("Improve controls and practice", "حسّن الضوابط والتدريب")}</strong></li><li><Repeat2 /><strong>{label("Update future priorities", "حدّث الأولويات المستقبلية")}</strong></li></ol></figure>;
  return null;
}

function Unit3Diagram({ visual, locale }: { visual: CurriculumLesson["explanation"][number]["visual"]; locale: Locale }) {
  const label = (en: string, ar: string) => <DiagramLabel locale={locale} en={en} ar={ar} />;
  if (visual === "tiers") return <figure className="edu-diagram unit3-diagram edu-web-tiers"><figcaption><Network />{label("A web application has connected layers", "يتكون تطبيق الويب من طبقات مترابطة")}</figcaption><div className="web-tier-flow"><section className="tier-frontend"><Laptop /><strong>{label("Frontend", "الواجهة الأمامية")}</strong><small>{label("What people see and use", "ما يراه الناس ويستخدمونه")}</small></section><i /><section className="tier-backend"><Server /><strong>{label("Backend", "الواجهة الخلفية")}</strong><small>{label("Processes requests and rules", "يعالج الطلبات والقواعد")}</small></section><i /><section className="tier-database"><Database /><strong>{label("Database", "قاعدة البيانات")}</strong><small>{label("Stores organised records", "تخزن سجلات منظمة")}</small></section></div><p>{label("A search can travel from the visible interface to server logic and stored data, then back with a result.", "يمكن أن ينتقل البحث من الواجهة المرئية إلى منطق الخادم والبيانات المخزنة، ثم يعود بنتيجة.")}</p></figure>;
  if (visual === "service-cards") return <figure className="edu-diagram unit3-diagram edu-web-services"><figcaption><Smartphone />{label("Different services use the same application structure", "تستخدم خدمات مختلفة البنية نفسها للتطبيق")}</figcaption><div><section><FileText /><strong>{label("Learning portal", "بوابة تعلم")}</strong><small>{label("Lessons and results", "دروس ونتائج")}</small></section><section><ShoppingCart /><strong>{label("Online shop", "متجر إلكتروني")}</strong><small>{label("Products and orders", "منتجات وطلبات")}</small></section><section><Glasses /><strong>{label("Social service", "خدمة اجتماعية")}</strong><small>{label("Posts and messages", "منشورات ورسائل")}</small></section></div><p>{label("The purpose changes, but interfaces, server work, and stored information still need to cooperate.", "يتغير الغرض، لكن الواجهات وعمل الخادم والمعلومات المخزنة تحتاج دائماً إلى التعاون.")}</p></figure>;
  if (visual === "client-server") return <figure className="edu-diagram unit3-diagram edu-client-server"><figcaption><Network />{label("Client and server exchange messages", "يتبادل العميل والخادم الرسائل")}</figcaption><div><section><Laptop /><strong>{label("Client", "العميل")}</strong><small>{label("Browser or application", "متصفح أو تطبيق")}</small></section><div className="request-response"><span><Send />{label("Request", "طلب")}</span><i /><span><Send />{label("Response", "استجابة")}</span></div><section><Server /><strong>{label("Server", "الخادم")}</strong><small>{label("Processes a request", "يعالج طلباً")}</small></section></div><p>{label("The client asks; the server does the requested work and answers.", "يطلب العميل؛ وينفذ الخادم العمل المطلوب ثم يجيب.")}</p></figure>;
  if (visual === "protocol") return <figure className="edu-diagram unit3-diagram edu-protocol"><figcaption><ShieldCheck />{label("A shared protocol gives messages a clear meaning", "يمنح البروتوكول المشترك الرسائل معنى واضحاً")}</figcaption><div className="protocol-layout"><section className="protocol-card"><strong>HTTP</strong><span>{label("rules for web messages", "قواعد رسائل الويب")}</span></section><section className="protocol-card protected"><strong>HTTPS</strong><span>{label("HTTP with protected travel", "HTTP مع نقل محمي")}</span></section><section className="method-card"><b>GET</b><span>{label("retrieve", "استرجع")}</span></section><section className="method-card"><b>POST</b><span>{label("send", "أرسل")}</span></section></div><div className="status-code-strip"><span className="ok"><b>200</b>{label("success", "نجاح")}</span><span className="missing"><b>404</b>{label("not found", "غير موجود")}</span><span className="error"><b>500</b>{label("server error", "خطأ خادم")}</span></div></figure>;
  if (visual === "api-json") return <figure className="edu-diagram unit3-diagram edu-api-json"><figcaption><Server />{label("An API returns structured information", "تعيد API معلومات منظمة")}</figcaption><div className="api-route"><section><Laptop /><strong>{label("Web application", "تطبيق ويب")}</strong></section><i /><section className="api-contract"><Network /><strong>API</strong><small>{label("defined request and response", "طلب واستجابة محددان")}</small></section><i /><section><Cloud /><strong>{label("Weather service", "خدمة الطقس")}</strong></section></div><div className="json-card" dir="ltr" aria-label={tr(locale, "Example JSON data", "مثال لبيانات JSON")}><span>{"{"}</span><b>"city"</b>: <em>"Cairo"</em>, <b>"temperature"</b>: <em>30</em><span>{"}"}</span></div><p>{label("JSON uses labelled values so software can exchange data in a readable structure.", "يستخدم JSON قيماً مسماة حتى تتبادل البرامج البيانات في بنية قابلة للقراءة.")}</p></figure>;
  if (visual === "frontend-stack") return <figure className="edu-diagram unit3-diagram edu-frontend-stack"><figcaption><Code2 />{label("The frontend combines structure, appearance, and behaviour", "تجمع الواجهة الأمامية بين البنية والمظهر والسلوك")}</figcaption><div><section className="stack-html"><FileText /><strong>HTML</strong><small>{label("structure", "البنية")}</small></section><section className="stack-css"><Sparkles /><strong>CSS</strong><small>{label("appearance", "المظهر")}</small></section><section className="stack-js"><Cpu /><strong>JavaScript</strong><small>{label("behaviour", "السلوك")}</small></section></div><p>{label("Each layer has a distinct job; together they make a page useful.", "لكل طبقة وظيفة مميزة؛ ومعاً تجعل الصفحة مفيدة.")}</p></figure>;
  if (visual === "semantic") return <figure className="edu-diagram unit3-diagram edu-semantic-page"><figcaption><FileText />{label("Semantic HTML names meaningful page regions", "يسمي HTML الدلالي مناطق الصفحة ذات المعنى")}</figcaption><div className="semantic-sheet"><header><b>&lt;header&gt;</b><span>{label("site identity", "هوية الموقع")}</span></header><nav><b>&lt;nav&gt;</b><span>{label("main links", "الروابط الرئيسية")}</span></nav><main><b>&lt;main&gt;</b><span>{label("main lesson or article", "الدرس أو المقال الرئيسي")}</span></main><footer><b>&lt;footer&gt;</b><span>{label("contact and copyright", "الاتصال وحقوق النشر")}</span></footer></div><p>{label("Meaningful regions support navigation for screen-reader users and clearer content understanding.", "تدعم المناطق ذات المعنى التنقل لمستخدمي قارئ الشاشة وفهماً أوضح للمحتوى.")}</p></figure>;
  if (visual === "responsive") return <figure className="edu-diagram unit3-diagram edu-responsive"><figcaption><Smartphone />{label("Responsive design reflows for available space", "يعيد التصميم المتجاوب ترتيب العناصر حسب المساحة المتاحة")}</figcaption><div><section className="device-wide"><Laptop /><strong>{label("Desktop", "حاسوب")}</strong><span><i /><i /><i /></span></section><section className="device-mid"><FileText /><strong>{label("Tablet", "جهاز لوحي")}</strong><span><i /><i /></span></section><section className="device-small"><Smartphone /><strong>{label("Phone", "هاتف")}</strong><span><i /></span></section></div><p>{label("The information stays available while the layout becomes comfortable to read and use.", "تبقى المعلومات متاحة بينما يصبح التخطيط مريحاً للقراءة والاستخدام.")}</p></figure>;
  if (visual === "frameworks") return <figure className="edu-diagram unit3-diagram edu-frameworks"><figcaption><Code2 />{label("Frameworks offer reusable ways to organise frontend work", "توفر الأطر طرقاً قابلة لإعادة الاستخدام لتنظيم عمل الواجهة الأمامية")}</figcaption><div><section><strong>React</strong><small>{label("components", "مكونات")}</small></section><section><strong>Vue</strong><small>{label("interface building", "بناء الواجهات")}</small></section><section><strong>Next</strong><small>{label("web application framework", "إطار تطبيق ويب")}</small></section></div><p>{label("This course treats frameworks conceptually: they help teams organise common interface work, but they do not replace accessibility or thoughtful design.", "يتناول المقرر الأطر مفاهيمياً: فهي تساعد الفرق على تنظيم عمل الواجهات الشائع، لكنها لا تستبدل إمكانية الوصول أو التصميم المتأني.")}</p></figure>;
  if (visual === "master-flow") return <figure className="edu-diagram unit3-diagram edu-master-flow"><figcaption><Network />{label("Unit 3 master flow: from a person’s action to a usable result", "المسار الرئيسي للوحدة 3: من فعل الشخص إلى نتيجة قابلة للاستخدام")}</figcaption><ol>{[[Laptop, "Person uses frontend", "يستخدم الشخص الواجهة الأمامية"], [Send, "Request travels", "ينتقل الطلب"], [Server, "Backend processes", "تعالج الواجهة الخلفية"], [Database, "Data or API responds", "تستجيب البيانات أو API"], [FileText, "Frontend displays result", "تعرض الواجهة الأمامية النتيجة"]].map(([Icon, en, ar], index) => { const Component = Icon as typeof Laptop; return <li key={en as string}><span><Component /></span><strong>{label(en as string, ar as string)}</strong>{index < 4 && <i />}</li>; })}</ol></figure>;
  return null;
}

function KeyRoundIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="8" cy="15" r="4" fill="none" stroke="currentColor" strokeWidth="1.8" /><path d="m11 12 8-8m-3 0h3v3m-7 7 3 3" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function ScaleIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v18M5 7h14M7 7l-3 6h6L7 7Zm10 0-3 6h6l-3-6Z" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>; }

function Unit4Diagram({ visual, locale }: { visual: CurriculumLesson["explanation"][number]["visual"]; locale: Locale }) {
  const label = (en: string, ar: string) => tr(locale, en, ar);
  const card = (Icon: typeof Users, en: string, ar: string, detailEn: string, detailAr: string) => <section><Icon /><strong>{label(en, ar)}</strong><small>{label(detailEn, detailAr)}</small></section>;
  if (visual === "media-map") return <figure className="edu-diagram unit4-diagram edu-media-map"><figcaption><Network />{label("Choose a medium by its communication role", "اختر الوسيط بحسب دوره الاتصالي")}</figcaption><div>{card(Volume2, "TV, radio, newspaper", "التلفاز والإذاعة والصحيفة", "mainly one-way", "أحادي الاتجاه أساسًا")}<i />{card(Users, "SNS", "الشبكات الاجتماعية", "reply, share, interact", "رد ومشاركة وتفاعل")}<i />{card(Laptop, "Website", "الموقع الإلكتروني", "information + optional forms", "معلومات + نماذج اختيارية")}</div><p>{label("Purpose + audience access → a reasoned media choice", "الغرض + وصول الجمهور ← اختيار مبرر للوسيط")}</p></figure>;
  if (visual === "media-compare") return <figure className="edu-diagram unit4-diagram edu-media-compare"><figcaption><Volume2 />{label("Different media have different useful roles", "للوسائط المختلفة أدوار مفيدة مختلفة")}</figcaption><div>{card(Volume2, "TV", "التلفاز", "reach", "انتشار")}{card(Volume2, "Radio", "الإذاعة", "listen", "استماع")}{card(FileText, "Newspaper", "الصحيفة", "read", "قراءة")}{card(Laptop, "Website", "الموقع", "detail", "تفاصيل")}{card(Users, "SNS", "الشبكات", "share", "مشاركة")}</div><p>{label("No single medium is best for every message.", "لا يوجد وسيط واحد هو الأفضل لكل رسالة.")}</p></figure>;
  if (visual === "website-balance") return <figure className="edu-diagram unit4-diagram edu-website-balance"><figcaption><Laptop />{label("A website: strengths and constraints", "الموقع الإلكتروني: مزايا وقيود")}</figcaption><div><section><h3>{label("Strengths", "المزايا")}</h3><ul><li>{label("Detailed and updateable", "مفصل وقابل للتحديث")}</li><li>{label("Combines media", "يجمع الوسائط")}</li><li>{label("Can support interaction", "يمكنه دعم التفاعل")}</li></ul></section><section><h3>{label("Constraints", "القيود")}</h3><ul><li>{label("Needs access and a device", "يحتاج وصولًا وجهازًا")}</li><li>{label("Visitor must open it", "يجب أن يفتحه الزائر")}</li><li>{label("Loading can vary", "قد يختلف التحميل")}</li></ul></section></div></figure>;
  if (visual === "media-plan") return <figure className="edu-diagram unit4-diagram edu-media-plan"><figcaption><Send />{label("A media mix gives each channel a job", "يعطي مزيج الوسائط كل قناة وظيفة")}</figcaption><ol><li><Users /><strong>SNS</strong><span>{label("attract attention", "يجذب الانتباه")}</span></li><i /><li><Laptop /><strong>{label("Website", "الموقع")}</strong><span>{label("give full details", "يقدم التفاصيل الكاملة")}</span></li><i /><li><Send /><strong>{label("Email", "البريد")}</strong><span>{label("send a reminder", "يرسل تذكيرًا")}</span></li></ol></figure>;
  if (visual === "persona") return <figure className="edu-diagram unit4-diagram edu-persona"><figcaption><Users />{label("A persona makes a target user concrete", "تجعل شخصية المستخدم المستخدم المستهدف ملموسًا")}</figcaption><section><div className="persona-avatar"><UserRoundCheck /></div><div><strong>{label("Mariam, parent", "مريم، ولية أمر")}</strong><span>{label("Phone • short work break", "هاتف • استراحة عمل قصيرة")}</span></div></section><dl><div><dt>{label("Goal", "الهدف")}</dt><dd>{label("Find opening hours", "إيجاد ساعات العمل")}</dd></div><div><dt>{label("Challenge", "التحدي")}</dt><dd>{label("Little time, small screen", "وقت قليل وشاشة صغيرة")}</dd></div></dl><p>{label("Priority: make essential information quick to find.", "الأولوية: اجعل المعلومات الأساسية سريعة العثور عليها.")}</p></figure>;
  if (visual === "wireframe") return <figure className="edu-diagram unit4-diagram edu-wireframe"><figcaption><Palette />{label("Wireframe: information and priority before decoration", "مخطط هيكلي: معلومات وأولوية قبل الزينة")}</figcaption><div className="wireframe-sheet"><header>{label("Community clinic", "عيادة المجتمع")}</header><section>{label("Emergency contact · Appointment", "اتصال الطوارئ · حجز موعد")}</section><div><span>{label("Opening hours", "ساعات العمل")}</span><span>{label("Services", "الخدمات")}</span></div><footer>{label("Directions", "الاتجاهات")}</footer></div><p>{label("This is a layout blueprint, not a final coloured page.", "هذا مخطط للتخطيط وليس صفحة ملونة نهائية.")}</p></figure>;
  if (visual === "crap") return <figure className="edu-diagram unit4-diagram edu-crap"><figcaption><Palette />{label("CRAP makes information relationships clearer", "تجعل مبادئ CRAP علاقات المعلومات أوضح")}</figcaption><div>{[["C", "Contrast", "التباين", "show priority", "إظهار الأولوية"], ["R", "Repetition", "التكرار", "stay consistent", "حافظ على الاتساق"], ["A", "Alignment", "المحاذاة", "create order", "اصنع نظامًا"], ["P", "Proximity", "التقارب", "group related items", "اجمع العناصر المرتبطة"]].map(([letter, en, ar, detailEn, detailAr]) => <section key={letter}><b>{letter}</b><strong>{label(en, ar)}</strong><small>{label(detailEn, detailAr)}</small></section>)}</div></figure>;
  if (visual === "user-flow") return <figure className="edu-diagram unit4-diagram edu-user-flow"><figcaption><UserRoundCheck />{label("User-centered design asks what people need", "يسأل التصميم المتمحور حول المستخدم عما يحتاجه الناس")}</figcaption><ol><li><Users />{label("Understand user", "افهم المستخدم")}</li><i /><li><Users />{label("Persona", "شخصية مستخدم")}</li><i /><li><Palette />{label("Wireframe", "مخطط هيكلي")}</li><i /><li><CheckCircle2 />{label("Design decisions", "قرارات التصميم")}</li><i /><li><UserRoundCheck />{label("Usable + accessible", "سهل الاستخدام ومتاح")}</li></ol><p>{label("Usability: easy and efficient. Accessibility: usable by a wide range of people.", "سهولة الاستخدام: سهل وفعال. إمكانية الوصول: قابل للاستخدام لنطاق واسع من الناس.")}</p></figure>;
  if (visual === "evidence-split") return <figure className="edu-diagram unit4-diagram edu-evidence-split"><figcaption><ClipboardCheck />{label("Two kinds of evidence answer different questions", "نوعان من الأدلة يجيبان عن أسئلة مختلفة")}</figcaption><div>{card(BarChart3, "Quantitative", "كمي", "How much? Numbers", "كم؟ أرقام")}{card(Users, "Qualitative", "نوعي", "Why? Feedback and observation", "لماذا؟ تغذية راجعة وملاحظة")}</div></figure>;
  if (visual === "metrics") return <figure className="edu-diagram unit4-diagram edu-metrics"><figcaption><BarChart3 />{label("Three basic ways to read use of a page", "ثلاث طرق أساسية لقراءة استخدام صفحة")}</figcaption><div><section><b>PV</b><strong>{label("Page views", "مشاهدات الصفحة")}</strong><small>{label("How many times viewed", "كم مرة شوهدت")}</small></section><section><b>BR</b><strong>{label("Bounce rate", "معدل الارتداد")}</strong><small>{label("Leaves after first page", "يغادر بعد الصفحة الأولى")}</small></section><section><b>CVR</b><strong>{label("Conversion rate", "معدل التحويل")}</strong><small>{label("Completes target action", "يكمل الإجراء المستهدف")}</small></section></div><p>{label("Numbers find patterns, not automatic reasons.", "تكشف الأرقام أنماطًا لا أسبابًا تلقائية.")}</p></figure>;
  if (visual === "heuristics") return <figure className="edu-diagram unit4-diagram edu-heuristics"><figcaption><ClipboardCheck />{label("Heuristic evaluation: practical interface checks", "التقييم الاستدلالي: فحوص واجهة عملية")}</figcaption><div>{card(Repeat2, "Consistency", "الاتساق", "same labels and behavior", "التسميات والسلوك نفسه")}{card(ShieldCheck, "Error prevention", "منع الأخطاء", "avoid likely mistakes", "تجنب الأخطاء المحتملة")}{card(CircleAlert, "System status", "حالة النظام", "show loading or confirmation", "أظهر التحميل أو التأكيد")}</div></figure>;
  if (visual === "evidence-loop") return <figure className="edu-diagram unit4-diagram edu-evidence-loop"><figcaption><Repeat2 />{label("Evidence guides a focused next question", "توجه الأدلة السؤال التالي المركز")}</figcaption><ol><li><BarChart3 />{label("Numbers show a pattern", "الأرقام تظهر نمطًا")}</li><i /><li><Users />{label("Users help explain why", "المستخدمون يساعدون في تفسير السبب")}</li><i /><li><ClipboardCheck />{label("Check interface issues", "افحص مشكلات الواجهة")}</li><i /><li><Repeat2 />{label("Choose one improvement", "اختر تحسينًا واحدًا")}</li></ol></figure>;
  if (visual === "pdca") return <figure className="edu-diagram unit4-diagram edu-pdca"><figcaption><Repeat2 />{label("PDCA is a repeated improvement cycle", "PDCA دورة تحسين متكررة")}</figcaption><ol>{[["P", "Plan", "خطط", "goal + one change", "هدف + تغيير واحد"], ["D", "Do", "نفذ", "implement", "طبق"], ["C", "Check", "تحقق", "measure result", "قس النتيجة"], ["A", "Act", "تصرف", "keep or refine", "أبقِ أو حسّن"]].map(([letter, en, ar, detailEn, detailAr]) => <li key={letter}><b>{letter}</b><strong>{label(en, ar)}</strong><span>{label(detailEn, detailAr)}</span></li>)}</ol><p>{label("Act leads back to the next Plan.", "يؤدي التصرف إلى التخطيط التالي.")}</p></figure>;
  if (visual === "design-thinking") return <figure className="edu-diagram unit4-diagram edu-design-thinking"><figcaption><Users />{label("Design Thinking solves a user problem step by step", "يحل التفكير التصميمي مشكلة مستخدم خطوة بخطوة")}</figcaption><ol>{[["1", "Empathize", "فهم المستخدم"], ["2", "Define", "تحديد المشكلة"], ["3", "Ideate", "توليد الأفكار"], ["4", "Prototype", "نموذج أولي"], ["5", "Test", "اختبار"]].map(([number, en, ar]) => <li key={number}><b>{number}</b><strong>{label(en, ar)}</strong></li>)}</ol><p>{label("Testing can take the team back to an earlier step.", "يمكن للاختبار أن يعيد الفريق إلى خطوة سابقة.")}</p></figure>;
  if (visual === "ab-test") return <figure className="edu-diagram unit4-diagram edu-ab-test"><figcaption><BarChart3 />{label("A/B test: one change, then compare data", "اختبار A/B: تغيير واحد ثم مقارنة البيانات")}</figcaption><div><section><b>A</b><strong>{label("Register", "سجل")}</strong><span>32 / 100</span></section><section><b>B</b><strong>{label("Join Event", "انضم إلى الفعالية")}</strong><span>47 / 100</span></section></div><p>{label("Only the button label changed, so the difference is interpretable.", "تغيرت تسمية الزر فقط، لذا يمكن تفسير الاختلاف.")}</p></figure>;
  if (visual === "unit4-master") return <figure className="edu-diagram unit4-diagram edu-unit4-master"><figcaption><Repeat2 />{label("Unit 4 master flow", "المسار الرئيسي للوحدة ٤")}</figcaption><ol>{[[Users, "Purpose + audience", "الغرض + الجمهور"], [Network, "Choose media", "اختر الوسائط"], [UserRoundCheck, "Understand user", "افهم المستخدم"], [Palette, "Plan and design clearly", "خطط وصمم بوضوح"], [BarChart3, "Evaluate with evidence", "قيّم بالأدلة"], [Repeat2, "Improve and repeat", "حسّن وكرر"]].map(([Icon, en, ar], index) => { const Component = Icon as typeof Users; return <li key={en as string}><span><Component /></span><strong>{label(en as string, ar as string)}</strong>{index < 5 && <i />}</li>; })}</ol></figure>;
  return null;
}

function ConceptVisual({ visual, locale }: { visual: CurriculumLesson["explanation"][number]["visual"]; locale: Locale }) {
  const label = (en: string, ar: string) => tr(locale, en, ar);
  const educationalDiagram = Unit1Diagram({ visual, locale });
  if (educationalDiagram) return educationalDiagram;
  const unit2Diagram = Unit2Diagram({ visual, locale });
  if (unit2Diagram) return unit2Diagram;
  const unit3Diagram = Unit3Diagram({ visual, locale });
  if (unit3Diagram) return unit3Diagram;
  const unit4Diagram = Unit4Diagram({ visual, locale });
  if (unit4Diagram) return unit4Diagram;
  if (visual === "timeline") return <div className="concept-visual timeline" role="img" aria-label={label("Information technology timeline", "خط زمني لتكنولوجيا المعلومات")}><span>1940s</span><i /> <span>PC</span><i /> <span>Web</span><i /> <span>Mobile</span><i /> <span>Cloud</span></div>;
  if (visual === "moore") return <div className="concept-visual moore" role="img" aria-label={label("More transistors, greater capability", "ترانزستورات أكثر وقدرة أكبر")}><span>●</span><span>●●●</span><span>●●●●●</span><b>↑</b></div>;
  if (visual === "edge") return <div className="concept-visual edge" role="img" aria-label={label("Cloud versus edge processing", "مقارنة المعالجة السحابية والطرفية")}><span>{label("Vehicle", "مركبة")} → ☁ → {label("Decision", "قرار")}</span><strong>{label("Sensors → local decision", "مستشعرات ← قرار محلي")}</strong></div>;
  if (visual === "arvr") return <div className="concept-visual split" role="img" aria-label={label("AR and VR comparison", "مقارنة AR وVR")}><span>AR<br /><small>{label("adds", "يضيف")}</small></span><span>VR<br /><small>{label("immerses", "يغمر")}</small></span></div>;
  if (visual === "hierarchy") return <div className="concept-visual hierarchy" role="img" aria-label={label("AI hierarchy", "تسلسل الذكاء الاصطناعي")}><span>AI</span><span>ML</span><span>DL</span><span>GenAI</span></div>;
  if (visual === "rules") return <div className="concept-visual split" role="img" aria-label={label("Rules compared with learning from data", "مقارنة القواعد بالتعلم من البيانات")}><span>{label("Written rules", "قواعد مكتوبة")}</span><span>{label("Data → pattern", "بيانات ← نمط")}</span></div>;
  if (visual === "neural") return <div className="concept-visual neural" role="img" aria-label={label("Conceptual neural network", "شبكة عصبية مفاهيمية")}><span>● ● ●</span><i>→</i><span>● ●</span><i>→</i><span>●</span></div>;
  if (visual === "generative") return <div className="concept-visual generative" role="img" aria-label={label("Generative AI outputs", "مخرجات الذكاء الاصطناعي التوليدي")}><span>Text</span><span>Image</span><span>Audio</span><span>Code</span></div>;
  if (visual === "everyday" || visual === "industry") return <div className="concept-visual cards" aria-hidden="true"><span>⌕</span><span>◉</span><span>↗</span></div>;
  if (visual === "bias") return <div className="concept-visual bias" role="img" aria-label={label("Bias flow", "تدفق التحيز")}><span>{label("Data or design", "بيانات أو تصميم")}</span><i>↓</i><span>AI</span><i>↓</i><span>{label("Impact", "أثر")}</span></div>;
  if (visual === "xai") return <div className="concept-visual split" role="img" aria-label={label("Black box and explainable AI", "الصندوق الأسود والذكاء القابل للتفسير")}><span>{label("Black box", "صندوق أسود")}<small>?</small></span><span>XAI<small>✓</small></span></div>;
  if (visual === "ethics") return <div className="concept-visual ethics" role="img" aria-label={label("Four AI ethics principles", "مبادئ أخلاقيات الذكاء الاصطناعي الأربعة")}><span>{label("Fair", "إنصاف")}</span><span>{label("Clear", "شفاف")}</span><span>{label("Private", "خاص")}</span><span>{label("Accountable", "مساءل")}</span></div>;
  return <div className={`concept-visual ${visual}`} aria-hidden="true"><span /><span /><span /></div>;
}

export function LessonPlayer({ lesson, locale }: { lesson: CurriculumLesson; locale: Locale }) {
  const storageKey = `curriculum-v2:${lesson.id}`;
  const lessonSteps = useMemo(() => stepsForLesson(lesson), [lesson]);
  const [state, setState] = useState<Stored>(initialStored);
  const [ready, setReady] = useState(false);
  const [downloaded, setDownloaded] = useState(false);
  useEffect(() => {
    const saved = localStorage.getItem(storageKey);
    let restored: Stored = initialStored();
    if (saved) { try { const parsed = JSON.parse(saved) as Partial<Stored>; restored = { ...initialStored(), ...parsed, completedActivities: parsed.completedActivities ?? [], reviewMistakes: parsed.reviewMistakes ?? [], reviewAnswers: parsed.reviewAnswers ?? {}, reviewOrders: parsed.reviewOrders ?? {} }; } catch { /* use defaults */ } }
    const requestedStep = window.location.hash.slice(1) as Step;
    if (lessonSteps.some((item) => item.id === requestedStep)) restored = { ...restored, step: requestedStep };
    setState(restored);
    setReady(true);
  }, [lessonSteps, storageKey]);
  useEffect(() => { if (ready) localStorage.setItem(storageKey, JSON.stringify(state)); }, [ready, state, storageKey]);
  useEffect(() => { if (ready) touchLessonProgress(lesson.slug); }, [lesson.slug, ready, state.step]);
  const questionCorrect = (question: CurriculumQuestion) => question.type === "short" ? Boolean(state.answers[question.id]?.trim()) : question.type === "cloze" ? state.answers[question.id]?.trim().toLocaleLowerCase() === question.answer.toLocaleLowerCase() : state.answers[question.id] === question.answer;
  const quizScore = useMemo(() => lesson.quiz.filter(questionCorrect).length, [lesson.quiz, state.answers]);
  const practiceMistakes = useMemo<LocalLessonMistake[]>(() => lesson.unit === 4 ? lesson.practice.filter((question) => !questionCorrect(question)).map((question) => ({ id: `${lesson.slug}:practice:${question.id}`, questionId: question.id, question: question.prompt, learnerAnswer: state.answers[question.id] ?? "", correctAnswer: question.answer, explanation: question.explanation, source: "practice" })) : [], [lesson.practice, lesson.slug, lesson.unit, state.answers]);
  const quizMistakes = useMemo<LocalLessonMistake[]>(() => lesson.quiz.filter((question) => !questionCorrect(question)).map((question) => ({ id: `${lesson.slug}:${question.id}`, questionId: question.id, question: question.prompt, learnerAnswer: state.answers[question.id] ?? "", correctAnswer: question.answer, explanation: question.explanation, source: "quiz" })), [lesson.quiz, lesson.slug, state.answers]);
  const completedBlocks = (overrides?: Partial<Stored>, includeQuiz = false, includeReview = false) => {
    const current = { ...state, ...overrides };
    return [...lesson.practice.map((question) => question.id), ...current.completedActivities, ...(current.challengeCompleted && lesson.challenge ? [lesson.challenge.id] : []), ...(includeQuiz || current.quizSubmitted ? lesson.quiz.map((question) => question.id) : []), ...(includeReview || current.reviewSubmitted ? ["unit-review"] : [])];
  };
  const progressDetails = (overrides?: Partial<Stored>) => {
    const current = { ...state, ...overrides };
    return { mistakes: [...(lesson.unit === 4 && current.solutions ? practiceMistakes : []), ...(current.quizSubmitted ? quizMistakes : []), ...current.reviewMistakes], ...(typeof current.reviewScore === "number" && lesson.unitReview ? { unitReview: { score: current.reviewScore, total: lesson.unitReview.questions.length } } : {}) };
  };
  const setAnswer = (id: string, answer: string) => setState((current) => ({ ...current, answers: { ...current.answers, [id]: answer } }));
  const move = (step: Step) => setState((current) => ({ ...current, step }));
  const showSolutions = () => { setState((current) => ({ ...current, solutions: true, step: "solutions" })); writeLessonProgress(lesson.slug, completedBlocks(), state.quizSubmitted ? quizScore : undefined, progressDetails({ solutions: true })); };
  const completeActivity = (id: string) => { const completedActivities = [...new Set([...state.completedActivities, id])]; setState((current) => ({ ...current, completedActivities })); writeLessonProgress(lesson.slug, completedBlocks({ completedActivities }), state.quizSubmitted ? quizScore : undefined, progressDetails({ completedActivities })); };
  const completeChallenge = () => { setState((current) => ({ ...current, challengeCompleted: true })); writeLessonProgress(lesson.slug, completedBlocks({ challengeCompleted: true }), state.quizSubmitted ? quizScore : undefined, progressDetails({ challengeCompleted: true })); };
  const submitQuiz = () => { setState((current) => ({ ...current, quizSubmitted: true })); writeLessonProgress(lesson.slug, completedBlocks({ quizSubmitted: true }, true), quizScore, progressDetails()); };
  const submitUnitReview = (result: { score: number; total: number; mistakes: SavedUnit2Mistake[]; answers: Record<string, string>; orders: Record<string, string[]> }) => { const reviewMistakes = result.mistakes; const reviewScore = result.score; const reviewAnswers = result.answers; const reviewOrders = result.orders; setState((current) => ({ ...current, reviewSubmitted: true, reviewScore, reviewMistakes, reviewAnswers, reviewOrders })); writeLessonProgress(lesson.slug, completedBlocks({ reviewSubmitted: true }, state.quizSubmitted, true), state.quizSubmitted ? quizScore : undefined, progressDetails({ reviewSubmitted: true, reviewScore, reviewMistakes })); };
  const retry = () => setState((current) => ({ ...current, quizSubmitted: false, answers: Object.fromEntries(Object.entries(current.answers).filter(([id]) => !id.startsWith("quiz-"))) }));
  const download = async () => { const urls = [`/${locale}/learn/${lesson.slug}`, `/${locale === "en" ? "ar" : "en"}/learn/${lesson.slug}`, `/api/v1/lessons/${lesson.slug}`]; const result = await cacheLessonUrls(urls); setDownloaded(result.ok); };
  const activeIndex = lessonSteps.findIndex((item) => item.id === state.step);
  return <main id="main-content" className="page shell curriculum-player">
    <div className="inner-page-head">
      <Link className="breadcrumb" href={`/${locale}/dashboard#curriculum-progress`}><ChevronLeft className="flip-rtl" size={17} />{tr(locale, "My curriculum", "منهجي")} · {tr(locale, `Unit ${lesson.unit}`, `الوحدة ${lesson.unit}`)}</Link>
      <button className="button ghost small" type="button" onClick={() => void download()}><Download size={16} />{downloaded ? tr(locale, "Saved offline", "حُفظ دون اتصال") : tr(locale, "Download", "تنزيل")}</button>
    </div>
    <header className="lesson-hero panel">
      <span className="eyebrow">{lesson.number} · {tr(locale, "Part 1", "الجزء الأول")}</span><h1>{pick(locale, lesson.title)}</h1><p>{pick(locale, lesson.summary)}</p>
      <div className="objective-pills">{lesson.objectives.map((objective, index) => <span key={index}><CheckCircle2 size={15} />{pick(locale, objective)}</span>)}</div>
      <small>{tr(locale, "Original learning content mapped to source pages", "محتوى تعليمي أصلي مرتبط بصفحات المصدر")} {lesson.sourcePages}</small>
    </header>
    <nav className="lesson-stepper" style={{ "--step-count": lessonSteps.length } as CSSProperties} aria-label={tr(locale, "Lesson sections", "أقسام الدرس")}>{lessonSteps.map((item, index) => <button key={item.id} className={state.step === item.id ? "active" : index < activeIndex ? "complete" : ""} data-state={state.step === item.id ? "current" : index < activeIndex ? "complete" : "upcoming"} onClick={() => move(item.id)}><span>{index + 1}</span><strong>{tr(locale, item.en, item.ar)}</strong></button>)}</nav>
    <section className="curriculum-content">
      {state.step === "explanation" && <><div className="section-head"><div><span className="eyebrow">01</span><h2>{tr(locale, "Explanation", "الشرح")}</h2></div></div>{lesson.explanation.map((section, index) => <article className="panel explanation-card" key={index}><ConceptVisual visual={section.visual} locale={locale} /><div><h2>{pick(locale, section.title)}</h2>{pick(locale, section.body).split("\n\n").map((paragraph, paragraphIndex) => <p key={paragraphIndex}>{paragraph}</p>)}</div></article>)}</>}
      {state.step === "summary" && <><div className="section-head"><div><span className="eyebrow">02</span><h2>{tr(locale, "Summary", "الملخص")}</h2><p>{tr(locale, "Review the essential ideas before you practise.", "راجع الأفكار الأساسية قبل التدريب.")}</p></div></div>{lesson.summaryPoints && <article className="panel summary-points"><ul>{lesson.summaryPoints.map((point, index) => <li key={index}>{pick(locale, point)}</li>)}</ul></article>}<div className="term-grid">{lesson.keyTerms.map((term, index) => <article className="panel term-card" key={index}><span>{index + 1}</span><h3>{pick(locale, term.term)}</h3><p>{pick(locale, term.definition)}</p></article>)}</div><article className="takeaway-card"><Sparkles /><div><strong>{tr(locale, "Key takeaway", "الخلاصة")}</strong><p>{pick(locale, lesson.takeaway)}</p></div></article></>}
      {state.step === "practice" && <><div className="section-head"><div><span className="eyebrow">03</span><h2>{tr(locale, "Practice Questions", "أسئلة التدريب")}</h2><p>{tr(locale, "Try the questions and interactions first. Your work is saved on this device.", "أجب عن الأسئلة وجرّب الأنشطة التفاعلية أولًا. يُحفظ عملك على هذا الجهاز.")}</p></div></div><div className="question-stack">{lesson.practice.map(q => <Question key={q.id} question={q} locale={locale} value={state.answers[q.id]} onChange={(answer) => setAnswer(q.id, answer)} />)}</div>{lesson.activities?.map((activity) => lesson.unit === 4 ? <Unit4ActivityRenderer key={activity.id} activity={activity} locale={locale} complete={state.completedActivities.includes(activity.id)} onComplete={completeActivity} /> : lesson.unit === 3 ? <Unit3ActivityRenderer key={activity.id} activity={activity} locale={locale} complete={state.completedActivities.includes(activity.id)} onComplete={completeActivity} /> : <Unit2ActivityRenderer key={activity.id} activity={activity} locale={locale} complete={state.completedActivities.includes(activity.id)} onComplete={completeActivity} />)}<button className="button" type="button" onClick={showSolutions}><Lightbulb size={18} />{tr(locale, "Show Solutions", "إظهار الحلول")}</button></>}
      {state.step === "solutions" && <><div className="section-head"><div><span className="eyebrow">04</span><h2>{tr(locale, "Solutions", "الحلول")}</h2><p>{tr(locale, "Compare your reasoning with the model explanations.", "قارن تفكيرك بالتفسيرات النموذجية.")}</p></div></div>{!state.solutions ? <article className="panel empty-state"><LockKeyhole /><p>{tr(locale, "Complete a first attempt, then choose Show Solutions.", "أكمل المحاولة الأولى ثم اختر إظهار الحلول.")}</p></article> : <div className="question-stack">{lesson.practice.map(q => <Question key={q.id} question={q} locale={locale} value={state.answers[q.id]} onChange={(answer) => setAnswer(q.id, answer)} reveal />)}</div>}</>}
      {state.step === "quiz" && <><div className="section-head"><div><span className="eyebrow">05</span><h2>{tr(locale, "Quiz", "الاختبار")}</h2><p>{tr(locale, "Ten questions. Submit once you have made your best attempt.", "عشرة أسئلة. أرسل إجاباتك بعد أفضل محاولة.")}</p></div></div><div className="question-stack">{lesson.quiz.map(q => <Question key={q.id} question={q} locale={locale} value={state.answers[q.id]} onChange={(answer) => setAnswer(q.id, answer)} reveal={state.quizSubmitted} locked={state.quizSubmitted} />)}</div>{state.quizSubmitted ? <article className="quiz-result panel"><ListChecks /><h2>{quizScore}/{lesson.quiz.length}</h2><p>{tr(locale, "Your score. Read each explanation, then retry if you want more practice.", "نتيجتك. اقرأ شرح كل إجابة ثم أعد المحاولة إذا أردت تدريبًا أكثر.")}</p><button className="button secondary" onClick={retry}><RotateCcw size={18} />{tr(locale, "Try Again", "حاول مرة أخرى")}</button></article> : <button className="button" type="button" onClick={submitQuiz}>{tr(locale, "Submit Quiz", "إرسال الاختبار")}<ChevronRight className="flip-rtl" size={18} /></button>}</>}
      {state.step === "challenge" && lesson.challenge && <><div className="section-head"><div><span className="eyebrow">06</span><h2>{tr(locale, "Engineer Challenge", "تحدي المهندس")}</h2><p>{lesson.unit === 4 ? tr(locale, "Make and justify a user-focused web and media decision. Pair discussion happens in person; your conclusion remains your own.", "اتخذ قرارًا متمحورًا حول المستخدم للويب والوسائط وبرره. يحدث النقاش الثنائي حضوريًا؛ وتبقى خلاصتك خاصة بك.") : lesson.unit === 3 ? tr(locale, "Make and justify a web-application design decision. Pair discussion happens in person; your conclusion remains your own.", "اتخذ قراراً تصميمياً لتطبيق ويب وبرره. يحدث النقاش الثنائي حضورياً؛ وتبقى خلاصتك خاصة بك.") : lesson.unit === 1 ? tr(locale, "Design a useful school AI service and justify the data, safeguards, and human responsibility. Pair discussion happens in person; your conclusion remains your own.", "صمم خدمة ذكاء اصطناعي مدرسية مفيدة وبرر البيانات والضمانات والمسؤولية البشرية. يحدث النقاش الثنائي حضوريًا؛ وتبقى خلاصتك خاصة بك.") : tr(locale, "Make and justify a security decision. Pair discussion happens in person; your conclusion remains your own.", "اتخذ قراراً أمنياً وبرره. يحدث النقاش الثنائي حضورياً؛ وتبقى خلاصتك خاصة بك.")}</p></div></div>{lesson.unit === 4 ? <Unit4Challenge challenge={lesson.challenge} reflection={lesson.reflection} locale={locale} complete={state.challengeCompleted} onComplete={completeChallenge} reflectionValue={state.reflection} onReflectionChange={(reflection) => setState((current) => ({ ...current, reflection }))} /> : lesson.unit === 3 ? <Unit3Challenge challenge={lesson.challenge} reflection={lesson.reflection} locale={locale} complete={state.challengeCompleted} onComplete={completeChallenge} reflectionValue={state.reflection} onReflectionChange={(reflection) => setState((current) => ({ ...current, reflection }))} /> : lesson.unit === 1 ? <Unit1Challenge challenge={lesson.challenge} reflection={lesson.reflection} locale={locale} complete={state.challengeCompleted} onComplete={completeChallenge} reflectionValue={state.reflection} onReflectionChange={(reflection) => setState((current) => ({ ...current, reflection }))} /> : <Unit2Challenge challenge={lesson.challenge} reflection={lesson.reflection} locale={locale} complete={state.challengeCompleted} onComplete={completeChallenge} reflectionValue={state.reflection} onReflectionChange={(reflection) => setState((current) => ({ ...current, reflection }))} />}</>}
      {state.step === "unit-review" && lesson.unitReview && <Unit2FinalReview review={lesson.unitReview} locale={locale} submitted={state.reviewSubmitted} storedScore={state.reviewScore} initialAnswers={state.reviewAnswers} initialOrders={state.reviewOrders} onSubmit={submitUnitReview} />}
    </section>
    <div className="lesson-next"><button className="button ghost" disabled={activeIndex === 0} onClick={() => move(lessonSteps[activeIndex - 1].id)}><ChevronLeft className="flip-rtl" />{tr(locale, "Previous", "السابق")}</button><button className="button ghost" disabled={activeIndex === lessonSteps.length - 1} onClick={() => move(lessonSteps[activeIndex + 1].id)}>{tr(locale, "Next", "التالي")}<ChevronRight className="flip-rtl" /></button></div>
  </main>;
}
