"use client";

import { ArrowDown, ArrowUp, BarChart3, CheckCircle2, CircleAlert, ClipboardCheck, MousePointerClick, Palette, Users } from "lucide-react";
import { useState, type ReactNode } from "react";
import type { LessonActivity, LessonChallenge } from "@/content/part1-curriculum";
import type { Locale, LocalizedText } from "@/lib/types";

const t = (locale: Locale, en: string, ar: string) => locale === "ar" ? ar : en;
const pick = (locale: Locale, value: LocalizedText) => value[locale];
const L = (en: string, ar: string): LocalizedText => ({ en, ar });

function ActivityFrame({ activity, locale, complete, children }: { activity: LessonActivity; locale: Locale; complete: boolean; children: ReactNode }) {
  return <article className="panel unit2-activity unit4-activity" data-complete={complete}>
    <div className="unit2-activity-heading"><span className="unit2-activity-icon"><Palette size={20} /></span><div><span className="eyebrow">{t(locale, "Interactive practice", "تدريب تفاعلي")}</span><h3>{pick(locale, activity.title)}</h3><p>{pick(locale, activity.instruction)}</p></div>{complete && <span className="completion-badge"><CheckCircle2 size={16} />{t(locale, "Completed", "مكتمل")}</span>}</div>
    {children}
  </article>;
}

function Status({ locale, success, children }: { locale: Locale; success: boolean; children: ReactNode }) {
  return <p className={`unit2-status ${success ? "success" : "warning"}`} role="status">{success ? <CheckCircle2 size={17} /> : <CircleAlert size={17} />}{children}</p>;
}

type SelectRow = { id: string; text: LocalizedText; answer: string };
function SelectMap({ locale, rows, options, button, success, retry, onComplete }: { locale: Locale; rows: SelectRow[]; options: Record<string, LocalizedText>; button: LocalizedText; success: LocalizedText; retry: LocalizedText; onComplete: () => void }) {
  const [values, setValues] = useState<Record<string, string>>({});
  const [checked, setChecked] = useState(false);
  const correct = rows.every((row) => values[row.id] === row.answer);
  return <div className="unit4-select-map"><div className="security-map-rows">{rows.map((row) => <label key={row.id}><span>{pick(locale, row.text)}</span><select value={values[row.id] ?? ""} onChange={(event) => { setValues((current) => ({ ...current, [row.id]: event.target.value })); setChecked(false); }}><option value="">{t(locale, "Choose", "اختر")}</option>{Object.entries(options).map(([id, name]) => <option key={id} value={id}>{pick(locale, name)}</option>)}</select>{checked && <small className={values[row.id] === row.answer ? "correct" : "incorrect"}>{values[row.id] === row.answer ? <CheckCircle2 size={14} /> : <CircleAlert size={14} />}{pick(locale, options[row.answer])}</small>}</label>)}</div><button className="button secondary" type="button" onClick={() => { setChecked(true); if (correct) onComplete(); }}>{pick(locale, button)}</button>{checked && <Status locale={locale} success={correct}>{pick(locale, correct ? success : retry)}</Status>}</div>;
}

function MediaDirection({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const rows: SelectRow[] = [
    { id: "tv", text: L("TV broadcast", "بث تلفزيوني"), answer: "one" }, { id: "radio", text: L("Radio announcement", "إعلان إذاعي"), answer: "one" },
    { id: "paper", text: L("Printed newspaper", "صحيفة مطبوعة"), answer: "one" }, { id: "sns", text: L("SNS post with replies and shares", "منشور على شبكة اجتماعية مع ردود ومشاركات"), answer: "two" }, { id: "site", text: L("Website with information and a contact form", "موقع بمعلومات ونموذج اتصال"), answer: "both" },
  ];
  return <SelectMap locale={locale} rows={rows} options={{ one: L("Mainly one-way", "أحادي الاتجاه أساسًا"), two: L("Two-way", "ثنائي الاتجاه"), both: L("Can support both", "يمكنه دعم الاثنين") }} button={L("Check communication patterns", "تحقق من أنماط الاتصال")} success={L("Correct. A website can mainly present information and also offer a route for response.", "صحيح. قد يعرض الموقع المعلومات أساسًا ويقدم أيضًا طريقًا للرد.")} retry={L("Think about whether the audience has a way to respond or interact.", "فكر هل يملك الجمهور طريقة للرد أو التفاعل.")} onComplete={onComplete} />;
}

function WebsiteBalance({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const rows: SelectRow[] = [
    { id: "update", text: L("Information can be updated when needed", "يمكن تحديث المعلومات عند الحاجة"), answer: "strength" }, { id: "detail", text: L("Can combine text, images, audio, and video", "يمكنه جمع النص والصور والصوت والفيديو"), answer: "strength" }, { id: "form", text: L("Can use a form to receive a question", "يمكنه استخدام نموذج لتلقي سؤال"), answer: "strength" },
    { id: "internet", text: L("A visitor normally needs Internet access", "يحتاج الزائر عادة إلى اتصال بالإنترنت"), answer: "constraint" }, { id: "visit", text: L("People usually need to choose to visit it", "يحتاج الناس عادة إلى اختيار زيارته"), answer: "constraint" }, { id: "load", text: L("Loading and display can vary by device or connection", "قد يختلف التحميل والعرض حسب الجهاز أو الاتصال"), answer: "constraint" },
  ];
  return <SelectMap locale={locale} rows={rows} options={{ strength: L("Strength", "ميزة"), constraint: L("Constraint", "قيد") }} button={L("Check the balance", "تحقق من التوازن")} success={L("Well balanced. A useful plan includes both what a website enables and what access can limit.", "توازن جيد. تتضمن الخطة المفيدة ما يتيحه الموقع وما قد يحده الوصول.")} retry={L("A strength is something the medium enables; a constraint is something a plan must account for.", "الميزة ما يتيحه الوسيط؛ والقيد ما يجب أن تراعيه الخطة.")} onComplete={onComplete} />;
}

function PurposeMatch({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const rows: SelectRow[] = [
    { id: "reach", text: L("Reach many people at the same time", "الوصول إلى كثير من الناس في الوقت نفسه"), answer: "broadcast" }, { id: "detail", text: L("Keep detailed directions and dates available", "إبقاء الاتجاهات والتواريخ المفصلة متاحة"), answer: "website" }, { id: "direct", text: L("Remind selected families tomorrow", "تذكير أسر محددة غدًا"), answer: "email" }, { id: "share", text: L("Encourage people to share the announcement", "تشجيع الناس على مشاركة الإعلان"), answer: "sns" },
  ];
  return <SelectMap locale={locale} rows={rows} options={{ broadcast: L("TV or radio role", "دور التلفاز أو الإذاعة"), website: L("Website role", "دور الموقع الإلكتروني"), email: L("Email role", "دور البريد الإلكتروني"), sns: L("SNS role", "دور الشبكات الاجتماعية") }} button={L("Check media roles", "تحقق من أدوار الوسائط")} success={L("Good. The same campaign can give each channel a different job.", "جيد. يمكن للحملة نفسها أن تعطي كل قناة وظيفة مختلفة.")} retry={L("Start with what the message needs to achieve in this situation.", "ابدأ بما تحتاج الرسالة إلى تحقيقه في هذا الموقف.")} onComplete={onComplete} />;
}

function MediaPlan({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const rows: SelectRow[] = [
    { id: "attention", text: L("Attract attention and invite sharing", "اجذب الانتباه وادعُ إلى المشاركة"), answer: "sns" }, { id: "details", text: L("Give complete class details and directions", "قدم تفاصيل الدروس والاتجاهات كاملة"), answer: "website" }, { id: "reminder", text: L("Send a direct reminder to registered parents", "أرسل تذكيرًا مباشرًا لأولياء الأمور المسجلين"), answer: "email" },
  ];
  return <SelectMap locale={locale} rows={rows} options={{ sns: L("SNS", "شبكات التواصل الاجتماعي"), website: L("Website", "موقع إلكتروني"), email: L("Email", "البريد الإلكتروني") }} button={L("Build the plan", "ابنِ الخطة")} success={L("This mix links attention, full information, and direct delivery.", "يربط هذا المزيج الانتباه بالمعلومات الكاملة والتسليم المباشر.")} retry={L("Give the role, not just the channel name, your attention.", "ركز على الدور لا على اسم القناة فقط.")} onComplete={onComplete} />;
}

function PersonaBuilder({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const [values, setValues] = useState<Record<string, string>>({}); const [checked, setChecked] = useState(false);
  const complete = Boolean(values.group && values.goal && values.device && values.challenge);
  const recommendations = values.group === "older" || values.challenge === "vision" ? L("Use readable text, clear contrast, and obvious navigation.", "استخدم نصًا مقروءًا وتباينًا واضحًا وتنقلًا ظاهرًا.") : values.device === "phone" || values.challenge === "time" ? L("Put the key action and essential information near the start of the page.", "ضع الإجراء الرئيسي والمعلومات الأساسية قرب بداية الصفحة.") : L("Group related information and make the next action easy to find.", "اجمع المعلومات المرتبطة واجعل الإجراء التالي سهل العثور عليه.");
  const field = (id: string, label: LocalizedText, options: Record<string, LocalizedText>) => <label><span>{pick(locale, label)}</span><select value={values[id] ?? ""} onChange={(event) => { setValues((current) => ({ ...current, [id]: event.target.value })); setChecked(false); }}><option value="">{t(locale, "Choose", "اختر")}</option>{Object.entries(options).map(([value, text]) => <option key={value} value={value}>{pick(locale, text)}</option>)}</select></label>;
  return <div className="unit4-persona-builder"><div className="unit4-field-grid">{field("group", L("User group", "فئة المستخدم"), { student: L("Student", "طالب"), parent: L("Parent", "ولي أمر"), older: L("Older visitor", "زائر أكبر سنًا") })}{field("goal", L("Main goal", "الهدف الرئيسي"), { hours: L("Find opening hours", "إيجاد ساعات العمل"), results: L("Check results", "فحص النتائج"), register: L("Register for an event", "التسجيل في فعالية") })}{field("device", L("Likely device", "الجهاز المحتمل"), { phone: L("Phone", "هاتف"), computer: L("Computer", "حاسوب") })}{field("challenge", L("Possible challenge", "التحدي المحتمل"), { time: L("Very little time", "وقت قليل جدًا"), vision: L("Low vision", "ضعف البصر"), unfamiliar: L("Unfamiliar with the site", "غير معتاد على الموقع") })}</div><section className="unit4-persona-preview" aria-live="polite"><Users size={24} /><div><strong>{t(locale, "Design priority", "أولوية التصميم")}</strong><p>{complete ? pick(locale, recommendations) : t(locale, "Complete the four choices to see a user-centered priority.", "أكمل الاختيارات الأربعة لرؤية أولوية متمحورة حول المستخدم.")}</p></div></section><button className="button secondary" type="button" onClick={() => { setChecked(true); if (complete) onComplete(); }}>{t(locale, "Save persona priority", "احفظ أولوية شخصية المستخدم")}</button>{checked && <Status locale={locale} success={Boolean(complete)}>{complete ? t(locale, "A persona turns a vague audience into design decisions that can be checked.", "تحول شخصية المستخدم الجمهور الغامض إلى قرارات تصميم يمكن فحصها.") : t(locale, "Choose a group, goal, device, and challenge first.", "اختر الفئة والهدف والجهاز والتحدي أولًا.")}</Status>}</div>;
}

function OrderingActivity({ locale, initial, answer, button, success, retry, onComplete }: { locale: Locale; initial: { id: string; text: LocalizedText }[]; answer: string[]; button: LocalizedText; success: LocalizedText; retry: LocalizedText; onComplete: () => void }) {
  const [order, setOrder] = useState(initial); const [checked, setChecked] = useState(false);
  const valid = order.every((item, index) => item.id === answer[index]);
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= order.length) return; const next = [...order]; [next[index], next[target]] = [next[target], next[index]]; setOrder(next); setChecked(false); };
  return <div className="unit4-ordering"><ol className="final-ordering">{order.map((item, index) => <li key={item.id}><b>{index + 1}</b><span>{pick(locale, item.text)}</span><div><button type="button" disabled={index === 0} onClick={() => move(index, -1)} aria-label={t(locale, "Move earlier", "انقل لأعلى")}><ArrowUp size={15} /></button><button type="button" disabled={index === order.length - 1} onClick={() => move(index, 1)} aria-label={t(locale, "Move later", "انقل لأسفل")}><ArrowDown size={15} /></button></div></li>)}</ol><button className="button secondary" type="button" onClick={() => { setChecked(true); if (valid) onComplete(); }}>{pick(locale, button)}</button>{checked && <Status locale={locale} success={valid}>{pick(locale, valid ? success : retry)}</Status>}</div>;
}

function WireframePriority({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const initial = [{ id: "directions", text: L("Directions", "الاتجاهات") }, { id: "services", text: L("Services", "الخدمات") }, { id: "appointment", text: L("Appointment button", "زر حجز موعد") }, { id: "hours", text: L("Opening hours", "ساعات العمل") }, { id: "emergency", text: L("Emergency contact", "اتصال الطوارئ") }];
  return <OrderingActivity locale={locale} initial={initial} answer={["emergency", "appointment", "hours", "services", "directions"]} button={L("Check page priority", "تحقق من أولوية الصفحة")} success={L("Good reasoning for a hurried visitor: urgent help and the main action appear first.", "تفكير جيد لزائر مستعجل: تظهر المساعدة العاجلة والإجراء الرئيسي أولًا.")} retry={L("Consider what a hurried clinic visitor must find before exploring extra detail.", "فكر فيما يجب أن يجده زائر العيادة المستعجل قبل استكشاف التفاصيل الإضافية.")} onComplete={onComplete} />;
}

function CrapFixer({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const rows: SelectRow[] = [
    { id: "button", text: L("The important “View results” button looks like ordinary body text", "زر «عرض النتائج» المهم يبدو كنص عادي"), answer: "contrast" }, { id: "headings", text: L("Each page gives the same type of heading a different style", "تعطي كل صفحة نوع العنوان نفسه أسلوبًا مختلفًا"), answer: "repetition" }, { id: "edges", text: L("Labels and fields start at unrelated horizontal positions", "تبدأ التسميات والحقول في مواضع أفقية غير مرتبطة"), answer: "alignment" }, { id: "price", text: L("A course fee is far from its course title and enrol button", "رسوم دورة بعيدة عن عنوان الدورة وزر التسجيل"), answer: "proximity" },
  ];
  return <SelectMap locale={locale} rows={rows} options={{ contrast: L("Contrast", "التباين"), repetition: L("Repetition", "التكرار"), alignment: L("Alignment", "المحاذاة"), proximity: L("Proximity", "التقارب") }} button={L("Fix the page", "أصلح الصفحة")} success={L("Exactly. Clear relationships reduce the effort needed to understand a page.", "بالضبط. تقلل العلاقات الواضحة الجهد اللازم لفهم الصفحة.")} retry={L("Ask whether the issue is priority, consistency, lines, or grouping.", "اسأل هل المشكلة في الأولوية أو الاتساق أو الخطوط أو التجميع.")} onComplete={onComplete} />;
}

function EvaluationSort({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const rows: SelectRow[] = [
    { id: "pv", text: L("The homepage received 6,400 page views", "تلقت الصفحة الرئيسية 6400 مشاهدة صفحة"), answer: "quant" }, { id: "observe", text: L("Two parents hesitate because they cannot find the school calendar", "يتردد والدان لأنهما لا يجدان تقويم المدرسة"), answer: "qual" }, { id: "interview", text: L("A learner says the labels are confusing", "يقول طالب إن التسميات مربكة"), answer: "qual" }, { id: "cvr", text: L("18 of 300 visitors complete registration", "يكمل 18 من أصل 300 زائر التسجيل"), answer: "quant" },
  ];
  return <SelectMap locale={locale} rows={rows} options={{ qual: L("Qualitative: why / experience", "نوعي: لماذا / تجربة"), quant: L("Quantitative: number / how much", "كمي: رقم / كم") }} button={L("Check evidence types", "تحقق من أنواع الأدلة")} success={L("Correct. Numbers show a pattern; observations and comments can investigate it.", "صحيح. تظهر الأرقام نمطًا؛ ويمكن للملاحظات والتعليقات فحصه.")} retry={L("Look for a number versus what people say or do.", "ابحث عن رقم مقابل ما يقوله الناس أو يفعلونه.")} onComplete={onComplete} />;
}

function MetricLab({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const [bounce, setBounce] = useState(""); const [conversion, setConversion] = useState(""); const [conclusion, setConclusion] = useState(""); const [checked, setChecked] = useState(false);
  const correct = bounce === "40" && conversion === "5" && conclusion === "needs-why";
  return <div className="unit4-metric-lab"><div className="unit4-metric-grid"><section><BarChart3 size={22} /><strong>{t(locale, "Bounce rate", "معدل الارتداد")}</strong><p>{t(locale, "100 visits; 40 leave after the first page.", "100 زيارة؛ يغادر 40 بعد الصفحة الأولى.")}</p><label><span>{t(locale, "Rate", "المعدل")}</span><select value={bounce} onChange={(event) => { setBounce(event.target.value); setChecked(false); }}><option value="">%</option><option value="40">40%</option><option value="60">60%</option><option value="4">4%</option></select></label></section><section><MousePointerClick size={22} /><strong>{t(locale, "Conversion rate", "معدل التحويل")}</strong><p>{t(locale, "200 visits; 10 completed registrations.", "200 زيارة؛ 10 تسجيلات مكتملة.")}</p><label><span>{t(locale, "Rate", "المعدل")}</span><select value={conversion} onChange={(event) => { setConversion(event.target.value); setChecked(false); }}><option value="">%</option><option value="5">5%</option><option value="10">10%</option><option value="20">20%</option></select></label></section></div><label className="unit4-conclusion"><span>{t(locale, "High page views with low registrations tells a team:", "تخبر المشاهدات العالية مع التسجيلات المنخفضة الفريق بأن:")}</span><select value={conclusion} onChange={(event) => { setConclusion(event.target.value); setChecked(false); }}><option value="">{t(locale, "Choose a conclusion", "اختر استنتاجًا")}</option><option value="needs-why">{t(locale, "Many arrive; qualitative evidence is needed to learn why few finish.", "يصل كثيرون؛ وتلزم أدلة نوعية لمعرفة سبب إكمال القليل.")}</option><option value="button">{t(locale, "The button colour is definitely wrong.", "لون الزر خاطئ بالتأكيد.")}</option><option value="perfect">{t(locale, "The page needs no evaluation.", "لا تحتاج الصفحة إلى تقييم.")}</option></select></label><button className="button secondary" type="button" onClick={() => { setChecked(true); if (correct) onComplete(); }}>{t(locale, "Check the measures", "تحقق من المقاييس")}</button>{checked && <Status locale={locale} success={correct}>{correct ? t(locale, "Correct. The calculations show a pattern; user research can explore the reason.", "صحيح. تظهر الحسابات نمطًا؛ ويمكن لبحث المستخدمين استكشاف السبب.") : t(locale, "Recheck each proportion: part ÷ total × 100, then avoid guessing the cause.", "أعد فحص كل نسبة: الجزء ÷ الكل × 100، ثم تجنب تخمين السبب.")}</Status>}</div>;
}

function HeuristicMap({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const rows: SelectRow[] = [
    { id: "label", text: L("The same action is “Send” on one page and “Finish now” on another", "الإجراء نفسه «إرسال» في صفحة و«أنهِ الآن» في صفحة أخرى"), answer: "consistency" }, { id: "mistake", text: L("A booking form accepts an impossible date without warning", "يقبل نموذج الحجز تاريخًا مستحيلًا دون تحذير"), answer: "prevention" }, { id: "submit", text: L("After submitting, the page gives no loading, success, or error message", "بعد الإرسال، لا تقدم الصفحة رسالة تحميل أو نجاح أو خطأ"), answer: "status" },
  ];
  return <SelectMap locale={locale} rows={rows} options={{ consistency: L("Consistency", "الاتساق"), prevention: L("Error prevention", "منع الأخطاء"), status: L("Visibility of system status", "وضوح حالة النظام") }} button={L("Check the heuristic map", "تحقق من خريطة القواعد")} success={L("Well diagnosed. Each issue is a practical usability rule a team can improve.", "تشخيص جيد. كل مشكلة قاعدة عملية لسهولة الاستخدام يمكن للفريق تحسينها.")} retry={L("Ask whether the problem is unfamiliar wording, a preventable mistake, or missing feedback.", "اسأل هل المشكلة تسميات غير مألوفة أو خطأ يمكن منعه أو تغذية راجعة مفقودة.")} onComplete={onComplete} />;
}

function PdcaOrder({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const initial = [{ id: "check", text: L("Check: compare the result with the goal", "تحقق: قارن النتيجة بالهدف") }, { id: "act", text: L("Act: decide whether to keep, refine, or change course", "تصرف: قرر الإبقاء أو التحسين أو تغيير المسار") }, { id: "plan", text: L("Plan: set a goal and one change", "خطط: حدد هدفًا وتغييرًا واحدًا") }, { id: "do", text: L("Do: implement the planned change", "نفذ: طبق التغيير المخطط") }];
  return <OrderingActivity locale={locale} initial={initial} answer={["plan", "do", "check", "act"]} button={L("Check PDCA", "تحقق من PDCA")} success={L("Correct. Act leads into a new Plan because improvement continues.", "صحيح. يؤدي التصرف إلى تخطيط جديد لأن التحسين مستمر.")} retry={L("Begin with a goal, then make the change before measuring its result.", "ابدأ بهدف ثم نفذ التغيير قبل قياس نتيجته.")} onComplete={onComplete} />;
}

function DesignThinkingOrder({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const initial = [{ id: "prototype", text: L("Make a quick mock-up with a clearer registration action", "اصنع نموذجًا سريعًا بإجراء تسجيل أوضح") }, { id: "empathize", text: L("Observe students trying to find the registration action", "لاحظ الطلاب وهم يحاولون إيجاد إجراء التسجيل") }, { id: "test", text: L("Let students try the mock-up and listen to feedback", "دع الطلاب يجربون النموذج واستمع إلى التغذية الراجعة") }, { id: "define", text: L("State the problem: mobile students cannot find the action", "حدد المشكلة: لا يستطيع طلاب الهاتف إيجاد الإجراء") }, { id: "ideate", text: L("Generate several navigation and label ideas", "ولد عدة أفكار للتنقل والتسميات") }];
  return <OrderingActivity locale={locale} initial={initial} answer={["empathize", "define", "ideate", "prototype", "test"]} button={L("Check Design Thinking", "تحقق من التفكير التصميمي")} success={L("Correct. Testing can return a team to understand or redefine the problem.", "صحيح. يمكن للاختبار أن يعيد الفريق إلى فهم المشكلة أو تعريفها من جديد.")} retry={L("First learn from people, then define before creating alternatives.", "تعلم أولًا من الناس، ثم حدد المشكلة قبل إنشاء البدائل.")} onComplete={onComplete} />;
}

function AbTestSimulator({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const [winner, setWinner] = useState(""); const [reason, setReason] = useState(""); const [checked, setChecked] = useState(false); const correct = winner === "b" && reason === "one";
  return <div className="unit4-ab-test"><div className="unit4-ab-cards"><section><span>A</span><strong>{t(locale, "Register", "سجل")}</strong><p>32 / 100 {t(locale, "users", "مستخدم")}</p></section><section><span>B</span><strong>{t(locale, "Join Event", "انضم إلى الفعالية")}</strong><p>47 / 100 {t(locale, "users", "مستخدم")}</p></section></div><label><span>{t(locale, "Which version performed better in this sample?", "أي نسخة أدت أفضل في هذه العينة؟")}</span><select value={winner} onChange={(event) => { setWinner(event.target.value); setChecked(false); }}><option value="">{t(locale, "Choose", "اختر")}</option><option value="a">A — {t(locale, "Register", "سجل")}</option><option value="b">B — {t(locale, "Join Event", "انضم إلى الفعالية")}</option></select></label><label><span>{t(locale, "Why keep colour, position, and layout unchanged in this test?", "لماذا نبقي اللون والموضع والتخطيط دون تغيير في هذا الاختبار؟")}</span><select value={reason} onChange={(event) => { setReason(event.target.value); setChecked(false); }}><option value="">{t(locale, "Choose", "اختر")}</option><option value="one">{t(locale, "So a result can be connected to the one changed label", "ليستطيع الفريق ربط النتيجة بالتسمية الوحيدة المتغيرة")}</option><option value="many">{t(locale, "So every version is completely different", "كي تكون كل نسخة مختلفة تمامًا")}</option></select></label><button className="button secondary" type="button" onClick={() => { setChecked(true); if (correct) onComplete(); }}>{t(locale, "Check the A/B test", "تحقق من اختبار A/B")}</button>{checked && <Status locale={locale} success={correct}>{correct ? t(locale, "B has the stronger sample result. Controlled changes make the result interpretable.", "لدى B النتيجة الأقوى في العينة. تجعل التغييرات المضبوطة النتيجة قابلة للتفسير.") : t(locale, "Use the displayed results and remember that one changed element makes comparison fair.", "استخدم النتائج المعروضة وتذكر أن عنصرًا متغيرًا واحدًا يجعل المقارنة عادلة.")}</Status>}</div>;
}

function ChallengeMedia({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const [selected, setSelected] = useState<string[]>([]); const [missed, setMissed] = useState(""); const [reason, setReason] = useState(""); const [saved, setSaved] = useState(false);
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  const valid = Boolean(selected.length >= 2 && missed && reason.trim().length >= 16);
  const media = [{ id: "sns", text: L("SNS — attract attention and sharing", "الشبكات الاجتماعية — جذب الانتباه والمشاركة") }, { id: "website", text: L("Website — complete class details", "الموقع الإلكتروني — تفاصيل الدروس الكاملة") }, { id: "radio", text: L("Radio / print notice — reach beyond Internet access", "إذاعة / إعلان مطبوع — الوصول خارج الإنترنت") }, { id: "email", text: L("Email — direct reminder", "البريد الإلكتروني — تذكير مباشر") }];
  return <div className="unit4-challenge-form"><div className="unit4-choice-cards">{media.map((item) => <label key={item.id} data-selected={selected.includes(item.id)}><input type="checkbox" checked={selected.includes(item.id)} onChange={() => { toggle(item.id); setSaved(false); }} /><span>{pick(locale, item.text)}</span></label>)}</div><label><span>{t(locale, "Which group may still be missed?", "أي مجموعة قد تظل غير مشمولة؟")}</span><select value={missed} onChange={(event) => { setMissed(event.target.value); setSaved(false); }}><option value="">{t(locale, "Choose a group", "اختر مجموعة")}</option><option value="limited">{t(locale, "People with limited Internet access", "أشخاص لديهم وصول محدود للإنترنت")}</option><option value="older">{t(locale, "Older residents", "سكان أكبر سنًا")}</option><option value="busy">{t(locale, "Busy parents", "أولياء أمور مشغولون")}</option></select></label><label className="challenge-writing"><span>{t(locale, "Explain the purpose and audience for your selected media.", "اشرح الغرض والجمهور لوسائلك المختارة.")}</span><textarea value={reason} onChange={(event) => { setReason(event.target.value); setSaved(false); }} /></label><button className="button secondary" type="button" onClick={() => { setSaved(true); if (valid) onComplete(); }}>{t(locale, "Save media plan", "احفظ خطة الوسائط")}</button>{saved && <Status locale={locale} success={valid}>{valid ? t(locale, "Recorded. Your plan has multiple roles and acknowledges a possible access gap.", "تم التسجيل. لخُطتك أدوار متعددة وتعترف بفجوة وصول محتملة.") : t(locale, "Select two media, name a group, and add a short justification.", "اختر وسيطين وسم مجموعة وأضف تبريرًا قصيرًا.")}</Status>}</div>;
}

function ChallengeResults({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const rows: SelectRow[] = [{ id: "persona", text: L("A user who needs to check results quickly on a phone", "مستخدم يحتاج إلى فحص النتائج بسرعة على هاتف"), answer: "student" }, { id: "priority", text: L("Information that should appear first", "المعلومات التي ينبغي أن تظهر أولًا"), answer: "results" }, { id: "crap", text: L("Make the key action easy to notice", "اجعل الإجراء الرئيسي سهل الملاحظة"), answer: "contrast" }];
  const [values, setValues] = useState<Record<string, string>>({}); const [reason, setReason] = useState(""); const [saved, setSaved] = useState(false); const valid = Boolean(rows.every((row) => values[row.id] === row.answer) && reason.trim().length >= 16);
  const options: Record<string, LocalizedText> = { student: L("Student persona", "شخصية طالب"), results: L("Results summary and clear next action", "ملخص النتائج وإجراء تالٍ واضح"), contrast: L("Contrast", "التباين"), decoration: L("Decoration first", "الزينة أولًا") };
  return <div className="unit4-challenge-form"><div className="security-map-rows">{rows.map((row) => <label key={row.id}><span>{pick(locale, row.text)}</span><select value={values[row.id] ?? ""} onChange={(event) => { setValues((current) => ({ ...current, [row.id]: event.target.value })); setSaved(false); }}><option value="">{t(locale, "Choose", "اختر")}</option>{Object.entries(options).map(([id, text]) => <option key={id} value={id}>{pick(locale, text)}</option>)}</select></label>)}</div><label className="challenge-writing"><span>{t(locale, "Explain how this page choice helps usability or accessibility.", "اشرح كيف يساعد اختيار الصفحة هذا في سهولة الاستخدام أو الوصول.")}</span><textarea value={reason} onChange={(event) => { setReason(event.target.value); setSaved(false); }} /></label><button className="button secondary" type="button" onClick={() => { setSaved(true); if (valid) onComplete(); }}>{t(locale, "Save results page plan", "احفظ خطة صفحة النتائج")}</button>{saved && <Status locale={locale} success={valid}>{valid ? t(locale, "Recorded. The page starts from a user need and gives the priority action a clear place.", "تم التسجيل. تبدأ الصفحة من احتياج مستخدم وتعطي الإجراء ذي الأولوية مكانًا واضحًا.") : t(locale, "Make all three design choices and add a brief explanation.", "اتخذ قرارات التصميم الثلاثة وأضف شرحًا قصيرًا.")}</Status>}</div>;
}

function ChallengeBookstore({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const [method, setMethod] = useState(""); const [focus, setFocus] = useState(""); const [question, setQuestion] = useState(""); const [saved, setSaved] = useState(false); const valid = Boolean(method === "test" && focus === "low-cvr" && question.trim().length >= 12);
  return <div className="unit4-challenge-form"><label><span>{t(locale, "Choose a qualitative method to investigate why few visitors buy.", "اختر طريقة نوعية لفحص سبب شراء عدد قليل من الزوار.")}</span><select value={method} onChange={(event) => { setMethod(event.target.value); setSaved(false); }}><option value="">{t(locale, "Choose", "اختر")}</option><option value="test">{t(locale, "Usability test: observe a visitor trying to buy a book", "اختبار سهولة الاستخدام: راقب زائرًا يحاول شراء كتاب")}</option><option value="pv">{t(locale, "Count page views again", "اعد مشاهدات الصفحات مرة أخرى")}</option></select></label><label><span>{t(locale, "Which pattern should the team describe accurately?", "أي نمط ينبغي أن يصفه الفريق بدقة؟")}</span><select value={focus} onChange={(event) => { setFocus(event.target.value); setSaved(false); }}><option value="">{t(locale, "Choose", "اختر")}</option><option value="low-cvr">{t(locale, "High PV, low purchase CVR, and many first-page exits", "مشاهدات عالية وتحويل شراء منخفض وخروج كثير من الصفحة الأولى")}</option><option value="perfect">{t(locale, "The page is already perfect", "الصفحة مثالية بالفعل")}</option></select></label><label className="challenge-writing"><span>{t(locale, "Write one question you would ask a visitor.", "اكتب سؤالًا واحدًا ستطرحه على زائر.")}</span><textarea value={question} onChange={(event) => { setQuestion(event.target.value); setSaved(false); }} /></label><button className="button secondary" type="button" onClick={() => { setSaved(true); if (valid) onComplete(); }}>{t(locale, "Save evaluation plan", "احفظ خطة التقييم")}</button>{saved && <Status locale={locale} success={valid}>{valid ? t(locale, "Recorded. You used the numbers to focus a qualitative investigation instead of guessing the cause.", "تم التسجيل. استخدمت الأرقام لتركيز فحص نوعي بدل تخمين السبب.") : t(locale, "Choose the evidence pattern and a qualitative method, then write a question.", "اختر نمط الأدلة والطريقة النوعية ثم اكتب سؤالًا.")}</Status>}</div>;
}

function ChallengeImprovement({ locale, onComplete }: { locale: Locale; onComplete: () => void }) {
  const [metric, setMetric] = useState(""); const [change, setChange] = useState(""); const [next, setNext] = useState(""); const [reason, setReason] = useState(""); const [saved, setSaved] = useState(false); const valid = Boolean(metric === "cvr" && change === "label" && next === "measure" && reason.trim().length >= 16);
  return <div className="unit4-challenge-form"><div className="unit4-field-grid"><label><span>{t(locale, "Metric", "المقياس")}</span><select value={metric} onChange={(event) => { setMetric(event.target.value); setSaved(false); }}><option value="">{t(locale, "Choose", "اختر")}</option><option value="cvr">{t(locale, "Registration CVR", "معدل تحويل التسجيل")}</option><option value="colour">{t(locale, "Favourite colour", "اللون المفضل")}</option></select></label><label><span>{t(locale, "One A/B change", "تغيير واحد لـ A/B")}</span><select value={change} onChange={(event) => { setChange(event.target.value); setSaved(false); }}><option value="">{t(locale, "Choose", "اختر")}</option><option value="label">{t(locale, "Compare two registration button labels", "قارن تسميتين لزر التسجيل")}</option><option value="everything">{t(locale, "Redesign every page element", "أعد تصميم كل عنصر في الصفحة")}</option></select></label><label><span>{t(locale, "After measurement", "بعد القياس")}</span><select value={next} onChange={(event) => { setNext(event.target.value); setSaved(false); }}><option value="">{t(locale, "Choose", "اختر")}</option><option value="measure">{t(locale, "Use evidence to keep, refine, or test the next change", "استخدم الأدلة للإبقاء أو التحسين أو اختبار التغيير التالي")}</option><option value="ignore">{t(locale, "Ignore the result", "تجاهل النتيجة")}</option></select></label></div><label className="challenge-writing"><span>{t(locale, "Describe the user problem and why this one change could help.", "صف مشكلة المستخدم ولماذا قد يساعد هذا التغيير الواحد.")}</span><textarea value={reason} onChange={(event) => { setReason(event.target.value); setSaved(false); }} /></label><button className="button secondary" type="button" onClick={() => { setSaved(true); if (valid) onComplete(); }}>{t(locale, "Save improvement loop", "احفظ حلقة التحسين")}</button>{saved && <Status locale={locale} success={valid}>{valid ? t(locale, "Recorded. This is a measurable, focused loop rather than an untestable full redesign.", "تم التسجيل. هذه حلقة مركزة قابلة للقياس بدل إعادة تصميم كاملة لا يمكن اختبارها.") : t(locale, "Choose a measurable registration metric, one controlled change, a next action, and add your reasoning.", "اختر مقياس تسجيل قابلًا للقياس وتغييرًا مضبوطًا واحدًا وإجراءً تاليًا وأضف تفكيرك.")}</Status>}</div>;
}

export function Unit4ActivityRenderer({ activity, locale, complete, onComplete }: { activity: LessonActivity; locale: Locale; complete: boolean; onComplete: (id: string) => void }) {
  const done = () => onComplete(activity.id);
  const content = activity.id === "media-direction-sort" ? <MediaDirection locale={locale} onComplete={done} />
    : activity.id === "website-balance" ? <WebsiteBalance locale={locale} onComplete={done} />
      : activity.id === "media-purpose-match" ? <PurposeMatch locale={locale} onComplete={done} />
        : activity.id === "media-plan-builder" ? <MediaPlan locale={locale} onComplete={done} />
          : activity.id === "persona-builder" ? <PersonaBuilder locale={locale} onComplete={done} />
            : activity.id === "wireframe-priority" ? <WireframePriority locale={locale} onComplete={done} />
              : activity.id === "crap-fixer" ? <CrapFixer locale={locale} onComplete={done} />
                : activity.id === "evaluation-sort" ? <EvaluationSort locale={locale} onComplete={done} />
                  : activity.id === "metric-lab" ? <MetricLab locale={locale} onComplete={done} />
                    : activity.id === "heuristic-map" ? <HeuristicMap locale={locale} onComplete={done} />
                      : activity.id === "pdca-order" ? <PdcaOrder locale={locale} onComplete={done} />
                        : activity.id === "design-thinking-order" ? <DesignThinkingOrder locale={locale} onComplete={done} />
                          : <AbTestSimulator locale={locale} onComplete={done} />;
  return <ActivityFrame activity={activity} locale={locale} complete={complete}>{content}</ActivityFrame>;
}

type Reflection = { transfer: LocalizedText; pairDiscussion: LocalizedText; individualPrompt: LocalizedText };
export function Unit4Challenge({ challenge, reflection, locale, complete, onComplete, reflectionValue, onReflectionChange }: { challenge: LessonChallenge; reflection?: Reflection; locale: Locale; complete: boolean; onComplete: () => void; reflectionValue: string; onReflectionChange: (value: string) => void }) {
  const content = challenge.id === "community-media-plan" ? <ChallengeMedia locale={locale} onComplete={onComplete} /> : challenge.id === "results-page-design" ? <ChallengeResults locale={locale} onComplete={onComplete} /> : challenge.id === "bookstore-evaluation" ? <ChallengeBookstore locale={locale} onComplete={onComplete} /> : <ChallengeImprovement locale={locale} onComplete={onComplete} />;
  return <><article className="panel unit2-challenge unit4-challenge" data-complete={complete}><div className="unit2-challenge-heading"><span><ClipboardCheck size={23} /></span><div><span className="eyebrow">{t(locale, "Think as an Engineer", "فكر كمهندس")}</span><h2>{pick(locale, challenge.title)}</h2><p>{pick(locale, challenge.prompt)}</p></div></div><ul>{challenge.successCriteria.map((criterion) => <li key={criterion.en}><CheckCircle2 size={16} />{pick(locale, criterion)}</li>)}</ul>{content}</article>{reflection && <article className="panel unit2-reflection unit4-reflection"><span className="eyebrow">{t(locale, "Transfer & reflect", "نقل وتأمل")}</span><h3>{t(locale, "Apply the idea in a new context", "طبق الفكرة في سياق جديد")}</h3><p>{pick(locale, reflection.transfer)}</p><p className="pair-prompt"><strong>{t(locale, "In-person pair discussion:", "نقاش ثنائي حضوري:")}</strong> {pick(locale, reflection.pairDiscussion)}</p><label><span>{pick(locale, reflection.individualPrompt)}</span><textarea value={reflectionValue} onChange={(event) => onReflectionChange(event.target.value)} placeholder={t(locale, "Write your individual conclusion.", "اكتب خلاصتك الفردية.")} /></label></article>}</>;
}
