-- Unit 1 pilot: core relational model.
-- Apply with the Supabase CLI. This migration assumes the standard `auth` and
-- `storage` schemas supplied by Supabase.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
revoke all on schema private from public;

create type public.app_role as enum ('student', 'teacher', 'admin');
create type public.locale_code as enum ('en', 'ar');
create type public.class_status as enum ('active', 'archived');
create type public.class_member_role as enum ('student', 'teacher');
create type public.lesson_version_status as enum ('draft', 'published', 'archived');
create type public.assignment_status as enum ('draft', 'assigned', 'closed');
create type public.assignment_kind as enum ('lesson', 'pretest', 'posttest', 'review');
create type public.learning_event_type as enum (
  'response_submitted',
  'assessment_submitted',
  'reflection_submitted',
  'simulation_completed',
  'retrieval_answered'
);
create type public.grading_state as enum (
  'ungraded',
  'automatically_graded',
  'manual_pending',
  'teacher_graded'
);
create type public.asset_status as enum ('draft', 'ready', 'retired');

create or replace function private.is_localized_text(value jsonb)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select jsonb_typeof(value) = 'object'
    and jsonb_typeof(value -> 'en') = 'string'
    and jsonb_typeof(value -> 'ar') = 'string'
    and length(btrim(value ->> 'en')) > 0
    and length(btrim(value ->> 'ar')) > 0;
$$;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := statement_timestamp();
  return new;
end;
$$;

create or replace function private.generate_class_code()
returns text
language plpgsql
volatile
set search_path = ''
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  result text := '';
  i integer;
begin
  for i in 1..8 loop
    result := result || substr(alphabet, 1 + floor(random() * length(alphabet))::integer, 1);
  end loop;
  return result;
end;
$$;

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role public.app_role not null default 'student',
  display_name text,
  preferred_locale public.locale_code not null default 'en',
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  constraint profiles_display_name_length check (
    display_name is null or char_length(display_name) between 1 and 100
  )
);

comment on table public.profiles is
  'Application identities backed by auth.users. Student auth users are generated by the trusted server with non-deliverable internal email addresses; students do not need real names or email addresses.';
comment on column public.profiles.role is
  'Only trusted server/admin workflows may assign teacher or admin. Admin capabilities also require an aal2 JWT.';

create table public.classes (
  id uuid primary key default extensions.gen_random_uuid(),
  code text not null default private.generate_class_code(),
  title text not null,
  teacher_id uuid not null references public.profiles(user_id) on delete restrict,
  status public.class_status not null default 'active',
  archived_at timestamptz,
  created_by uuid references public.profiles(user_id) on delete set null default auth.uid(),
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  constraint classes_code_format check (code ~ '^[A-HJ-NP-Z2-9]{8}$'),
  constraint classes_title_length check (char_length(btrim(title)) between 1 and 120),
  constraint classes_archive_consistency check (
    (status = 'active' and archived_at is null)
    or (status = 'archived' and archived_at is not null)
  ),
  constraint classes_code_unique unique (code)
);

comment on column public.classes.code is
  'Exactly eight uppercase, non-ambiguous characters. Generate/retry on the trusted server if the unique constraint encounters a collision.';

create table public.memberships (
  id uuid primary key default extensions.gen_random_uuid(),
  class_id uuid not null references public.classes(id) on delete cascade,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  member_role public.class_member_role not null,
  learner_id text,
  pin_changed_at timestamptz,
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  constraint memberships_user_once_per_class unique (class_id, user_id),
  constraint memberships_learner_identity check (
    (member_role = 'student' and learner_id ~ '^[A-Za-z0-9_-]{3,32}$')
    or (member_role = 'teacher' and learner_id is null)
  )
);

create unique index memberships_class_learner_id_uq
  on public.memberships (class_id, lower(learner_id))
  where member_role = 'student';

comment on column public.memberships.learner_id is
  'Teacher-issued pseudonymous login identifier, unique case-insensitively inside a class. The eight-digit PIN is never stored here; it is used as the password of the generated Supabase Auth identity and is handled only by trusted server code.';

create table public.lessons (
  id uuid primary key default extensions.gen_random_uuid(),
  slug text not null unique,
  unit_number smallint not null,
  lesson_number smallint not null,
  title jsonb not null,
  is_active boolean not null default true,
  created_by uuid references public.profiles(user_id) on delete set null default auth.uid(),
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  constraint lessons_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint lessons_number_range check (unit_number > 0 and lesson_number > 0),
  constraint lessons_title_localized check (private.is_localized_text(title)),
  constraint lessons_unit_lesson_unique unique (unit_number, lesson_number)
);

create table public.assets (
  id uuid primary key default extensions.gen_random_uuid(),
  storage_bucket text not null default 'lesson-assets',
  storage_path text not null,
  mime_type text not null,
  byte_size integer not null,
  sha256 text not null,
  alt_text jsonb not null,
  rights_holder text not null,
  rights_basis text not null,
  status public.asset_status not null default 'draft',
  created_by uuid references public.profiles(user_id) on delete set null default auth.uid(),
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  constraint assets_location_unique unique (storage_bucket, storage_path),
  constraint assets_bucket check (storage_bucket = 'lesson-assets'),
  constraint assets_safe_mime check (mime_type in ('image/png', 'image/jpeg', 'image/webp')),
  constraint assets_size check (byte_size between 1 and 2097152),
  constraint assets_hash_format check (sha256 ~ '^[a-f0-9]{64}$'),
  constraint assets_alt_text_localized check (private.is_localized_text(alt_text)),
  constraint assets_rights_holder check (char_length(btrim(rights_holder)) between 1 and 200),
  constraint assets_rights_basis check (char_length(btrim(rights_basis)) between 1 and 500),
  constraint assets_safe_path check (
    storage_path !~ '(^|/)\.\.(/|$)'
    and storage_path !~ '^/'
    and char_length(storage_path) between 1 and 500
  )
);

comment on table public.assets is
  'Metadata for private Storage objects. Lesson downloads receive short-lived signed URLs; the bucket is never public.';

create table public.lesson_versions (
  id uuid primary key default extensions.gen_random_uuid(),
  lesson_id uuid not null references public.lessons(id) on delete cascade,
  version integer not null,
  status public.lesson_version_status not null default 'draft',
  content jsonb not null,
  content_hash text not null default '',
  source_version_id uuid references public.lesson_versions(id) on delete set null,
  created_by uuid references public.profiles(user_id) on delete set null default auth.uid(),
  published_at timestamptz,
  archived_at timestamptz,
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  constraint lesson_versions_number_positive check (version > 0),
  constraint lesson_versions_content_object check (jsonb_typeof(content) = 'object'),
  constraint lesson_versions_hash_format check (content_hash = '' or content_hash ~ '^[a-f0-9]{64}$'),
  constraint lesson_versions_lesson_version_unique unique (lesson_id, version),
  constraint lesson_versions_lifecycle check (
    (status = 'draft' and published_at is null and archived_at is null)
    or (status = 'published' and published_at is not null and archived_at is null)
    or (status = 'archived' and published_at is not null and archived_at is not null)
  )
);

create unique index lesson_versions_one_published_uq
  on public.lesson_versions (lesson_id)
  where status = 'published';
create index lesson_versions_lesson_status_idx
  on public.lesson_versions (lesson_id, status, version desc);

comment on table public.lesson_versions is
  'Drafts may be edited. Once published, instructional content and its SHA-256 hash are immutable; archiving changes lifecycle metadata only. Assignments pin a version row forever.';

create table public.assignments (
  id uuid primary key default extensions.gen_random_uuid(),
  class_id uuid not null references public.classes(id) on delete cascade,
  lesson_version_id uuid not null references public.lesson_versions(id) on delete restrict,
  kind public.assignment_kind not null default 'lesson',
  title jsonb not null,
  status public.assignment_status not null default 'draft',
  opens_at timestamptz,
  due_at timestamptz,
  assigned_by uuid references public.profiles(user_id) on delete set null default auth.uid(),
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  constraint assignments_title_localized check (private.is_localized_text(title)),
  constraint assignments_dates_ordered check (due_at is null or opens_at is null or due_at >= opens_at)
);

create index assignments_class_status_idx
  on public.assignments (class_id, status, due_at);
create index assignments_version_idx
  on public.assignments (lesson_version_id);

create table public.learning_events (
  client_event_id uuid primary key,
  assignment_id uuid not null references public.assignments(id) on delete cascade,
  lesson_version_id uuid not null references public.lesson_versions(id) on delete restrict,
  student_id uuid not null references public.profiles(user_id) on delete cascade,
  block_id text not null,
  objective_ids text[] not null,
  event_type public.learning_event_type not null default 'response_submitted',
  response jsonb not null,
  attempt integer not null,
  client_created_at timestamptz not null,
  received_at timestamptz not null default statement_timestamp(),
  grading_state public.grading_state not null default 'ungraded',
  server_score numeric(8,2),
  max_score numeric(8,2),
  is_correct boolean,
  server_feedback jsonb,
  constraint learning_events_block_id check (block_id ~ '^[A-Za-z0-9._:-]{1,100}$'),
  constraint learning_events_objectives check (cardinality(objective_ids) > 0),
  constraint learning_events_attempt_positive check (attempt > 0),
  constraint learning_events_response_size check (octet_length(response::text) <= 65536),
  constraint learning_events_score_pair check (
    (server_score is null and max_score is null)
    or (server_score is not null and max_score is not null and max_score > 0 and server_score between 0 and max_score)
  ),
  constraint learning_events_grading_consistency check (
    (grading_state in ('ungraded', 'manual_pending') and server_score is null and max_score is null and is_correct is null)
    or (grading_state in ('automatically_graded', 'teacher_graded') and server_score is not null and max_score is not null)
  )
);

create index learning_events_student_assignment_idx
  on public.learning_events (student_id, assignment_id, received_at);
create index learning_events_assignment_objectives_idx
  on public.learning_events using gin (objective_ids);
create index learning_events_assignment_block_idx
  on public.learning_events (assignment_id, block_id, attempt);
create index learning_events_manual_queue_idx
  on public.learning_events (assignment_id, received_at)
  where grading_state = 'manual_pending';

comment on column public.learning_events.client_event_id is
  'Client-generated UUID and global idempotency key. Retrying the same event must return the stored server result rather than create a second record.';
comment on column public.learning_events.server_score is
  'Always calculated by trusted server code from the pinned lesson version. Client-provided scores are ignored.';

create table public.teacher_reviews (
  id uuid primary key default extensions.gen_random_uuid(),
  learning_event_id uuid not null unique references public.learning_events(client_event_id) on delete cascade,
  reviewer_id uuid references public.profiles(user_id) on delete set null default auth.uid(),
  rubric_results jsonb not null,
  score numeric(8,2) not null,
  max_score numeric(8,2) not null,
  feedback text,
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  constraint teacher_reviews_score check (max_score > 0 and score between 0 and max_score),
  constraint teacher_reviews_rubric_object check (jsonb_typeof(rubric_results) = 'object'),
  constraint teacher_reviews_feedback_size check (feedback is null or char_length(feedback) <= 5000)
);

create index teacher_reviews_reviewer_idx
  on public.teacher_reviews (reviewer_id, updated_at desc);

create table public.content_audit_logs (
  id bigint generated always as identity primary key,
  actor_id uuid references public.profiles(user_id) on delete set null,
  entity_type text not null,
  entity_id uuid not null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default statement_timestamp(),
  constraint content_audit_entity_type check (entity_type in ('lesson', 'lesson_version', 'asset')),
  constraint content_audit_action check (action in ('create', 'update', 'delete', 'publish', 'archive', 'rollback', 'retire')),
  constraint content_audit_details_object check (jsonb_typeof(details) = 'object')
);

create index content_audit_entity_idx
  on public.content_audit_logs (entity_type, entity_id, created_at desc);
create index content_audit_actor_idx
  on public.content_audit_logs (actor_id, created_at desc);

create table public.login_attempts (
  id bigint generated always as identity primary key,
  membership_id uuid references public.memberships(id) on delete set null,
  identifier_hash text not null,
  ip_hash text,
  user_agent_hash text,
  succeeded boolean not null,
  attempted_at timestamptz not null default clock_timestamp(),
  constraint login_attempts_identifier_hash check (identifier_hash ~ '^[a-f0-9]{64}$'),
  constraint login_attempts_ip_hash check (ip_hash is null or ip_hash ~ '^[a-f0-9]{64}$'),
  constraint login_attempts_user_agent_hash check (user_agent_hash is null or user_agent_hash ~ '^[a-f0-9]{64}$')
);

create index login_attempts_identifier_time_idx
  on public.login_attempts (identifier_hash, attempted_at desc);
create index login_attempts_cleanup_idx
  on public.login_attempts (attempted_at);

create table public.login_lockouts (
  identifier_hash text primary key,
  membership_id uuid references public.memberships(id) on delete cascade,
  failed_count smallint not null default 0,
  window_started_at timestamptz not null default clock_timestamp(),
  locked_until timestamptz,
  updated_at timestamptz not null default clock_timestamp(),
  constraint login_lockouts_identifier_hash check (identifier_hash ~ '^[a-f0-9]{64}$'),
  constraint login_lockouts_failed_count check (failed_count between 0 and 100)
);

comment on table public.login_attempts is
  'Server-only audit table. identifier_hash is SHA-256 of a server-peppered normalized class-code/learner-id tuple; raw PINs and raw network identifiers are never persisted.';

create or replace function private.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested_role text;
  safe_role public.app_role;
begin
  requested_role := new.raw_app_meta_data ->> 'app_role';
  safe_role := case requested_role
    when 'teacher' then 'teacher'::public.app_role
    when 'admin' then 'admin'::public.app_role
    else 'student'::public.app_role
  end;

  insert into public.profiles (user_id, role, display_name, preferred_locale)
  values (
    new.id,
    safe_role,
    nullif(btrim(new.raw_user_meta_data ->> 'display_name'), ''),
    case when new.raw_user_meta_data ->> 'preferred_locale' = 'ar'
      then 'ar'::public.locale_code else 'en'::public.locale_code end
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_auth_user();

create or replace function private.validate_class_owner()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  owner_role public.app_role;
begin
  select p.role into owner_role from public.profiles p where p.user_id = new.teacher_id;
  if owner_role is null or owner_role not in ('teacher', 'admin') then
    raise exception using errcode = '23514', message = 'class owner must have teacher or admin role';
  end if;

  if new.status = 'archived' and new.archived_at is null then
    new.archived_at := statement_timestamp();
  elsif new.status = 'active' then
    new.archived_at := null;
  end if;
  return new;
end;
$$;

create trigger classes_validate_owner
  before insert or update on public.classes
  for each row execute function private.validate_class_owner();
create trigger classes_set_updated_at
  before update on public.classes
  for each row execute function private.set_updated_at();

create or replace function private.add_class_owner_membership()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.memberships (class_id, user_id, member_role)
  values (new.id, new.teacher_id, 'teacher')
  on conflict (class_id, user_id) do nothing;
  return new;
end;
$$;

create trigger classes_add_owner_membership
  after insert on public.classes
  for each row execute function private.add_class_owner_membership();

create or replace function private.validate_membership_role()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  profile_role public.app_role;
begin
  select p.role into profile_role from public.profiles p where p.user_id = new.user_id;
  if profile_role is null then
    raise exception using errcode = '23503', message = 'membership profile does not exist';
  end if;
  if (new.member_role = 'student' and profile_role <> 'student')
     or (new.member_role = 'teacher' and profile_role not in ('teacher', 'admin')) then
    raise exception using errcode = '23514', message = 'membership role does not match application role';
  end if;
  return new;
end;
$$;

create trigger memberships_validate_role
  before insert or update on public.memberships
  for each row execute function private.validate_membership_role();
create trigger memberships_set_updated_at
  before update on public.memberships
  for each row execute function private.set_updated_at();

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function private.set_updated_at();
create trigger lessons_set_updated_at
  before update on public.lessons
  for each row execute function private.set_updated_at();
create trigger assets_set_updated_at
  before update on public.assets
  for each row execute function private.set_updated_at();
create trigger assignments_set_updated_at
  before update on public.assignments
  for each row execute function private.set_updated_at();
create trigger teacher_reviews_set_updated_at
  before update on public.teacher_reviews
  for each row execute function private.set_updated_at();

create or replace function private.protect_lesson_version()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    if old.status <> 'draft' then
      raise exception using errcode = '55000', message = 'published lesson versions cannot be deleted';
    end if;
    return old;
  end if;

  if tg_op = 'INSERT' and new.status <> 'draft'
     and coalesce(current_setting('app.lesson_publish_context', true), '') <> 'on' then
    raise exception using errcode = '55000', message = 'lesson versions must be published through the publish workflow';
  end if;

  if tg_op = 'UPDATE' and old.status <> 'draft' then
    if new.lesson_id is distinct from old.lesson_id
       or new.version is distinct from old.version
       or new.content is distinct from old.content
       or new.content_hash is distinct from old.content_hash
       or new.source_version_id is distinct from old.source_version_id
       or new.created_by is distinct from old.created_by
       or new.created_at is distinct from old.created_at then
      raise exception using errcode = '55000', message = 'published lesson version content is immutable';
    end if;
    if old.status = 'archived' and new.status <> 'archived' then
      raise exception using errcode = '55000', message = 'archived lesson versions cannot be reactivated';
    end if;
    if old.status = 'published' and new.status not in ('published', 'archived') then
      raise exception using errcode = '55000', message = 'invalid lesson version lifecycle transition';
    end if;
  end if;

  if tg_op = 'UPDATE' and old.status = 'draft' and new.status <> old.status
     and coalesce(current_setting('app.lesson_publish_context', true), '') <> 'on' then
    raise exception using errcode = '55000', message = 'lesson versions must be published through the publish workflow';
  end if;

  if tg_op = 'INSERT' or new.content is distinct from old.content then
    new.content_hash := encode(extensions.digest(convert_to(new.content::text, 'UTF8'), 'sha256'), 'hex');
  end if;
  new.updated_at := statement_timestamp();
  return new;
end;
$$;

create trigger lesson_versions_protect
  before insert or update or delete on public.lesson_versions
  for each row execute function private.protect_lesson_version();

create or replace function private.validate_assignment()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  version_status public.lesson_version_status;
begin
  if tg_op = 'UPDATE' then
    if new.class_id is distinct from old.class_id
       or new.lesson_version_id is distinct from old.lesson_version_id then
      raise exception using errcode = '55000', message = 'assignment class and pinned lesson version are immutable';
    end if;
  end if;

  select lv.status into version_status
  from public.lesson_versions lv
  where lv.id = new.lesson_version_id;

  if tg_op = 'INSERT' and version_status <> 'published' then
    raise exception using errcode = '23514', message = 'new assignments must pin a currently published lesson version';
  end if;
  return new;
end;
$$;

create trigger assignments_validate
  before insert or update on public.assignments
  for each row execute function private.validate_assignment();

create or replace function private.validate_learning_event()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  assignment_class_id uuid;
  pinned_version_id uuid;
  current_class_status public.class_status;
begin
  select a.class_id, a.lesson_version_id, c.status
    into assignment_class_id, pinned_version_id, current_class_status
  from public.assignments a
  join public.classes c on c.id = a.class_id
  where a.id = new.assignment_id;

  if assignment_class_id is null then
    raise exception using errcode = '23503', message = 'assignment does not exist';
  end if;
  if pinned_version_id <> new.lesson_version_id then
    raise exception using errcode = '23514', message = 'event lesson version does not match assignment';
  end if;
  if current_class_status <> 'active' then
    raise exception using errcode = '23514', message = 'events cannot be added to an archived class';
  end if;
  if not exists (
    select 1 from public.memberships m
    where m.class_id = assignment_class_id
      and m.user_id = new.student_id
      and m.member_role = 'student'
  ) then
    raise exception using errcode = '42501', message = 'student is not a member of the assigned class';
  end if;
  return new;
end;
$$;

create trigger learning_events_validate
  before insert on public.learning_events
  for each row execute function private.validate_learning_event();

create or replace function private.prevent_learning_event_update()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception using errcode = '55000', message = 'learning events are append-only';
end;
$$;

create trigger learning_events_append_only
  before update on public.learning_events
  for each row execute function private.prevent_learning_event_update();

